export enum EpossHomeKeyEnum {
  UAM_MENU_KEY = 'userManagement',
  INVENTORY_MENU_KEY = 'inventory',
  APPROVALS_MENU_KEY = 'approvals',
  CONFIGURATION_MENU_KEY = 'configuration',
  MASTER_MENU_KEY = 'master',
  SALES_MENU_KEY = 'SALES',
  REPORTS_MENU_KEY = 'reports',
  FILES_MENU_KEY = 'FILES',
  CUSTOMER_TRANSACTIOn_MENU_KEY = 'customerTransaction',
  BOUTIQUE_MASTER_MENU_KEY = 'boutiqueMaster',
  BANKING_AND_REVENUE_MENU_KEY = 'bankingAndRevenue',
  BOD_EOD_MENU_KEY = 'bodEod',
  MONITORING_DASHBOARD = 'monitoringDashboard',
  GIFT_CARDS = 'giftCards',
  ACCEPT_ADVANCE = 'acceptAdvance',
  METAL_RATE = 'metalRate',
  VIEW_OFFLINE_EGHS = 'viewOfflineEghs',
  REQUEST_APPROVALS_STATUS = 'requestApprovalsStatus',
  BANK_DEPOSIT = 'bankDeposit',
  PIF_SERIES = 'pifSeries',
  EGHS_BANK_DEPOSIT = 'eghsBankDeposit',
  SERVICE_POSS_BANK_DEPOSIT = 'servicePossBankDeposit',
  APPVERSION_DASHBOARD = 'appVersionDashboard',
  CREATE_EDIT_USER_ROLE_MENU = 'createEditUserRoleMenu',
  ACCESS_CONTROL = 'accessControl',
  OCG_MENU_KEY = 'OCG'
}
