/*  
 * Copyright 2019. Titan Company Limited
 * All rights reserved.
 */

package com.titan.poss.file.jobs.tasklet;

import org.springframework.batch.core.ExitStatus;
import org.springframework.batch.core.StepContribution;
import org.springframework.batch.core.StepExecution;
import org.springframework.batch.core.StepExecutionListener;
import org.springframework.batch.core.scope.context.ChunkContext;
import org.springframework.batch.core.step.tasklet.Tasklet;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * 
 * @author Mindtree Ltd.
 * @version 1.0
 */

@Component
public class FileWritingCheckTasklet implements Tasklet, StepExecutionListener {

	private String query;

	private String fileAuditId;

	private boolean check;

	@Autowired
	private JdbcTemplate jdbcTemplate;

	/**
	 * 
	 */
	public FileWritingCheckTasklet() {
	}

	/**
	 * @param query
	 */
	public FileWritingCheckTasklet(String query, String fileAuditId) {
		this.query = query;
		this.fileAuditId = fileAuditId;
	}

	@Override
	public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext) throws Exception {
		String fileId = (String) chunkContext.getStepContext().getStepExecution().getJobExecution()
				.getExecutionContext().get(fileAuditId);
		Integer count = jdbcTemplate.queryForObject(query, new Object[] { fileId }, Integer.class);
		if (count > 0) {
			check = true;
		} else {
			check = false;
		}
		return RepeatStatus.FINISHED;
	}

	@Override
	public void beforeStep(StepExecution stepExecution) {
		// autogenerated

	}

	@Override
	public ExitStatus afterStep(StepExecution stepExecution) {
		if (check) {
			return ExitStatus.COMPLETED;
		}
		return ExitStatus.STOPPED;
	}
}
