import { SelectDropDownOption } from '../select-dropdown.model';
import { CheckBoxSelectedOption } from '../checkbox-grid.model';
export interface ReportFilterOption {
  id: string;
  description: string;
}

export interface ReportFilterConfig {
  boutiqueCode: string;
  regionCode: string;
  isBTQUser: boolean;
  isCorpUser: boolean;
  isRegUser: boolean;
}

export interface ReportFilterOptions {
  reportNames: ReportName[];
  brands: ReportFilterOption[];
  subBrands?: ReportFilterOption[];
  regions: ReportFilterOption[];
  levels: ReportFilterOption[];
  countries: SelectDropDownOption[];
  states: SelectDropDownOption[];
  towns: ReportFilterOption[];
  locations: ReportFilterOption[];
  productGroups: ReportFilterOption[];
  productCategories: ReportFilterOption[];
  binGroups: ReportFilterOption[];
  binCodes: ReportFilterOption[];
  paymentType: ReportFilterOption[];
  cnType: ReportFilterOption[];
  cnStatus: ReportFilterOption[];
  complexityCode: ReportFilterOption[];
  karatage: ReportFilterOption[];
  confirmedByRso: ReportFilterOption[];
  receiptType: ReportFilterOption[];
  issueType: ReportFilterOption[];
  transferTypes: ReportFilterOption[];
}

export interface ReportBTQCodePayload {
  brands: string[];
  regions: string[];
  levels: string[];
  countries: string[];
  states: string[];
  towns: string[];
}

export interface ReportName {
  name: string;
  reportDes: string;
  id: string;
  maxNoOfDays: number;
  reportType: string;
  reportGroup: string;
  isApplicableToTheRole?: boolean;
}

export interface ReportGroupLov {
  code: string;
  value: string;
}
export interface ReportField {
  reportFieldId: string;
  fieldName: string;
}

export interface GenerateReportRequest {
  fromDate: any;
  toDate: any;
  locationCode: string[];
  ownerType: string[];
  reportType: string;
  countryId: string;
  stateId: string;
  brandCode: string[];
  subBrandCode: string[];
  subRegionCode: string;
  townId: string[];
  customFields?: {
    data?: any;
    type?: string;
  };
  id?: string;
  employeeCode?: string;
  queryName?: string;
}

export interface Report {
  id: string;
  reportMasterId: string;
  status: string;
  reportType: string;
  reportDes: string;
}

export interface ReportReponse {
  reports: Report[];
  totalReports: number;
}

export interface LoadReportPayload {
  pageSize: number;
  pageIndex: number;
  reportDesc: string;
  reportGroup: string;
  reportStatus: string;
  referenceNumber: string;
  fromDate: string;
  toDate: string;
  selectedTab: number;
}

export interface SaveReportPayload {
  addRoles: {
    isExcluded: boolean;
    isMasked: boolean;
    reportFieldId: string;
    roleCode: string;
  }[];
  removeRoles?: string[];
}

export interface SaveReportRolePayload {
  addAccess: {
    fromAccessTime: string;
    reportId: string;
    toAccessTime: string;
  }[];
  removeAccess: string[];
  updateAccess: {
    fromAccessTime: string;
    id: string;
    toAccessTime: string;
  }[];
}

export interface ReportRoleSetting {
  id: string;
  reportId: string;
  reportName: string;
  toAccessTime: string;
  fromAccessTime: string;
  roleCode?: string;
  roleName?: string;
}
export interface AutoReportList {
  cronExpression: string;
  frequency: string;
  id: string;
  isAutoGenerated: boolean;
  reportId: string;
  reportDescription: string;
}

export interface LoadAutoReportPayload {
  pageSize: number;
  pageIndex: number;
  reportDesc?: string;
}
export interface LoadAutoReportResponse {
  autoReportList: AutoReportList[];
  totalElements: number;
}

export interface SaveAutoReportPayload {
  addScheduler: {
    cronExpression: string;
    frequency: string;
    reportId: string;
  }[];

  removeScheduler: string[];
  updateScheduler: {
    cronExpression: string;
    frequency: string;
    schedulerId: string;
  }[];
}

export interface SaveSearchParametersPayload {
  reportMasterId: string;
  data: {
    employeeCode?: string;
    queryName: string;
    savedQuery: {
      data: {};
      type: string;
    };
  };
}

export interface UpdateSearchParametersPayload {
  reportMasterId: string;
  queryId: string;
  data: {
    employeeCode?: string;
    queryName: string;
    savedQuery: {
      data: {};
      type: string;
    };
  };
}
export interface SearchParameter {
  reportMasterId: string;
  fromDate: any;
  toDate: any;
  locationCode: string[];
  ownerType: string[];
  reportType?: string;
  countryCode: string;
  stateId: string;
  brandCode: string[];
  subBrandCode?: string[];
  regionCode: string[];
  townId: string[];
  productGroupCode: string[];
  productCategoryCode: string[];
  binGroupCode: string[];
  paymentType: string[];
  id?: string;
  employeeCode?: string;
  queryName?: string;
  cnType: string[];
  cnStatus: string[];
  fiscalYear: string;
  karatage: string[];
  complexity: string[];
  confirmedByRso: string[];
  fromGrossWeight: string[];
  toGrossWeight: string[];
  fromValue: string[];
  toValue: string[];
  docNo: string;
  customerMobileNo: string;
  customerName: string;
  ulpNo: string;
  fromAmount: string;
  toAmount: string;
  issueType: string[];
  receiptType: string[];
  transferType: string[];
}

export interface IndividualReportSetting {
  fieldName: string;
  fieldType: string;
  id: string;
  isOptional: true;
  reportMasterId: string;
}

export interface SaveIndividualReportSetting {
  reportMasterId: string;

  data: {
    employeeCode: string;
    outputColumns: {
      data: any;
      type: string;
    };
    templateName: string;
  };
}

export interface LoadExcludedSettingRequestPayload {
  reportMasterId: string;
  employeeCode: string;
}
export interface LoadExcludedSettingPayload {
  reportSetting: CheckBoxSelectedOption[];
  templateId: string;
  templateName: string;
}

export interface UpdateIndividualReportSetting {
  templateId: string;
  reportMasterId: string;

  data: {
    employeeCode: string;
    outputColumns: {
      data: any;
      type: string;
    };
    templateName: string;
  };
}

export interface LoadSearchParameterPayload {
  reportMasterId: string;
  employeeCode?: string;
  queryName?: string;
}

export interface Karatage {
  karat: string;
  description: string;
  materialCode: string;
}
