export enum ReportTypes {
  DETAILED = 'DETAILS',
  SUMMARY = 'SUMMARY'
}

export enum ReportGroup {
  INVENTORY = 'INVENTORY',
  DISCOUNT = 'DISCOUNT'
}

export enum ReportHomeKeyEnum {
  REPORT_SETTING = 'reportSetting',
  INVENTORY_REPORT = 'inventoryReport',
  REPORT_LIST = 'reportList',
  ROLE_MAPPING = 'roleMapping',
  MANUAL_GENERATION = 'manual generation',
  AUTO_GENERATION = 'auto generation'
}

export enum ReportStatus {
  ALL = 'ALL',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  IN_PROGRESS = 'IN_PROGRESS'
}
export enum REPORT_GROUPS {
  PAYMENTS_REPORT = 'PAYMENTS_REPORT',
  PAYMENT_DETAIL_REPORT = 'PAYMENT_DETAIL_REPORT',
  INVENTORY_REPORT = 'INVENTORY_REPORT',
  DISCOUNTS_REPORT = 'DISCOUNTS_REPORT',
  DISCOUNTS_LOC_REPORT = 'DISCOUNT_ENABLED_LOCATION_REPORT',
  DISCOUNT_TXN_REPORT = 'DISCOUNT_TRANSACTION_DETAIL_REPORT',
  CREDIT_NOTES_REPORT = 'CREDIT_NOTES_REPORT',
  CN_REGISTER_REPORT = 'CN_REGISTER_REPORT',
  SALES_REPORT = 'SALES_REPORT',
  MONTHLY = 'MONTHLY',
  WEEKLY = 'WEEKLY',
  DAILY = 'DAILY',
  SUNDAY = 'SUNDAY',
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUN = 'SUN',
  MON = 'MON',
  TUE = 'TUE',
  WED = 'WED',
  THU = 'THU',
  FRI = 'FRI',
  SAT = 'SAT',
  RSOCode = 'RSO',
  OTHER_RECEIPT_REPORT = 'OTHER_RECEIPT_REPORT',
  OTHER_ISSUE_REPORT = 'OTHER_ISSUE_REPORT',
  STOCK_DETAIL_REPORT = 'STOCK_DETAIL_REPORT',
  STOCK_SUMMARY_REPORT = 'STOCK_SUMMARY_REPORT',
  SALES_ORDER_DETAILS = 'SALES_ORDER_DETAILS',
  CONVERSION = 'CONVERSION',
  STOCK_ISSUE_REPORT = 'STOCK_ISSUE_REPORT'
}
