export enum DiscountTypeEnum {
  RIVAAH_ASHIRWAAD_DISCOUNT = 'RIVAAH_ASHIRWAAD_DISCOUNT',
  EXCHANGE_OFFER_DISCOUNT = 'KARAT_EXCHANGE_OFFER_DISCOUNT',
  CATEGORY_DISCOUNT = 'CATEGORY_DISCOUNT',
  SLAB_BASED_DISCOUNT = 'SLAB_BASED_DISCOUNT',
  BILL_LEVEL_DISCOUNT = 'BILL_LEVEL_DISCOUNT',
  CO_BILL_LEVEL_DISCOUNT = 'CO_BILL_LEVEL_DISCOUNT',
  SYSTEM_DISCOUNT = 'SYSTEM_DISCOUNT',
  COIN_OFFER_DISCOUNT = 'COIN_OFFER_DISCOUNT',
  EMPLOYEE_DISCOUNT = 'EMPLOYEE_DISCOUNT',
  TATA_EMPLOYEE_DISCOUNT = 'TATA_EMPLOYEE_DISCOUNT',
  TSSS_DISCOUNT = 'TSSS_DISCOUNT',
  ITEM_GROUP_LEVEL_DISCOUNT = 'ITEM_GROUP_LEVEL_DISCOUNT',
  BEST_DEAL_DISCOUNT = 'BEST_DEAL_DISCOUNT',
  HIGH_VALUE_DISCOUNT = 'HIGH_VALUE_DISCOUNT',
  EMPOWERMENT_DISCOUNT = 'EMPOWERMENT_DISCOUNT',
  ULP_BIRTHDAY = 'ULP_DISCOUNT_BIRTHDAY',
  ULP_SPOUSE_BIRTHDAY = 'ULP_DISCOUNT_SPOUSE_BIRTHDAY',
  ULP_ANNIVERSARY = 'ULP_DISCOUNT_ANNIVERSARY',
  SYSTEM_DISCOUNT_GEP_PURITY = 'SYSTEM_DISCOUNT_GEP_PURITY',
  SYSTEM_DISCOUNT_DV = 'SYSTEM_DISCOUNT_DV',
  SYSTEM_DISCOUNT_GHS_BONUS = 'SYSTEM_DISCOUNT_GHS_BONUS',
  DIGI_GOLD_DISCOUNT = 'DIGI_GOLD_DISCOUNT',
  RIVAAH_CARD_DISCOUNT = 'RIVAAH_CARD_DISCOUNT',
  RIVAAH_CARD_ELIGIBILITY = 'RIVAAH_CARD_ELIGIBILITY',
  GRN_MULTIPLE_DISCOUNT = 'GRN_MULTIPLE_DISCOUNT'
}

export enum DiscountConfigTabEnum {
  PRODUCT_CATEGORY_MAPPING,
  PRODUCT_GROUP_MAPPING,
  LOCATION_MAPPING,
  DISCOUNT_APPILICABLE,
  EXCLUDE_CONFIG,
  SLAB_CONFIG,
  EXCHANGE_OFFER_CONFIG,
  REFER_BEST_DEAL_DISC,
  TSSS_CONFIG,
  MAX_CONFIG,
  AGE_CONFIG,
  APPLICABLE_THEME,
  EMPOWERMENT_CONFIG,
  RIVAAH_CARD_DISCOUNT,
  SCHEME_MAPPING
}

export enum DiscountExcludeConfigTabEnum {
  THEME_CODE = 'THEME_CODE',
  ITEM_CODE = 'ITEM_CODE',
  COMPLEXITY = 'COMPLEXITY_PERCENT',
  PER_GRAM_MC = 'MC_PER_GRAM',
  SCHEME_CODE = 'SCHEME_CODE'
}

export enum DiscountApplicableEnum {
  AB_CO_TYPE = 'ORDER_CONFIG',
  GRN_TYPE = 'DISCOUNT_GRN_CONFIG',
  TEP_TYPE = 'TEP_CONFIG',
  BASIC_CRITERIA_TYPE = 'BASIC_CRITERIA',
  CLUB_DISCOUNT_TYPE = 'CLUB_DISCOUNT_TYPE',
  CLUB_OTHER_OFFERS = 'CLUB_OTHER_OFFERS_CONFIG',
  CUMULATIVE_TYPE = 'CUMULATIVE_DETAILS',
  BEST_DEAL_TYPE = 'BEST_DEAL_DISCOUNT',
  EXCHANGE_OFFER_CONFIG = 'EXCHANGE_OFFER_CONFIG',
  EXCHANGE_OFFER_TYPE = 'EXCHANGE_OFFER_DISCOUNT',
  AB_CO_DATA = 'AB_CO_DATA',
  EMPOWERMENT_CONFIG = 'EMPOWERMENT_CONFIG',
  RIVAAH_ITEM_GROUP_LEVEL = 'RIVAAH_ITEM_GROUP_LEVEL',
  RIVAAH_BEST_DEAL = 'RIVAAH_BEST_DEAL'
}
export enum DiscountProductGroupTabEnum {
  PRODUCT_GROUP_TEP,
  PRODUCT_GROUP_1KT,
  PRODUCT_GROUP_2KT,
  PRODUCT_GROUP_UCP,
  PRODUCT_GROUP_MC
}

export enum DiscountProductGroupTypeEnum {
  PRODUCT_GROUP_UCP = 'UCP',
  PRODUCT_GROUP_MC = 'MC'
}

export enum DiscountChargeTypeEnum {
  UCP = 'ucp',
  MC = 'makingCharge',
  GC = 'goldCharge',
  WC = 'wastageCharge',
  SC = 'stoneCharge',
  VALUE_PER_GRAM = 'valuePerGms'
}

export enum DiscountBasedOnEnum {
  WEIGHT_BASED = 'WEIGHT_BASED',
  CARAT_BASED = 'CARAT_BASED',
  VALUE_BASED = 'VALUE_BASED'
}

export enum DiscountBasedOnTypesEnum {
  GROSS_WEIGHT = 'GROSS_WEIGHT',
  PRE_DISCOUNT_TAX = 'PRE_DISCOUNT_TAX',
  SINGLE_STONE = 'SINGLE_STONE',
  NET_WEIGHT = 'NET_WEIGHT',
  PRE_DISCOUNT_WITHOUT_TAX = 'PRE_DISCOUNT_WITHOUT_TAX',
  CUMULATIVE_STONE = 'CUMULATIVE_STONE'
}

export enum SlabConfigFieldsEnum {
  SLAB_NAME = 'slabName',
  MIN = 'min',
  MAX = 'max'
}

export enum DiscountCompEnum {
  REGULAR = 'REGULAR',
  PREVIEW = 'PREVIEW',
  AB = 'AB',
  CO = 'CO',
  RIVA = 'RIVA'
}

export enum DiscountValuePerFielsEnum {
  REGULAR = 'regular',
  CHARGE = 'charge',
  PREVIEW = 'preview',
  AB = 'ab',
  CO = 'co',
  RIVA = 'riva'
}

export enum DiscountDetailsPopupTabEnum {
  ITEM_LEVEL_DISCOUNT,
  BILL_LEVEL_DISCOUNT,
  CO_BILL_LEVEL_DISCOUNT,
  EXCHANGE_OFFER_DISCOUNT,
  COIN_OFFER_DISCOUNT,
  SYSTEM_DISCOUNT,
  RIVAAH_CARD_DISCOUNT,
  KARAT_EXCHANGE_OFFER_DISCOUNT,
  SYSTEM_DISCOUNT_GEP_PURITY
}

export enum DiscountComponentNameEnum {
  MAKING_CHARGE = 'MAKING_CHARGE',
  METAL_CHARGE = 'METAL_CHARGE',
  STONE_CHARGE = 'STONE_CHARGE',
  UNIT_WEIGHT = 'UNIT_WEIGHT',
  UCP = 'UCP'
}

export enum DiscountClubTypeEnum {
  TYPE_1 = 'TYPE1',
  TYPE_2 = 'TYPE2',
  TYPE_3 = 'TYPE3'
}

export enum DiscountLovTypesEnum {
  DISCOUNT_TYPE = 'DISCOUNT_TYPE',
  CLUBBING_DISCOUNT_TYPE = 'CLUBBING_DISCOUNT_TYPE',
  APPROVAL_ROLES = 'APPROVAL_ROLES'
}

export enum DiscountEnums {
  OWNERTYPE = 'OWNERTYPE',
  NEW = 'new',
  REQUEST_NEW = 'NEW',
  REQUEST_AMENDMENT = 'AMENDMENT'
}

export enum DiscountPopupEnum {
  DISCOUNT_VALUE_DETAILS = 'DISCOUNT_VALUE_DETAILS'
}

export enum DiscountCompTypeEnum {
  REGULAR = 'REGULAR',
  PREVIEW = 'PREVIEW',
  AB = 'AB',
  CO = 'CO',
  RIVAAH = 'RIVAAH'
}

export enum ProductGroupTypesEnum {
  PLAIN = 'PLAIN',
  STUDDED = 'STUDDED',
  MIA = 'MIA'
}

export enum DropdownSearchOptionsEnum {
  DISCOUNT_CODE = 'DiscountCode',
  OCCASION = 'Occasion',
  CN_TYPE = 'CN_TYPE',
  CONFIG_NAME = 'CONFIG_NAME'
}

export enum StatusListEnum {
  RUNNING = 'RUNNING',
  ACTIVE_AND_NOT_RUNNING = 'ACTIVE_AND_NOT_RUNNING',
  INACTIVE = 'INACTIVE'
}

export enum PublishStatusListEnum {
  PUBLISHED = 'PUBLISHED',
  NOT_PUBLISHED = 'NOT_PUBLISHED'
}

export enum SlabErrorEnum {
  SLAB_NAME = 'SLAB_NAME',
  MIN_MAX = 'MIN_MAX'
}
