export enum RequestStatusTypesEnum {
  APPROVED = 'APPROVED',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED'
}
export enum WorkflowTypeEnum {
  MANUAL_BILL = 'MANUAL_BILL',
  MANUAL_AB_BILL = 'ADVANCE_BOOKING_MANUAL_BILL',
  REQUEST_APPROVER_L1 = 'REQUEST_APPROVER_L1',
  MANUAL_BILL_GRF = 'MANUAL_BILL_GRF',
}
