import {
  Report,
  ReportName,
  ReportGroupLov,
  AutoReportList,
  CheckBoxSelectedOption,
  ReportField,
  ReportRoleSetting,
  ComplexityCode,
  Karatage
} from '@poss-web/shared/models';

export class ReportAdaptor {
  static getReport(data: any): Report {
    return {
      reportDes: data.reportDescription,
      reportType: data.reportType,
      status: data.status,
      id: data.id,
      reportMasterId: data.reportMasterId
    };
  }

  static getReportName(data: any): ReportName {
    return {
      name: data.reportName,
      id: data.id,
      maxNoOfDays: data.maxNoOfDays,
      reportType: data.reportType,
      reportGroup: data.reportGroup,
      reportDes: data.reportDescription,
      isApplicableToTheRole: data?.isMappedToTheRole
    };
  }

  static getReportGroup(data: any): ReportGroupLov {
    return data;
  }

  static getAutoReportList(data: any): AutoReportList {
    return {
      cronExpression: data.cronExpression,
      frequency: data.frequency,
      id: data.id,
      isAutoGenerated: data.isAutoGenerated,
      reportId: data.reportId,
      reportDescription: data.reportDescription
    };
  }

  static getReportSettings(data: any): CheckBoxSelectedOption {
    return {
      columnHeaderKey: data.roleCode,
      rowHeaderKey: data.reportFieldId,
      id: data.id
    };
  }

  static getExcludedReportSettings(data: any): CheckBoxSelectedOption {
    return {
      columnHeaderKey: data,
      rowHeaderKey: data,
      id: data
    };
  }
  static getReportIndividualSettings(data: any): CheckBoxSelectedOption {
    return {
      columnHeaderKey: data.roleCode,
      rowHeaderKey: data.fieldName,
      id: data.id
    };
  }

  static getReportFields(data: any): ReportField {
    return {
      reportFieldId: data.id,
      fieldName: data.fieldName
    };
  }

  static getReportRoles(data: any): ReportRoleSetting {
    return {
      id: data.id,
      reportId: data.reportId,
      roleCode: data.roleCode,
      roleName: data.roleDescrption,
      reportName: data.reportName,
      toAccessTime: data.toAccessTime === 0 ? '00:00' : data.toAccessTime,
      fromAccessTime: data.fromAccessTime === 0 ? '00:00' : data.fromAccessTime
    };
  }

  static getComplexityCode(data: any): ComplexityCode {
    return {
      complexityCode: data.complexityCode,
      description: data.description
    };
  }

  static getKaratage(data: any): Karatage {
    return {
      karat: data.karat,
      description: data.description,
      materialCode: data.materialCode
    };
  }
}
