import { HttpClient } from '@angular/common/http';
import { ApiService } from '@poss-web/shared/util-api-service';
import { of } from 'rxjs';
import { ProductGroupDataService } from './product-group.data.service';
import { CachingStrategySetting } from '@poss-web/shared/models';
import {
  CacheableApiService,
  DexieService,
  HashkeyGeneratorService,
  StorageFacade
} from '@poss-web/shared/util-cacheable-api-service';
import { fakeAsync } from '@angular/core/testing';
export function apiServiceFactory(httpClient: HttpClient, apiURL: string) {
  return new ApiService(httpClient, apiURL);
}
describe('Product Groups', () => {
  let service: ProductGroupDataService;
  let cacheableApiService: CacheableApiService;

  let productGroups: any;
  let productGroups1: any;
  let productGroupsSummary: any;
  let productGroupByCodeData: any;
  let productGroupByCodeData1: any;
  beforeAll(() => {
    productGroups = {
      results: [
        {
          productGroupCode: '1',
          productType: 'STUDDED',
          description: '1234567890',
          materialCode: 'S',
          orgCode: '',
          configDetails: {
            productCategoryFlag: null,
            isActive: true,
            isMia: false,
            goldPriceMandatory: true,
            platinumPriceMandatory: true,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: true,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: true,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: true,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: 'no'
          },
          isActive: true
        },
        {
          productGroupCode: '100',
          productType: null,
          description: 'GOLD',
          materialCode: '',
          orgCode: '',
          configDetails: {
            productCategoryFlag: null,
            isActive: true,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: true,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: true,
            isLoyalityPointsRedeemable: true,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: true,
            isBiMetal: true,
            isMiaUCP: true,
            isPlainStudPricing: true,
            isJewelleryItem: true,
            quickSilverReedemptionAllowed: true,
            whetherItIsStuddedOrNot: true,
            TEPIssueOutCategory: true,
            DynamicF1CalculationYesOrNo: 'yes',
            description: 'platinum',
            materialCode: '1',
            orgCode: 'ABC',
            productType: '1',
            eligibleForBillLevelDiscount: true
          },
          isActive: true
        },
        {
          productGroupCode: '10000',
          productType: 'PLAINPLATINUM',
          description: 'PLATINUM',
          materialCode: '',
          orgCode: '',
          configDetails: {
            productCategoryFlag: '1',
            isActive: true,
            isMia: false,
            goldPriceMandatory: true,
            platinumPriceMandatory: true,
            makingChargesMandatory: true,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: true,
            isPlainStudPricing: true,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: true,
            DynamicF1CalculationYesOrNo: 'yes'
          },
          isActive: true
        },
        {
          productGroupCode: '100001',
          productType: null,
          description: 'gold',
          materialCode: '',
          orgCode: '',
          configDetails: {
            isActive: false,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: '1'
          },
          isActive: true
        },
        {
          productGroupCode: '1000212',
          productType: null,
          description: 'good',
          materialCode: '',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: null
          },
          isActive: true
        },
        {
          productGroupCode: '1001',
          productType: 'STUDDED',
          description: 'good',
          materialCode: 'P',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: true,
            platinumPriceMandatory: true,
            makingChargesMandatory: true,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: null
          },
          isActive: true
        },
        {
          productGroupCode: '1002120',
          productType: null,
          description: 'metal',
          materialCode: '',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: null
          },
          isActive: true
        },
        {
          productGroupCode: '10032',
          productType: 'STUDDED',
          description: 'good',
          materialCode: '',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: true,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: null
          },
          isActive: true
        },
        {
          productGroupCode: '101',
          productType: null,
          description: 'Titan Watches',
          materialCode: '',
          orgCode: '',
          configDetails: {
            productCategoryFlag: null,
            isActive: true,
            isMia: false,
            goldPriceMandatory: true,
            platinumPriceMandatory: true,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: true,
            isFOCApplicable: true,
            isBiMetal: true,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: true,
            quickSilverReedemptionAllowed: true,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: false,
            eligibleForBillLevelDiscount: false
          },
          isActive: true
        },
        {
          productGroupCode: '1020',
          productType: null,
          description: '  pal',
          materialCode: '',
          orgCode: '',
          configDetails: {
            isActive: false,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false
          },
          isActive: true
        },
        {
          productGroupCode: '102000',
          productType: null,
          description: 'gold',
          materialCode: '',
          orgCode: '',
          configDetails: {
            isActive: false,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false
          },
          isActive: true
        },
        {
          productGroupCode: '10221',
          productType: null,
          description: 'Gold',
          materialCode: '',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false
          },
          isActive: true
        },
        {
          productGroupCode: '111',
          productType: null,
          description: ' platinum',
          materialCode: '',
          orgCode: '',
          configDetails: {
            isActive: false,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false
          },
          isActive: true
        },
        {
          productGroupCode: '119',
          productType: 'STUDDED',
          description: '123',
          materialCode: 'S',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: true,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: true,
            DynamicF1CalculationYesOrNo: 'yes'
          },
          isActive: true
        },
        {
          productGroupCode: '12',
          productType: null,
          description: 'gold',
          materialCode: '',
          orgCode: '',
          configDetails: {
            isActive: false,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false
          },
          isActive: true
        },
        {
          productGroupCode: '120021',
          productType: 'STUDDED',
          description: 'GOLD',
          materialCode: 'A',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: 'yes'
          },
          isActive: true
        },
        {
          productGroupCode: '123',
          productType: null,
          description: 'gold',
          materialCode: '',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: null
          },
          isActive: true
        },
        {
          productGroupCode: '123000',
          productType: 'STUDDED',
          description: 'good',
          materialCode: '',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: true,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: null
          },
          isActive: true
        },
        {
          productGroupCode: '1234',
          productType: 'PLAINGOLD',
          description: 'gold',
          materialCode: 'P',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: true,
            platinumPriceMandatory: true,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: false
          },
          isActive: true
        },
        {
          productGroupCode: '12345',
          productType: null,
          description: 'gold',
          materialCode: '',
          orgCode: '',
          configDetails: {
            isActive: false,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: true,
            isPlainGold: true,
            isGRFStuddedCategory: true,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: false
          },
          isActive: true
        }
      ],
      pageNumber: 0,
      pageSize: 20,
      totalPages: 6,
      totalElements: 101
    };

    productGroups1 = {
      results: [
        {
          productGroupCode: '1',
          productType: 'STUDDED',
          description: '1234567890',
          itemTypeCode: 'S',
          orgCode: '',
          configDetails: {
            productCategoryFlag: null,
            isActive: true,
            isMia: false,
            goldPriceMandatory: true,
            platinumPriceMandatory: true,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: true,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: true,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: true,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: 'no'
          },
          isActive: true
        },
        {
          productGroupCode: '100',
          productType: null,
          description: 'GOLD',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            productCategoryFlag: null,
            isActive: true,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: true,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: true,
            isLoyalityPointsRedeemable: true,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: true,
            isBiMetal: true,
            isMiaUCP: true,
            isPlainStudPricing: true,
            isJewelleryItem: true,
            quickSilverReedemptionAllowed: true,
            whetherItIsStuddedOrNot: true,
            TEPIssueOutCategory: true,
            DynamicF1CalculationYesOrNo: 'yes',
            description: 'platinum',
            materialCode: '1',
            orgCode: 'ABC',
            productType: '1',
            eligibleForBillLevelDiscount: true
          },
          isActive: true
        },
        {
          productGroupCode: '10000',
          productType: 'PLAINPLATINUM',
          description: 'PLATINUM',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            productCategoryFlag: '1',
            isActive: true,
            isMia: false,
            goldPriceMandatory: true,
            platinumPriceMandatory: true,
            makingChargesMandatory: true,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: true,
            isPlainStudPricing: true,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: true,
            DynamicF1CalculationYesOrNo: 'yes'
          },
          isActive: true
        },
        {
          productGroupCode: '100001',
          productType: null,
          description: 'gold',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            isActive: false,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: '1'
          },
          isActive: true
        },
        {
          productGroupCode: '1000212',
          productType: null,
          description: 'good',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: null
          },
          isActive: true
        },
        {
          productGroupCode: '1001',
          productType: 'STUDDED',
          description: 'good',
          itemTypeCode: 'P',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: true,
            platinumPriceMandatory: true,
            makingChargesMandatory: true,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: null
          },
          isActive: true
        },
        {
          productGroupCode: '1002120',
          productType: null,
          description: 'metal',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: null
          },
          isActive: true
        },
        {
          productGroupCode: '10032',
          productType: 'STUDDED',
          description: 'good',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: true,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: null
          },
          isActive: true
        },
        {
          productGroupCode: '101',
          productType: null,
          description: 'Titan Watches',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            productCategoryFlag: null,
            isActive: true,
            isMia: false,
            goldPriceMandatory: true,
            platinumPriceMandatory: true,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: true,
            isFOCApplicable: true,
            isBiMetal: true,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: true,
            quickSilverReedemptionAllowed: true,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: false,
            eligibleForBillLevelDiscount: false
          },
          isActive: true
        },
        {
          productGroupCode: '1020',
          productType: null,
          description: '  pal',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            isActive: false,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false
          },
          isActive: true
        },
        {
          productGroupCode: '102000',
          productType: null,
          description: 'gold',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            isActive: false,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false
          },
          isActive: true
        },
        {
          productGroupCode: '10221',
          productType: null,
          description: 'Gold',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false
          },
          isActive: true
        },
        {
          productGroupCode: '111',
          productType: null,
          description: ' platinum',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            isActive: false,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false
          },
          isActive: true
        },
        {
          productGroupCode: '119',
          productType: 'STUDDED',
          description: '123',
          itemTypeCode: 'S',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: true,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: true,
            DynamicF1CalculationYesOrNo: 'yes'
          },
          isActive: true
        },
        {
          productGroupCode: '12',
          productType: null,
          description: 'gold',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            isActive: false,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false
          },
          isActive: true
        },
        {
          productGroupCode: '120021',
          productType: 'STUDDED',
          description: 'GOLD',
          itemTypeCode: 'A',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: 'yes'
          },
          isActive: true
        },
        {
          productGroupCode: '123',
          productType: null,
          description: 'gold',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: null
          },
          isActive: true
        },
        {
          productGroupCode: '123000',
          productType: 'STUDDED',
          description: 'good',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: true,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: null
          },
          isActive: true
        },
        {
          productGroupCode: '1234',
          productType: 'PLAINGOLD',
          description: 'gold',
          itemTypeCode: 'P',
          orgCode: '',
          configDetails: {
            isActive: true,
            isMia: true,
            goldPriceMandatory: true,
            platinumPriceMandatory: true,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: false,
            isPlainGold: false,
            isGRFStuddedCategory: false,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: false
          },
          isActive: true
        },
        {
          productGroupCode: '12345',
          productType: null,
          description: 'gold',
          itemTypeCode: '',
          orgCode: '',
          configDetails: {
            isActive: false,
            isMia: false,
            goldPriceMandatory: false,
            platinumPriceMandatory: false,
            makingChargesMandatory: false,
            stoneChargesMandatory: false,
            isEligibleForLoyalityPoints: false,
            printGuarnteeCard: false,
            eligibleForBillLevelDiscount: true,
            isPlainGold: true,
            isGRFStuddedCategory: true,
            isLoyalityPointsRedeemable: false,
            isPlainSilver: false,
            isPlainPlatinum: false,
            isFOCApplicable: false,
            isBiMetal: false,
            isMiaUCP: false,
            isPlainStudPricing: false,
            isJewelleryItem: false,
            quickSilverReedemptionAllowed: false,
            whetherItIsStuddedOrNot: false,
            TEPIssueOutCategory: false,
            DynamicF1CalculationYesOrNo: false
          },
          isActive: true
        }
      ],
      pageNumber: 0,
      pageSize: 20,
      totalPages: 6,
      totalElements: 101
    };
    productGroupsSummary = {
      results: [
        {
          productGroupCode: '1',
          description: '1234567890'
        },
        {
          productGroupCode: '100',
          description: 'GOLD'
        },
        {
          productGroupCode: '10000',
          description: 'PLATINUM'
        },
        {
          productGroupCode: '100001',
          description: 'gold'
        },
        {
          productGroupCode: '1000212',
          description: 'good'
        },
        {
          productGroupCode: '1001',
          description: 'good'
        },
        {
          productGroupCode: '1002120',
          description: 'metal'
        },
        {
          productGroupCode: '10032',
          description: 'good'
        },
        {
          productGroupCode: '101',
          description: 'Titan Watches'
        },
        {
          productGroupCode: '1020',
          description: '  pal'
        },
        {
          productGroupCode: '102000',
          description: 'gold'
        },
        {
          productGroupCode: '10221',
          description: 'Gold'
        },
        {
          productGroupCode: '111',
          description: ' platinum'
        },
        {
          productGroupCode: '119',
          description: '123'
        },
        {
          productGroupCode: '12',
          description: 'gold'
        },
        {
          productGroupCode: '120021',
          description: 'GOLD'
        },
        {
          productGroupCode: '123',
          description: 'gold'
        },
        {
          productGroupCode: '123000',
          description: 'good'
        },
        {
          productGroupCode: '1234',
          description: 'gold'
        },
        {
          productGroupCode: '12345',
          description: 'gold'
        }
      ],
      pageNumber: 0,
      pageSize: 20,
      totalPages: 5,
      totalElements: 88
    };
    productGroupByCodeData = {
      productGroupCode: 1,
      productType: 'STUDDED',
      description: '1234567890',
      materialCode: 'S',
      orgCode: '',
      configDetails: {
        productCategoryFlag: null,
        isActive: true,
        isMia: false,
        goldPriceMandatory: true,
        platinumPriceMandatory: true,
        makingChargesMandatory: false,
        stoneChargesMandatory: false,
        isEligibleForLoyalityPoints: false,
        printGuarnteeCard: false,
        eligibleForBillLevelDiscount: false,
        isPlainGold: true,
        isGRFStuddedCategory: false,
        isLoyalityPointsRedeemable: false,
        isPlainSilver: false,
        isPlainPlatinum: false,
        isFOCApplicable: false,
        isBiMetal: false,
        isMiaUCP: false,
        isPlainStudPricing: true,
        isJewelleryItem: false,
        quickSilverReedemptionAllowed: true,
        whetherItIsStuddedOrNot: false,
        TEPIssueOutCategory: false,
        DynamicF1CalculationYesOrNo: 'no'
      },
      isActive: true
    };
    productGroupByCodeData1 = {
      productGroupCode: 1,
      productType: 'STUDDED',
      description: '1234567890',
      itemTypeCode: 'S',
      orgCode: '',
      configDetails: {
        productCategoryFlag: null,
        isActive: true,
        isMia: false,
        goldPriceMandatory: true,
        platinumPriceMandatory: true,
        makingChargesMandatory: false,
        stoneChargesMandatory: false,
        isEligibleForLoyalityPoints: false,
        printGuarnteeCard: false,
        eligibleForBillLevelDiscount: false,
        isPlainGold: true,
        isGRFStuddedCategory: false,
        isLoyalityPointsRedeemable: false,
        isPlainSilver: false,
        isPlainPlatinum: false,
        isFOCApplicable: false,
        isBiMetal: false,
        isMiaUCP: false,
        isPlainStudPricing: true,
        isJewelleryItem: false,
        quickSilverReedemptionAllowed: true,
        whetherItIsStuddedOrNot: false,
        TEPIssueOutCategory: false,
        DynamicF1CalculationYesOrNo: 'no'
      },
      isActive: true
    };
  });
  beforeEach(() => {
    const http: HttpClient = null;
    const indexedDBStorage = new DexieService();
    const cachingStrategySettings: CachingStrategySetting[] = [
      {
        type: 3,
        name: 'InvalidatedBySize',
        category: 'cache',
        size: 1,
        unit: 'MB'
      }
    ];
    cacheableApiService = new CacheableApiService(
      new HashkeyGeneratorService('test'),
      new StorageFacade(indexedDBStorage),
      new ApiService(http, 'test'),
      cachingStrategySettings
    );

    service = new ProductGroupDataService(cacheableApiService);
  });

  it('should be created', () => {
    fakeAsync(() => {
      expect(service).toBeTruthy();
    });
  });

  it('should get product groups', () => {
    spyOn(cacheableApiService, 'get').and.returnValue(of(productGroupsSummary));
    service.getProductGroups().subscribe(x => {
      expect(x).toEqual(productGroupsSummary.results);
    });
  });

  it('should get total Elements from product groups', () => {
    spyOn(cacheableApiService, 'get').and.returnValue(of(productGroups));
    service.getProductGroupMasterCount().subscribe(x => {
      expect(x).toEqual(productGroups.totalElements);
    });
  });

  it('should get product Group Summary', () => {
    spyOn(cacheableApiService, 'get').and.returnValue(of(productGroups1));
    service.getProductGroupMaster().subscribe(x => {
      expect(x).toEqual(productGroups.results);
    });
  });

  it('should get Product Group by Product Group Code', () => {
    // act
    const productGroupCode = '71';
    spyOn(cacheableApiService, 'get').and.returnValue(
      of(productGroupByCodeData1)
    );
    service.getProductGroupByCode(productGroupCode).subscribe(x => {
      expect(x).toEqual(productGroupByCodeData);
    });
  });
});
