import { POSS_WEB_API_URL } from '@poss-web/shared/util-config';
import { TestBed } from '@angular/core/testing';
import { ReportsService } from './reports.service';
import {
  HttpClientTestingModule,
  HttpTestingController
} from '@angular/common/http/testing';
import {
  LoadAutoReportPayload,
  LoadSearchParameterPayload,
  responseTypeEnum,
  SaveAutoReportPayload
} from '@poss-web/shared/models';

import {
  getGenerateReportUrl,
  getReportBinGroupsUrl,
  getReportListUrl,
  getReportNamesUrl,
  getReportGroupUrl,
  getReportRolesUrl,
  getReportFieldsUrl,
  getReportSettingsUrl,
  getSaveReportRoleSettingsUrl,
  getAutoReportListUrl,
  getAutoReportSaveUrl,
  getRolesUrl,
  getSaveReportSettingsUrl,
  getDownloadReportUserUrl,
  getDownloadReportSystemUrl,
  getSearchParameterUrl,
  getAutoGeneratedReportListUrl,
  getSearchParameterSaveUrl,
  getPatchSearchParameterUrl,
  getIndividualSettingUrl,
  getExcludedIndividualSettingUrl,
  getIndividualSettingSaveUrl,
  getIndividualSettingPatchUrl,
  getCnTypeEngineUrl,
  getComplexityCodeUrl,
  getKaratageUrl
} from '@poss-web/shared/util-api-service';
import {
  ReportHelper,
  BinGroupDataAdaptor
} from '@poss-web/shared/util-adaptors';
describe('ReportsService', () => {
  let httpTestingController: HttpTestingController;
  let reportsService: ReportsService;
  const apiUrl = 'http://localhost:3000';

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [
        ReportsService,
        {
          provide: POSS_WEB_API_URL,
          useValue: apiUrl
        }
      ]
    });
    httpTestingController = TestBed.inject(HttpTestingController);
    reportsService = TestBed.inject(ReportsService);
  });
  afterEach(() => {
    httpTestingController.verify();
  });
  it('should be created', () => {
    expect(reportsService).toBeTruthy();
  });
  describe('generateReport', () => {
    it('should call POST api method with correct url and params', () => {
      const payload = {
        reportId: '1',
        request: {
          fromDate: '12-03-2021',
          toDate: '16-03-2021',
          locationCode: ['URB'],
          ownerType: ['L1'],
          reportType: 'SUMMARY',
          countryId: '1',
          stateId: '29',
          subBrandCode: ['mia'],
          brandCode: ['mia'],
          subRegionCode: 'east',
          townId: ['1'],
          customFields: {
            data: {}
          }
        }
      };

      const url = getGenerateReportUrl(payload.reportId);

      reportsService
        .generateReport(payload.reportId, payload.request)
        .subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('POST');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('loadReports', () => {
    const payload = {
      pageSize: 1,
      pageIndex: 10,
      reportDesc: 'STOCK RECEIVE',
      reportGroup: 'INVENTORY ',
      reportStatus: 'completed',
      referenceNumber: '102',
      fromDate: '12-03-2021',
      toDate: '15-03-2021',
      selectedTab: 0
    };
    it('should call POST api method with correct url and params', () => {
      spyOn(ReportHelper, 'getReports').and.returnValue({});
      const url = getReportListUrl(payload);

      reportsService.loadReports(payload).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('POST');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
    it('should call POST api method with correct url and params 2', () => {
      payload.selectedTab = 1;
      spyOn(ReportHelper, 'getReports').and.returnValue({});
      const url = getAutoGeneratedReportListUrl(payload);

      reportsService.loadReports(payload).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('POST');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });

    it('should call POST api method with correct url and params 3', () => {
      payload.reportDesc = null;
      payload.selectedTab = 1;
      spyOn(ReportHelper, 'getReports').and.returnValue({});
      const url = getAutoGeneratedReportListUrl(payload);

      reportsService.loadReports(payload).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('POST');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });

    it('should call POST api method with correct url and params 4', () => {
      payload.reportStatus = null;
      payload.selectedTab = 1;
      spyOn(ReportHelper, 'getReports').and.returnValue({});
      const url = getAutoGeneratedReportListUrl(payload);

      reportsService.loadReports(payload).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('POST');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });

    it('should call POST api method with correct url and params 5', () => {
      payload.reportGroup = null;
      payload.selectedTab = 1;
      spyOn(ReportHelper, 'getReports').and.returnValue({});
      const url = getAutoGeneratedReportListUrl(payload);

      reportsService.loadReports(payload).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('POST');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });

    it('should call POST api method with correct url and params 6', () => {
      payload.referenceNumber = null;
      payload.selectedTab = 1;
      spyOn(ReportHelper, 'getReports').and.returnValue({});
      const url = getAutoGeneratedReportListUrl(payload);

      reportsService.loadReports(payload).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('POST');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('getBinGroups', () => {
    it('should call GET api method with correct url and params', () => {
      spyOn(BinGroupDataAdaptor, 'binGroupDataFromJson').and.returnValue({});
      const url = getReportBinGroupsUrl();

      reportsService.getBinGroups().subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('loadReportGroups', () => {
    const url = getReportGroupUrl();
    it('should call GET api method with correct url and params', () => {
      spyOn(ReportHelper, 'getReportGroups').and.returnValue({});
      reportsService.loadReportGroups().subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('loadReportNames', () => {
    const type = 'INVENTORY_GROUP';
    const url = getReportNamesUrl(type);
    it('should call GET api method with correct url and params', () => {
      spyOn(ReportHelper, 'getReportNames').and.returnValue({});
      reportsService.loadReportNames(type).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('loadReportRoles', () => {
    const payload = {
      roleCode: 'commercial',
      reportDes: 'stock summary report'
    };
    const url = getReportRolesUrl(payload.reportDes, payload.roleCode);
    it('should call GET api method with correct url and params', () => {
      spyOn(ReportHelper, 'getReportRoles').and.returnValue({});
      reportsService
        .loadReportRoles(payload.reportDes, payload.roleCode)
        .subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('loadReportFields', () => {
    const reportId = '10';
    const url = getReportFieldsUrl(reportId);
    it('should call GET api method with correct url and params', () => {
      reportsService.loadReportFields(reportId).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({ results: [] });
    });
  });

  describe('loadReportSettings', () => {
    const payload = {
      reportId: '1',
      roleCode: 'commercial'
    };
    const url = getReportSettingsUrl(payload.reportId, payload.roleCode);
    it('should call GET api method with correct url and params', () => {
      reportsService
        .loadReportSettings(payload.reportId, payload.roleCode)
        .subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({ results: [] });
    });
  });

  describe('saveReportRoleSetting', () => {
    const payload = {
      roleCode: 'commercial',
      request: {
        addAccess: [
          {
            fromAccessTime: '10:05',
            toAccessTime: '11:05',
            reportId: '1'
          }
        ],
        removeAccess: [],
        updateAccess: []
      }
    };
    const url = getSaveReportRoleSettingsUrl(payload.roleCode);
    it('should call GET api method with correct url and params', () => {
      reportsService
        .saveReportRoleSetting(payload.roleCode, payload.request)
        .subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('PATCH');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });
  describe('saveReportSettings', () => {
    const payload = {
      reportId: '1',
      request: {
        addRoles: [
          {
            reportFieldId: '1',
            isExcluded: true,
            isMasked: true,
            roleCode: 'commercial'
          }
        ],
        removeRoles: []
      }
    };
    const url = getSaveReportSettingsUrl(payload.reportId);
    it('should call GET api method with correct url and params', () => {
      reportsService
        .saveReportSettings(payload.reportId, payload.request)
        .subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('PATCH');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('getAutoReportList', () => {
    it('should call GET api method with correct url and params', () => {
      spyOn(ReportHelper, 'getAutoReportList').and.returnValue({});

      const payload: LoadAutoReportPayload = {
        pageIndex: 0,
        pageSize: 10,
        reportDesc: 'stock summary report'
      };
      const url = getAutoReportListUrl(
        payload.pageIndex,
        payload.pageSize,
        payload.reportDesc
      );

      reportsService.getAutoReportList(payload).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('saveAutoReportSettings', () => {
    it('should call GET api method with correct url and params', () => {
      const url = getAutoReportSaveUrl();
      const payload: SaveAutoReportPayload = {
        addScheduler: [
          {
            reportId: '1',
            cronExpression: '* * * * * *',
            frequency: 'DAILY'
          }
        ],
        removeScheduler: [],
        updateScheduler: []
      };
      reportsService.saveAutoReportSettings(payload).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('PATCH');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('getRoles', () => {
    it('should call GET api method with correct url and params', () => {
      const url = getRolesUrl();

      reportsService.getRoles().subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({results: [{data: 'abc'}]});
    });
  });
  describe('getSearchParameter', () => {
    it('should call GET api method with correct url and params', () => {
      spyOn(ReportHelper, 'getSearchParameter').and.returnValue({});
      let payload: LoadSearchParameterPayload = {
        reportMasterId: '123',
        employeeCode: '123'
      }
      const url = getSearchParameterUrl(payload.reportMasterId, payload.employeeCode);

      reportsService.getSearchParameter(payload).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({results: [{data: ''}]});
    });
  });
  describe('saveSearchParameter', () => {
    it('should call GET api method with correct url and params', () => {
      spyOn(ReportHelper, 'getSearchParameter').and.returnValue({});

      const url = getSearchParameterSaveUrl('123');

      reportsService.saveSearchParameter({reportMasterId: '123'} as any).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('POST');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('updateSearchParameter', () => {
    it('should call GET api method with correct url and params', () => {
      spyOn(ReportHelper, 'getSearchParameter').and.returnValue({});

      const url = getPatchSearchParameterUrl('123', '1');

      reportsService.updateSearchParameter({reportMasterId: '123', queryId: '1'} as any).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('PATCH');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('loadIndividualSetting', () => {
    it('should call GET api method with correct url and params', () => {
      spyOn(ReportHelper, 'getReportFields').and.returnValue({});

      const url = getIndividualSettingUrl('123');

      reportsService.loadIndividualSetting('123').subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('loadExcludedIndividualSetting', () => {
    it('should call GET api method with correct url and params', () => {
      spyOn(ReportHelper, 'getExcludedReportSettings').and.returnValue({});

      const url = getExcludedIndividualSettingUrl('123', '1');

      reportsService.loadExcludedIndividualSetting('123','1').subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('saveIndividualSetting', () => {
    it('should call GET api method with correct url and params', () => {

      const url = getIndividualSettingSaveUrl('123');

      reportsService.saveIndividualSetting({reportMasterId: '123'} as any).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('POST');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('updateIndividualSetting', () => {
    it('should call GET api method with correct url and params', () => {

      const url = getIndividualSettingPatchUrl('123', '1');

      reportsService.updateIndividualSetting({reportMasterId: '123', templateId: '1'} as any).subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('PATCH');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('loadCnType', () => {
    it('should call GET api method with correct url and params', () => {

      const url = getCnTypeEngineUrl();

      reportsService.loadCnType().subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('getComplexity', () => {
    it('should call GET api method with correct url and params', () => {
      spyOn(ReportHelper, 'getComplexityCodeData').and.returnValue({});

      const url = getComplexityCodeUrl();

      reportsService.getComplexity().subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });

  describe('getKaratage', () => {
    it('should call GET api method with correct url and params', () => {
      spyOn(ReportHelper, 'getKaratageData').and.returnValue({});

      const url = getKaratageUrl();

      reportsService.getKaratage().subscribe();

      const request = httpTestingController.expectOne(req => {
        return req.url === apiUrl + url.path;
      });
      expect(request.cancelled).toBeFalsy();
      expect(request.request.method).toEqual('GET');
      expect(request.request.responseType).toEqual('json');

      request.flush({});
    });
  });
});
