import { FileDownloadService } from '@poss-web/shared/util-common';
import {
  ApiService,
  getReportNamesUrl,
  getGenerateReportUrl,
  getReportListUrl,
  getReportRolesUrl,
  getReportFieldsUrl,
  getReportSettingsUrl,
  getReportBinGroupsUrl,
  getReportGroupUrl,
  getSaveReportSettingsUrl,
  getSaveReportRoleSettingsUrl,
  getRolesUrl,
  getAutoReportListUrl,
  getAutoReportSaveUrl,
  getSearchParameterUrl,
  getPatchSearchParameterUrl,
  getIndividualSettingUrl,
  getIndividualSettingPatchUrl,
  getIndividualSettingSaveUrl,
  getExcludedIndividualSettingUrl,
  getSearchParameterSaveUrl,
  getCnTypeEngineUrl,
  getComplexityCodeUrl,
  getKaratageUrl,
  getAutoGeneratedReportListUrl,
  getDownloadReportUserUrl,
  getDownloadReportSystemUrl
} from '@poss-web/shared/util-api-service';
import { Injectable } from '@angular/core';
import { Observable} from 'rxjs';
import { map } from 'rxjs/operators';
import {
  GenerateReportRequest,
  ReportName,
  ReportReponse,
  LoadReportPayload,
  CheckBoxSelectedOption,
  SaveReportPayload,
  ReportField,
  responseTypeEnum,
  BinGroup,
  ReportGroupLov,
  ReportRoleSetting,
  SaveReportRolePayload,
  LoadAutoReportPayload,
  SaveAutoReportPayload,
  LoadSearchParameterPayload,
  SaveSearchParametersPayload,
  UpdateSearchParametersPayload,
  UpdateIndividualReportSetting,
  SaveIndividualReportSetting
} from '@poss-web/shared/models';
import {
  BinGroupDataAdaptor,
  ReportHelper
} from '@poss-web/shared/util-adaptors';

@Injectable()
export class ReportsService {
  constructor(
    private apiService: ApiService,
    private fileDownloadService: FileDownloadService
  ) {}

  generateReport = (
    reportId: string,
    request: GenerateReportRequest
  ): Observable<string> => {
    const url = getGenerateReportUrl(reportId);
    return this.apiService
      .post(url, request)
      .pipe(map((data: any) => data.reportReferenceId));
  };

  downloadReport = (
    reportID: string,
    selectedTab: number
  ): Observable<boolean> => {
    let url;
    if (selectedTab === 0) {
      url = getDownloadReportUserUrl(reportID);
    } else if (selectedTab === 1) {
      url = getDownloadReportSystemUrl(reportID);
    }

    this.apiService.ResponseContentType = responseTypeEnum.BLOB;
    return this.apiService.get(url.path, url.params).pipe(
      map(data => {
        this.fileDownloadService.downloadReportFile(data, 'Report-' + reportID);
        return true;
      })
    );
  };

  getBinGroups(): Observable<BinGroup[]> {
    const url = getReportBinGroupsUrl();
    return this.apiService
      .get(url.path, url.params)
      .pipe(map((data: any) => BinGroupDataAdaptor.binGroupDataFromJson(data)));
  }

  loadReports = (request: LoadReportPayload): Observable<ReportReponse> => {
    let url;
    if (request.selectedTab === 0) {
      url = getReportListUrl(request);
    } else if (request.selectedTab === 1) {
      url = getAutoGeneratedReportListUrl(request);
    }

    const newRequest: {
      reportDescription?: string;
      reportGroup?: string;
      status?: string;
      referenceNumber?: string;
      fromDate: string;
      toDate: string;
    } = {
      fromDate: request.fromDate,
      toDate: request.toDate
    };
    if (!!request.reportDesc) {
      newRequest.reportDescription = request.reportDesc.replace(/_/g, ' ');
    }
    if (!!request.reportStatus) {
      newRequest.status = request.reportStatus;
    }
    if (!!request.reportGroup) {
      newRequest.reportGroup = request.reportGroup;
    }
    if (!!request.referenceNumber) {
      newRequest.referenceNumber = 'REF-' + request.referenceNumber;
    }

    return this.apiService
      .post(url.path, newRequest, url.params)
      .pipe(map((data: any) => ReportHelper.getReports(data)));
  };

  loadReportGroups = (): Observable<ReportGroupLov[]> => {
    const url = getReportGroupUrl();

    return this.apiService
      .get(url)
      .pipe(map((data: any) => ReportHelper.getReportGroups(data)));
  };

  loadReportNames = (type: string): Observable<ReportName[]> => {
    const url = getReportNamesUrl(type);

    return this.apiService
      .get(url.path, url.params)
      .pipe(map((data: any) => ReportHelper.getReportNames(data)));
  };

  loadReportRoles = (
    reportDes: string,
    roleCode: string
  ): Observable<ReportRoleSetting[]> => {
    const url = getReportRolesUrl(reportDes, roleCode);
    return this.apiService
      .get(url.path, url.params)
      .pipe(map((data: any) => ReportHelper.getReportRoles(data)));
  };

  loadReportFields = (reportId: string): Observable<ReportField[]> => {
    const url = getReportFieldsUrl(reportId);
    return this.apiService
      .get(url.path, url.params)

      .pipe(map((data: any) => ReportHelper.getReportFields(data)));
  };

  loadReportSettings = (
    reportId: string,
    roleCode: string
  ): Observable<CheckBoxSelectedOption[]> => {
    const url = getReportSettingsUrl(reportId, roleCode);
    return this.apiService
      .get(url.path, url.params)
      .pipe(map((data: any) => ReportHelper.getReportSettings(data)));
  };

  saveReportRoleSetting(roleCode: string, request: SaveReportRolePayload) {
    const url = getSaveReportRoleSettingsUrl(roleCode);
    return this.apiService.patch(url, request);
  }
  saveReportSettings = (
    reportId: string,
    request: SaveReportPayload
  ): Observable<any> => {
    const url = getSaveReportSettingsUrl(reportId);
    return this.apiService.patch(url, request);
  };

  getAutoReportList(loadAutoReportPayload: LoadAutoReportPayload) {
    const url = getAutoReportListUrl(
      loadAutoReportPayload.pageIndex,
      loadAutoReportPayload.pageSize,
      loadAutoReportPayload.reportDesc
    );
    return this.apiService
      .get(url.path, url.params)
      .pipe(map((data: any) => ReportHelper.getAutoReportList(data)));
  }
  saveAutoReportSettings(saveAutoReportPayload: SaveAutoReportPayload) {
    const url = getAutoReportSaveUrl();
    return this.apiService.patch(url, saveAutoReportPayload);
  }
  getRoles() {
    const url = getRolesUrl();
    return this.apiService.get(url).pipe(map((data: any) => data.results));
  }
  getSearchParameter(loadSearchParameterPayload: LoadSearchParameterPayload) {
    const url = getSearchParameterUrl(
      loadSearchParameterPayload.reportMasterId,
      loadSearchParameterPayload.employeeCode
    );

    return this.apiService
      .get(url.path, url.params)
      .pipe(
        map((data: any) => ReportHelper.getSearchParameter(data.results[0]))
      );
  }
  saveSearchParameter(
    saveSearchParametersPayload: SaveSearchParametersPayload
  ) {
    const url = getSearchParameterSaveUrl(
      saveSearchParametersPayload.reportMasterId
    );
    return this.apiService
      .post(url, saveSearchParametersPayload.data)
      .pipe(map((data: any) => ReportHelper.getSearchParameter(data)));
  }

  updateSearchParameter(
    updateSearchParametersPayload: UpdateSearchParametersPayload
  ) {
    const url = getPatchSearchParameterUrl(
      updateSearchParametersPayload.reportMasterId,
      updateSearchParametersPayload.queryId
    );
    return this.apiService
      .patch(url, updateSearchParametersPayload.data)
      .pipe(map((data: any) => ReportHelper.getSearchParameter(data)));
  }

  loadIndividualSetting(reportMasterId) {
    const url = getIndividualSettingUrl(reportMasterId);
    return this.apiService
      .get(url.path, url.params)
      .pipe(map((data: any) => ReportHelper.getReportFields(data)));
  }

  loadExcludedIndividualSetting(reportMasterId, employeeCode) {
    const url = getExcludedIndividualSettingUrl(reportMasterId, employeeCode);
    return this.apiService
      .get(url.path, url.params)
      .pipe(map((data: any) => ReportHelper.getExcludedReportSettings(data)));
  }
  saveIndividualSetting(
    saveIndividualReportSetting: SaveIndividualReportSetting
  ) {
    const url = getIndividualSettingSaveUrl(
      saveIndividualReportSetting.reportMasterId
    );
    return this.apiService.post(url, saveIndividualReportSetting.data);
  }

  updateIndividualSetting(
    updateIndividualReportSetting: UpdateIndividualReportSetting
  ) {
    const url = getIndividualSettingPatchUrl(
      updateIndividualReportSetting.reportMasterId,
      updateIndividualReportSetting.templateId
    );
    return this.apiService.patch(url, updateIndividualReportSetting.data);
  }

  loadCnType() {
    const url = getCnTypeEngineUrl();
    return this.apiService.get(url);
  }
  getComplexity() {
    const url = getComplexityCodeUrl();
    return this.apiService
      .get(url.path, url.params)
      .pipe(map((data: any) => ReportHelper.getComplexityCodeData(data)));
  }
  getKaratage() {
    const url = getKaratageUrl();
    return this.apiService
      .get(url.path, url.params)
      .pipe(map((data: any) => ReportHelper.getKaratageData(data)));
  }
}
