/*  
 * Copyright 2019. Titan Company Limited
 * All rights reserved.
 */

package com.titan.poss.core.enums;

/**
 * 
 * @author Mindtree Ltd.
 * @version 1.0
 */

public enum SchedulerCodeEnum {

	FILE_MASTER_JOB, FILE_NETCARROTS_JOB, FILE_STN_JOB, FILE_INVOICE_JOB, FILE_BOUTIQUE_REVENUE_JOB, FILE_TEP_AP_JOB,
	FILE_BOUTIQUE_SALES_JOB, FILE_DEBIT_NOTE_JOB, FILE_DEBIT_NOTE_L3_JOB, FILE_GIFT_MASTER_JOB, FILE_GV_REDEMPTION_JOB,
	FILE_RETURN_INVOICE_JOB, FILE_IBT_STN_JOB, FILE_STOCK_INTERFACE_JOB, INVENTORY_IBT_CLOSE, INVENTORY_DATA_SYNC,
	USER_RESET_PASSWORD, USER_DEACTIVATE_PASSWORD, USER_DEACTIVATE_LOGIN, USER_ASSIGN_MOBILE, USER_REMOVE_TEMP_ROLES,
	USER_DATA_SYNC, CONFIG_DATA_SYNC, SALES_REMOVE_FROM_RESERVEBIN, SALES_DATA_SYNC, SALES_AB_SUSPEND,
	SALES_AB_APPROVAL, SALES_RO_AIRPAY_PAYMENTS_DELETE, SALES_OPEN_TASK_DELETE, SALES_HOLD_TRANSACTIONS_DELETE,
	DATASYNC_PUBLISH_FAILED, DATAYSNC_RETRY_FAILED, DATASYNC_HEARTBEAT_CHECK, DATASYNC_PUBLISH_RETRY,
	LOCATION_DATA_SYNC, LOCATION_METAL_RATE_UPDATE, REPORT_GENERATE_JOB, SALES_CREDIT_NOTE_SUSPEND, PAYMENT_DATA_SYNC,
	PRODUCT_DATA_SYNC, STORES_DATA_SYNC, SALES_PENDING_BILL_CANCEL_DELETE, FILE_GENERAL_LEDGER_JOB,
	INTEGRATION_EVENT_RETRY_PUBLISH_JOB, WORKFLOW_EXPIRE_PENDING_REQUESTS_JOB, SALES_FILE_SYNC_ONLINE,
	INTEGRATION_CLEAR_SCHEDULER_AUDIT, FILE_CLEAR_FILE_AUDIT, LOCATION_FISCAL_YEAR_UPDATE, FILE_TEP_TRANSACTION_JOB,
	FILE_STUDDED_SPLIT_JOB, FILE_RETRY_STUDDED_SPLIT_JOB, CUSTOMER_DIGITAL_SIGNATURE_DELETION,
	GENERATE_INVOICE_DOCUMENTS, SALES_AB_CO_PAYMENT_CLEAR,SALES_CLEAR_FROZEN_CREDIT_NOTE,EA_STN_CONFIRM,
	COPY_DB_BACKUP
}
