package com.titan.poss.core.enums;

/**
 * @author Mindtree Ltd.
 * @version 1.0
 */
public enum WorkflowTypeEnum {

	BIN_CODE_CREATION, OTHER_ISSUES, CONVERSION, IBT_CANCELLATION, MANUAL_BILL, ADVANCE_BOOKING_MANUAL_BILL,
	CANCEL_ADVANCE_BOOKING, ACTIVATE_ADVANCE_BOOKING, CREDIT_NOTE_CANCELLATION, CREDIT_NOTE_GOLD_RATE_REMOVE,
	CREDIT_NOTE_TRANSFER, CREDIT_NOTE_ACTIVATE, INCREASE_IN_ROLES, APPROVE_RO_PAYMENT, BILL_CANCELLATION,
	UPLOAD_DOCUMENTS, IBT_TRANSFERS, GRN_OTHER_REASONS, GRN_MANUFACTURING_DEFECT, DISCOUNT_CREATION,
	DISCOUNT_MASTER_CREATION, GOODS_RETURN, TEP_APPROVAL_WORKFLOW, FULL_VALUE_TEP, MANUAL_FULL_VALUE_TEP, MANUAL_TEP,
	CUSTOMER_UPLOAD_DOCUMENT, MANUAL_BILL_GRF,TEP_EXCEPTION_APPROVAL_WORKFLOW,ACTIVATE_CUSTOMER_ORDER;

}
