/*
 * Copyright 2019. Titan Company Limited
 * All rights reserved.
 */

package com.titan.poss.report.dto.response;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 *
 * @author Mindtree Ltd.
 * @version 1.0
 */
@Data
@EqualsAndHashCode(callSuper = false)
@NoArgsConstructor
public class AutoReportDto {

    private String id;

    private String reportId;

    private String reportDescription;

    private String frequency;

    private String cronExpression;

    private Boolean isAutoGenerated;

    public AutoReportDto(String id, String reportId, String reportDescription, String frequency, String cronExpression) {
        this.id = id;
        this.reportId = reportId;
        this.reportDescription = reportDescription;
        this.frequency = frequency;
        this.cronExpression = cronExpression;
        this.isAutoGenerated = id == null ? Boolean.FALSE : Boolean.TRUE;
    }





}
