import { LoadReportPayload } from '@poss-web/shared/models';
import { HttpParams } from '@angular/common/http';

export const reportBaseUrl = (): string => {
  return '/report/v2/';
};

export const getReportNamesUrl = (
  reportGroup
): {
  path: string;
  params: HttpParams;
} => {
  let params = new HttpParams()
    .set('isPageable', '' + false)
  if (reportGroup)
    params = params.set('reportGroup', reportGroup);
  return { path: reportBaseUrl() + `reports`, params };
};

export const getReportGroupUrl = (): string => {
  return '/report/v2/lovs/REPORT_GROUP';
};

export const getReportPostLOVTypeUrl = (): string => {
  return '/report/v2/lovs/';
};

export const getReportLOVTypeUrl = (lovType: string): string => {
  return '/report/v2/lovs/' + lovType;
};
export const getGenerateReportUrl = (reportId: string): string => {
  return reportBaseUrl() + `generate-reports/${reportId}`;
};

export const getReportListUrl = (
  request: LoadReportPayload
): {
  path: string;
  params: HttpParams;
} => {
  let params = new HttpParams()
    .set('page', '' + request.pageIndex)
    .set('size', '' + request.pageSize);
  params = params.set('sort', 'id,DESC');

  return { path: reportBaseUrl() + `list-reports/user`, params };
};

export const getAutoGeneratedReportListUrl = (
  request: LoadReportPayload
): {
  path: string;
  params: HttpParams;
} => {
  let params = new HttpParams()
    .set('page', '' + request.pageIndex)
    .set('size', '' + request.pageSize);
  params = params.set('sort', 'id,DESC');

  return { path: reportBaseUrl() + `list-reports/system`, params };
};

export const getDownloadReportUserUrl = (
  reportID: string
): { path: string; params: HttpParams } => {
  const params = new HttpParams().set('reportType', 'user');
  return {
    path: reportBaseUrl() + `download-reports/REP-${reportID}`,
    params: params
  };
};

export const getDownloadReportSystemUrl = (
  reportID: string
): { path: string; params: HttpParams } => {
  const params = new HttpParams().set('reportType', 'System');
  return {
    path: reportBaseUrl() + `download-reports/REP-${reportID}`,
    params: params
  };
};

export const getReportFieldsUrl = (
  reportID: string
): {
  path: string;
  params: HttpParams;
} => {
  const params = new HttpParams().set('isPageable', '' + false);

  return { path: reportBaseUrl() + `reports/${reportID}/fields`, params };
};

export const getAutoReportListUrl = (
  pageIndex: number,
  pageSize: number,
  reportDescription: string
): {
  path: string;
  params: HttpParams;
} => {
  let params = new HttpParams()
    .set('isPageable', '' + true)
    .set('page', '' + pageIndex)
    .set('size', '' + pageSize);
  if (reportDescription !== null && reportDescription !== undefined) {
    params = new HttpParams()
      .set('isPageable', '' + false)

      .set('reportDescription', reportDescription);
  }
  return { path: reportBaseUrl() + `reports/scheduler`, params };
};

export const getAutoReportSaveUrl = (): string => {
  return reportBaseUrl() + `reports/scheduler`;
};

export const getReportRolesUrl = (
  reportDes: string,
  roleCode: string
): {
  path: string;
  params: HttpParams;
} => {
  let params = new HttpParams().set('isPageable', '' + false);
  if (reportDes !== null && reportDes !== undefined) {
    params = new HttpParams()
      .set('isPageable', '' + false)
      .set('reportDescription', reportDes);
  }

  if (roleCode !== null && roleCode !== undefined) {
    params = new HttpParams()
      .set('isPageable', '' + false)
      .set('roleCode', roleCode);
  }
  return { path: reportBaseUrl() + `reports/roles`, params };
};

export const getReportSettingsUrl = (
  reportID: string,
  roleCode: string
): { path: string; params: HttpParams } => {
  const params = new HttpParams()
    .set('isPageable', '' + false)
    .set('roleCode', roleCode);

  return {
    path: reportBaseUrl() + `reports/${reportID}/fields/roles`,

    params: params
  };
};

export const getSaveReportSettingsUrl = (reportID: string): string => {
  return reportBaseUrl() + `reports/${reportID}/fields/roles`;
};

export const getRolesUrl = (): string => {
  return '/engine/v2/users/roles';
};

export const getSaveReportRoleSettingsUrl = (roleCode: string): string => {
  return reportBaseUrl() + `reports/${roleCode}/roles`;
};

export const getReportBinGroupsUrl = (): {
  path: string;
  params: HttpParams;
} => {
  const path = '/inventory/v2/lite-data/bingroups';
  const params = new HttpParams()
    .set('isPageable', '' + false)
    .set('sort', 'description,ASC');

  return {
    path,
    params
  };
};

export const getSearchParameterSaveUrl = (reportID): string => {
  return reportBaseUrl() + `reports/${reportID}/saved-queries`;
};

export const getSearchParameterUrl = (
  reportID,
  employeeCode
): {
  path: string;
  params: HttpParams;
} => {
  const path = reportBaseUrl() + `reports/${reportID}/saved-queries`;
  const params = new HttpParams().set('employeeCode', '' + employeeCode);

  return {
    path,
    params
  };
};

export const getPatchSearchParameterUrl = (reportID, queryId): string => {
  return reportBaseUrl() + `reports/${reportID}/saved-queries/${queryId}`;
};

export const getIndividualSettingUrl = (
  reportID
): {
  path: string;
  params: HttpParams;
} => {
  const path = reportBaseUrl() + `reports/optional/${reportID}/fields`;
  const params = new HttpParams().set('isPageable', '' + false);

  return {
    path,
    params
  };
};
export const getIndividualSettingSaveUrl = (reportID): string => {
  return reportBaseUrl() + `reports/${reportID}/templates`;
};

export const getExcludedIndividualSettingUrl = (
  reportID,
  employeeCode
): {
  path: string;
  params: HttpParams;
} => {
  const path = reportBaseUrl() + `reports/${reportID}/templates`;
  const params = new HttpParams().set('employeeCode', '' + employeeCode);

  return {
    path,
    params
  };
};
export const getIndividualSettingPatchUrl = (reportID, templateId): string => {
  return reportBaseUrl() + `reports/${reportID}/templates/${templateId}`;
};
export const getCnTypeEngineUrl = (): string => {
  return '/engine/v2/payments/credit-note-types;';
};

export const getComplexityCodeUrl = (): {
  path: string;
  params: HttpParams;
} => {
  const path = '/engine/v2/products/complexities';
  const params = new HttpParams()
    .set('size', '' + 100000)
    .set('isActive', '' + true);
  return { path, params };
};

export const getKaratageUrl = (): { path: string; params: HttpParams } => {
  const path = '/engine/v2/products/purities';
  const params = new HttpParams()
    .set('isActive', '' + true)
    .set('size', '' + 10000);

  return { path, params };
};
