export enum LocationSettingAttributesEnum {
  // FACTORY_LOCATION_CODE = 'factory_locationCode',
  FACTORY_BRAND_CODE = 'factory_brandCode',
  FACTORY_TOWN_ID = 'factory_townId',
  FACTORY_TOWN_NAME = 'factory_townName',
  FACTORY_STATE_ID = 'factory_stateId',
  FACTORY_STATE_NAME = 'factory_stateName',
  FACTORY_REGION_CODE = 'factory_regionCode',
  FACTORY_LOCATION_TYPE_CODE = 'factory_locationTypeCode',
  FACTORY_LOCATION_FORMAT = 'factory_locationFormat',
  FACTORY_IS_ACTIVE = 'factory_isActive',
  FACTORY_DESCRIPTION = 'factory_description',
  FACTORY_MARKET_CODE = 'factory_marketCode',
  FACTORY_COUNTRY_CODE = 'factory_countryCode',
  FACTORY_OWNER_TYPE_CODE = 'factory_ownerTypeCode',
  FACTORY_CODE_VALUE = 'factory_factoryCodeValue',
  FACTORY_CFA_CODE_VALUE = 'factory_cfaCodeValue',
  FACTORY_SUB_REGION_CODE = 'factory_subRegionCode',
  FACTORY_SUB_BRAND_CODE = 'factory_subBrandCode',
  FACTORY_REMARKS = 'factory_remarks',
  FACTORY_BASE_CURRENCY = 'factory_baseCurrency',
  FACTORY_STOCK_CURRENCY = 'factory_stockCurrency',
  FACTORY_MASTER_CURRENCY = 'factory_masterCurrency',
  FACTORY_PAYMENT_CURRENCIES = 'factory_paymentCurrencies',

  // CFA_LOCATION_CODE = 'cfa_locationCode',
  CFA_BRAND_CODE = 'cfa_brandCode',
  CFA_TOWN_ID = 'cfa_townId',
  CFA_TOWN_NAME = 'cfa_townName',
  CFA_STATE_ID = 'cfa_stateId',
  CFA_STATE_NAME = 'cfa_stateName',
  CFA_REGION_CODE = 'cfa_regionCode',
  CFA_LOCATION_TYPE_CODE = 'cfa_locationTypeCode',
  CFA_LOCATION_FORMAT = 'cfa_locationFormat',
  CFA_IS_ACTIVE = 'cfa_isActive',
  CFA_DESCRIPTION = 'cfa_description',
  CFA_MARKET_CODE = 'cfa_marketCode',
  CFA_COUNTRY_CODE = 'cfa_countryCode',
  CFA_OWNER_TYPE_CODE = 'cfa_ownerTypeCode',
  CFA_FACTORY_CODE_VALUE = 'cfa_factoryCodeValue',
  CFA_CODE_VALUE = 'cfa_cfaCodeValue',
  CFA_SUB_REGION_CODE = 'cfa_subRegionCode',
  CFA_SUB_BRAND_CODE = 'cfa_subBrandCode',
  CFA_REMARKS = 'cfa_remarks',
  CFA_BASE_CURRENCY = 'cfa_baseCurrency',
  CFA_STOCK_CURRENCY = 'cfa_stockCurrency',
  CFA_MASTER_CURRENCY = 'cfa_masterCurrency',
  CFA_PAYMENT_CURRENCIES = 'cfa_paymentCurrencies',

  COUNTRY_CODE = 'country_countryCode',
  COUNTRY_DESCRIPTION = 'country_description',
  COUNTRY_IS_ACTIVE = 'country_isActive',
  // COUNTRY_CURRENCY_CODE = 'country_currencyCode',
  COUNTRY_DATE_FORMAT = 'country_dateFormat',
  COUNTRY_LOCALE = 'country_locale',
  COUNTRY_PHONE_LENGTH = 'country_phoneLength',
  COUNTRY_FISCAL_YEAR = 'country_fiscalYear',
  COUNTRY_TIME_FORMAT = 'country_timeFormat',
  COUNTRY_ISD_CODE = 'country_isdCode',
  COUNTRY_FISCAL_YEAR_START = 'country_fiscalYearStart',
  COUNTRY_LAST_MODIFIED_DATE = 'country_lastModifiedDate',
  COUNTRY_WEIGHT_UNIT = 'country_weightUnit',
  COUNTRY_STONE_WEIGHT_UNIT = 'country_stoneWeightUnit',

  BASECURRENCY_CURRENCY_CODE = 'baseCurrency_currencyCode',
  BASECURRENCY_CURRENCY_SYMBOL = 'baseCurrency_currencySymbol',
  BASECURRENCY_CURRENCY_DESCRIPTION = 'baseCurrency_description',
  BASECURRENCY_UNICODE = 'baseCurrency_unicode',
  BASECURRENCY_ISACTIVE = 'baseCurrency_isActive',
  BASECURRENCY_LAST_MODIFIED_DATE = 'baseCurrency_lastModifiedDate',

  STORE_COMPANY_NAME = 'store_companyName',
  STORE_ADDRESS_LINES = 'store_addressLines',
  STORE_PHONE_NUMBER1 = 'store_phoneNumber1',
  STORE_PHONE_NUMBER2 = 'store_phoneNumber2',
  STORE_CONTACT_NUMBER = 'store_contactNumber',
  STORE_CORPORATE_ADDRESS = 'store_corporateAddress',
  STORE_CIN_NUMBER = 'store_cinNumber',
  STORE_IS_WALKIN_DETAILS_MANDATORY = 'store_isWalkInsDetailsMandatory',
  STORE_PINCODE = 'store_pincode',
  STORE_BOUTIQUE_EMAIL_ID = 'store_boutiqueEmailId',
  STORE_NO_OF_DAYS = 'store_noOfDays',
  STORE_NUMBER_OF_DAYS_TO_DISPLAY = 'store_numberOfDaysToDisplay',
  STORE_REGD_OFFICE = 'store_regdOffice',
  STORE_MAX_RETRY_ATTEMPTS_FOR_METAL = 'store_maxRateRetryAttempt',
  STORE_IS_DIAL = 'store_isDial',

  PRINT_FREE_TEXT_FOR_GRAMS = 'print_freeTextForGrams',
  PRINT_NO_OF_INVOICE_COPIES_FOR_REGULAR_QUICK_CM = 'print_noOfInvoicecopiesforRegularOrQuickCM',
  PRINT_INVOICE_TYPE = 'print_invoiceType',
  PRINT_MC_WASTAGE_EXPENSE = 'print_mcOrWastageExpense',
  PRINT_WASTAGE_COMPONENT = 'print_printWastageComponent',
  PRINT_WASTAGE_PERCENT = 'print_printWastagePercent',
  PRINT_WASTAGE_CHARGE = 'print_printWastageCharge',
  PRINT_STONE_VALUE = 'print_printStoneValue',
  PRINT_GOLD_VALUE = 'print_printGoldValue',
  PRINT_PRICE = 'print_printPrice',
  PRINT_IS_MC_WASTAGE = 'print_isMCAndWastage',
  PRINT_IS_DISPLAY_WASTAGE_PERCENT = 'print_isDisplayWastagePercent',
  PRINT_IS_VARIABLE_PRICE = 'print_isVariablePrice',
  PRINT_MAKING_CHARGES = 'print_printMakingCharges',
  PRINT_CUSTOMER_NUMBER_IN_REPORT = 'print_printCustomerNumberinReport',
  PRINT_CASH_MEMO = 'print_printCashMemo',
  PRINT_GUARANTEE_CARD = 'print_printGuaranteeCard',
  PRINT_OTHER_STONE_WITH_GUARANTEE_CARD = 'print_printOtherStoneWtinGuaranteeCard',
  PRINT_OTHER_STONE_WEIGHT_IN_ANNEXURE = 'print_printOtherStoneWeightinAnnexure',
  PRINT_IMAGE = 'print_printImage',

  CN_SUSPENDING_CN = 'cn_suspendingCNs',
  CN_TRANSFERRED_CN = 'cn_transferredCNs',
  CN_ACTIVATED_CN = 'cn_activatedCNs',
  CN_MAX_NO_OF_CN = 'cn_maxNoOfCN',
  CN_OTP_FOR_MIN_CN = 'cn_otpForMinCN',
  CN_MAX_NP_OF_TIMES_CN_IN_EGHS = 'cn_maxNoOfTimesCNinEGHS',
  CN_IS_EMPLOYEE_LOAN_CN_CANCEL = 'cn_isEmployeeLoanCNCancel',
  CN_IS_EMPLOYEE_LOAN_CN_TRANSFER = 'cn_isEmployeeLoanCNTransfer',
  CN_ISUPLOAD_MANDATORY_FOR_THIRDPARTY_CN_WITHOUT_OTP = 'cn_isUploadMandatoryforThirdPartyCNWithoutOTP',

  TAX_IS_GST = 'tax_isGST',
  TAX_GST_REGISTERATION_NO = 'tax_gstRegisterationNo',
  TAX_VALID_FROM = 'tax_gstValidFrom',
  TAX_PRINT_VALID_FROM = 'tax_gstPrintValidFrom',

  CM_IS_BILL_CANCEL_APPROVAL_REQUIRED = 'cm_isBillCancelApprovalRequired',
  CM_MAX_HOURS_FOR_BILL_CANCEL = 'cm_maxNoOfHoursForBillCancel',
  CM_IS_TITLE = 'cm_isTitle',
  CM_IS_MOBILE_AND_EMAIL_MANDATORY_FOR_CORRECTION = 'cm_isMobileAndEmailMandatoryForCorrection',
  CM_IS_EDIT_WEIGHT_ALLOWED = 'cm_isEditWeightAllowed',
  CM_IS_MOBILE_AND_EMAIL = 'cm_isMobileAndEmail',
  CM_HOLD_TIME_IN_MINUTES = 'cm_cmHoldTimeInMinutes',
  CM_NO_OF_HOURS_FOR_OPENTASK_DELETION_IN_CM = 'cm_noOfHoursForOpenTaskDeletionCM',

  GRN_NO_OF_DAYS_GRN_ALLOWED = 'grn_noOfDaysGRNAllowed',
  GRN_MAX_NO_OF_DAYS_FOR_APPROVED_GRN = 'grn_maximumNoOfDaysForApprovedGRN',
  GRN_NO_OF_DAYS_TO_PROTECT_GOLDRATE_FOR_GRN = 'grn_noOfDaysToProtectGoldRateForGRN',
  GRN_MIN_UTILIZATION_PERCENT_FOR_GRN = 'grn_minUtilizationPercentForGRN',
  GRN_IS_INTERBOUTIQUE_GRN_ALLOWED = 'grn_isInterBoutiqueGRNAllowed',
  GRN_IS_GRN_ALLOWED_IN_CM = 'grn_isGRNAllowedInCM',
  GRN_IS_GRN_ALLOWED_IN_AB = 'grn_isGrnAllowedInAdvanceBooking',

  GRF_MINIMUM_UTILIZATION = 'grf_minimumUtilization',
  GRF_IS_GRF_ALLOWED = 'grf_isGRFAllowed',
  GRF_IS_GRF_ALLOWED_IN_CM = 'grf_isGRFAllowedInCM',
  GRF_IS_GRF_ALLOWED_IN_AB = 'grf_isGRFAllowedInAdvanceBooking',
  GRF_IS_GRF_ALLOWED_IN_CUSTOMER_ORDER = 'grf_isGRFAllowedInCustomerOrder',
  GRF_IS_MERGE_CN_ALLOWED = 'grf_isMergeCNAllowed',
  GRF_CURRENT_OWNER = 'grf_currentOwner',
  GRF_THIRD_PERSON = 'grf_thirdPerson',

  GEP_ENABLE_GEP_SALE = 'gep_enableGEPSale',
  GEP_PURE_GOLD_PURITY = 'gep_gepPureGoldPurity',
  GEP_PURE_PLATINUM_PURITY = 'gep_gepPurePlatinumPurity',
  GEP_PURE_SILVER_PURITY = 'gep_gepPureSilverPurity',
  GEP_STANDARD_DEDUCTION_GOLD = 'gep_gepStandardDeductionGold',
  GEP_STANDARD_DEDUCTION_PLATINUM = 'gep_gepStandardDeductionPlatinum',
  GEP_STANDARD_DEDUCTION_SILVER = 'gep_gepStandardDeductionSilver',
  GEP_NO_OF_DAYS_GEP_CANCEL = 'gep_noOfDaysGepCancel',
  GEP_KARAT_ACCEPTED_FOR_GEP = 'gep_karatAcceptedForGEP',
  GEP_IS_PRE_MELTING_DETAILS_MANDATORY = 'gep_isPreMeltingDetailsMandatory',
  GEP_HOLD_TIME = 'gep_gepHoldTime',

  GC_MAXIMUM_AMOUNT = 'gc_maximumAmount',
  GC_MINIMUM_AMOUNT = 'gc_minimumAmount',
  GC_MULTIPLES_VALUE = 'gc_multiplesValue',
  GC_IS_CARD_CANCELLATION_ALLOWED = 'gc_isCardCancellationAllowed',
  GC_IS_CARD_INWARDING_ALLOWED = 'gc_isCardInwardingAllowed',
  GC_IS_CARD_ACTIVATION_ALLOWED = 'gc_isCardActivationAllowed',

  AB_CANCELLATION_ALLOWED_FOR_AB = 'ab_cancellationAllowedforAdvanceBooking',
  AB_ACTIVATE_ALLOWED_FOR_AB = 'ab_activateAllowedforAdvanceBooking',
  AB_REQUEST_APPROVAL_FOR_NON_FROZEN_ORDER_CANCEL = 'ab_requestApprovalForNonFrozenOrderCancel',
  AB_VALIDITY_DAYS_FOR_AUTOCLOSURE_IN_AB = 'ab_validityDaysforAutoClosureInAdvanceBooking',
  AB_VALIDATE_DAYS_FOR_ACTIVATE_IN_AB = 'ab_validityDaysforActivateInAdvanceBooking',
  AB_VALIDITY_DAYS_FOR_RELEASE_INV_IN_AB = 'ab_validityDaysforReleaseInvInAdvancebooking',
  AB_MIN_PERCENT_TOBE_PAID_FOR_FROZEN_ORDER = 'ab_minPercentToBePaidForFrozenOrder',
  AB_MIN_PERCENT_TOBE_PAID_FOR_NONFROZEN_ORDER = 'ab_minPercentToBePaidForNonFrozenOrder',
  AB_HOLD_TIME = 'ab_abHoldTime',
  CO_HOLD_TIME = 'co_coHoldTime',
  AB_NO_OF_HOURS_FOR_OPEN_TASK_DELETION = 'ab_noOfHoursForOpenTaskDeletion',

  CO_CANCELLATION_ALLOWED_FOR_CUSTOMER_ORDER = 'co_cancellationAllowedforCustomerOrder',
  CO_ACTIVATE_ALLOWED_FOR_CUSTOMER_ORDER = 'co_activateAllowedforCustomerOrder',
  CO_VALIDITY_DAYS_FOR_AUTO_CLOSURE_IN_CUSTOMER_ORDER = 'co_validityDaysforAutoClosureInCustomerOrder',
  CO_VALIDITY_DAYS_FOR_RELEASE_INV_IN_CUSTOMER_ORDER = 'co_validitydaysforReleaseInvInCustomerOrder',
  CO_MAX_NO_OF_DAYS_FOR_PO_LIKELY_DATE = 'co_maxNoofdaysforPOLikelyDate',

  GHS_GRAMMAGE_CN_TRANSFER = 'ghs_grammageCNTransfer',
  GHS_IS_CONSENT_LETTER_UPLOAD_MANDATORY = 'ghs_isConsentLetterUploadMandatory',
  GHS_IS_CLUBBING_GHS_ACC_RESTRICTED = 'ghs_isClubbingGHSAccRestricted',
  GHS_IS_EGHS_MANDATORY = 'ghs_isEghsMandatory',
  GHS_IS_OTP_REQUIRED = 'ghs_isOtpRequired',
  GHS_NO_OF_DAYS_FOR_SUSPENDING_GHS = 'ghs_noOfDaysForSuspendingGhs',
  GHS_CONSOLIDATE_ATTEMPTS = 'ghs_consolidateAttempts',
  GHS_GRACE_PERIOD_FOR_SUSPENDED_GHS = 'ghs_gracePeriodAfterSuspenededGhs',
  GHS_IS_GHS_REDEMPTION_ALLOWED = 'ghs_isGHSRedemptionAllowed',
  GHS_ISUPLOAD_MANDATORY_FOR_GHS_WITHOUT_OTP = 'ghs_isUploadMandatoryforGHSWithoutOTP',

  INV_IS_ISSUE_TO_FACTORY = 'inv_isIssueToFactory',
  INV_IS_ISSUE_TO_MERCHANDISE = 'inv_isIssueToMerchandise',
  INV_IS_ISSUE_TO_OTHER_BOUTIQUE = 'inv_isIssueToOtherBoutique',
  INV_IS_ISSUE_TO_TEP = 'inv_isIssueToTEP',
  INV_IS_ISSUE_TO_GEP = 'inv_isIssueToGEP',
  INV_IS_ISSUE_DEFECTIVE = 'inv_isIssueDefective',
  INV_IS_ISSUE_OTHERS = 'inv_isIssueOthers',
  INV_MAX_NO_OF_DAYS_FOR_PHYSICAL_RECEIPT_DATE = 'inv_maximumNoOfDaysForPhysicalReceiptDate',
  INV_MAX_NO_OF_DAYS_FOR_STN_CANCELLATION = 'inv_maximumNoOfDaysForSTNCancellation',
  INV_IS_CONVERSION_RESTRICTED = 'inv_isConversionRestricted',
  INV_IS_STN_CANCELLATION_ALLOWED = 'inv_isSTNcancellationAllowed',
  INV_IS_STUDDED_SPLIT_ALLOWED = 'inv_isStuddedSplitAllowed',
  INV_SPARE_WT_TOLERANCE_FOR_STOCK_ITEM = 'inv_sparewtToleranceforStockItem',
  INV_SERVICE_WT_TOLERANCE_FOR_STOCK_ITEM = 'inv_servicewtToleranceforStockItem',
  INV_CONVERSION_WT_TOLERANCE_FOR_BANGLE = 'inv_conversionwtToleranceforBangle',

  BANKING_IS_BANKING_MANDATORY = 'banking_isBankingMandatory',
  BANKING_IS_PASSWORD_MANDATORY = 'banking_isPasswordMandatory',
  BANKING_ENABLE_CASH_DEPOSIT = 'banking_enableCashDeposit',
  BANKING_ENABLE_CHEQUE_DEPOSIT = 'banking_enableChequeDeposit',
  BANKING_REMARKS_FOR_PASSWORD = 'banking_remarksForPassword',
  BANKING_SAP_CODE = 'banking_sapCode',
  BANKING_PAYMENT_MODE = 'banking_paymentMode',

  OTP_IS_OTP_ALLOWED_ASSM = 'otp_isOTPallowedASSM',
  OTP_IS_OTP_ALLOWED_CM = 'otp_isOTPallowedCM',
  OTP_IS_OTP_ALLOWED_ADVANCE = 'otp_isOTPallowedAdvance',
  OTP_IS_OTP_ALLOWED_AB = 'otp_isOTPallowedAB',
  OTP_IS_OTP_ALLOWED_GHS = 'otp_isOTPallowedGHS',
  OTP_IS_OTP_ALLOWED_CO = 'otp_isOTPallowedCO',
  OTP_IS_OTP_REQUIRED_FOR_GC = 'otp_isOTPrequiredforGC',
  OTP_IS_OTP_REQUIRED_FOR_GHS_REDEMPTION = 'otp_isOTPrequiredforGHSRedemption',
  OTP_HELP_DESK_EMAIL_ID = 'otp_otpHelpDeskEmailId',

  CUSTOMER_IS_UPLOAD_DOCUMENT_ALLOWED = 'customer_isUploadDocumentAllowed',
  CUSTOMER_IS_DOWNLOAD_DOCUMENT_ALLOWED = 'customer_isDownloadDocumentAllowed',
  CUSTOMER_IS_DOCUMENT_DISPLAY_FOR_CC = 'customer_isDocumentDisplayForCC',
  CUSTOMER_IS_EMAIL_FOR_ENCIRCLE_CUSTOMER = 'customer_isEmailForEncircleCustomer',
  CUSTOMER_IS_MOBILE_NO_FOR_ONE_TIME_CUSTOMER = 'customer_isMobileNoForOneTimeCustomer',
  CUSTOMER_IS_EMAIL_FOR_ONE_TIME_CUSTOMER = 'customer_isEmailForOneTimeCustomer',
  CUSTOMER_IS_MOBILE_NO_FOR_INSTITUTIONAL_CUSTOMER = 'customer_isMobileNoForInstitutionalCustomer',
  CUSTOMER_IS_EMAIL_FOR_INSTITUTIONAL_CUSTOMER = 'customer_isEmailForInstitutionalCustomer',
  CUSTOMER_IS_MOBILE_NO_FOR_INTERNATIONAL_CUSTOMER = 'customer_isMobileNoForInternationalCustomer',
  CUSTOMER_IS_EMAIL_FOR_INTERNATIONAL_CUSTOMER = 'customer_isEmailForInternationalCustomer',

  DIGIGOLD_DIGIGOLD_DISCOUNT_PERCENTAGE = 'digigold_digiGoldDiscountPercent',
  DIGIGOLD_IS_CN_CANCEL_ALLOWED_FOR_DIGIGOLD = 'digigold_isCNCancelAllowedForDigiGold',
  DIGIGOLD_IS_CN_CANCEL_ALLOWED_FOR_NON_DIGIGOLD = 'digigold_isCNCancelAllowedForNonDigiGold',
  DIGIGOLD_IS_CN_PARTIAL_REDEMPTION_ALLOWED_FOR_DIGIGOLD = 'digigold_isCNPartialRedemptionAllowedForDigiGold',
  DIGIGOLD_IS_CN_TRANSFER_ALLOWED_FOR_DIGIGOLD = 'digigold_isCNTransferAllowedForDigiGold',
  DIGIGOLD_IS_CN_TRANSFER_ALLOWED_FOR_NON_DIGIGOLD = 'digigold_isCNTransferAllowedForNonDigiGold',

  PAYMENT_CHEQUE_VALIDITY_DAYS = 'payment_chequeValidityDays',
  PAYMENT_DD_VALIDITY_DAYS = 'payment_ddValidityDays',
  PAYMENT_REALISATION_DAYS = 'payment_realisationDays',
  PAYMENT_IS_ULP_ALLOWED = 'payment_isUlpAllowed',
  PAYMENT_ENABLE_CN_CANCELLATION_FOR_GV_PAYMENT = 'payment_enableCNCancellationForGVPayment',
  PAYMENT_ENABLE_CN_TRANSFER_FOR_GV_PAYMENT = 'payment_enableCNTarnsferForGVpayment',
  PAYMENT_IS_MULTIPLE_GV_ALLOWED = 'payment_isMultipleGVAllowed',
  PAYMENT_APPROVED_RO_REQUEST_DELETION = 'payment_approvedRORequestDeletion',
  PAYMENT_PENDING_RO_REQUEST_DELETION = 'payment_pendingRORequestDeletion',
  PAYMENT_RTGS_ENABLE_RTGS_PAYMENT = 'payment_enableRtgsPayment',
  PAYMENT_RTGS_IS_RR_NUMBER_VALIDATION = 'payment_isRRNumberValidation',
  // PAYMENT_RTGS_MAX_AMOUNT  = 'payment_maximumAmount',
  // PAYMENT_RTGS_MIN_AMOUNT  = 'payment_minimumAmount',
  PAYMENT_RTGS_NO_OF_DAYS_FOR_CHEQUE_OR_DD_ACCEPTANCE = 'payment_noOfDaysForChequeOrDDAcceptance',
  PAYMENT_RTGS_IS_RO_APPROVED_BY_WORKFLOW = 'payment_isROApprovedByWorkflow',
  PAYMENT_RTGS_IS_ENABLE_AIRPAY_FOR_INTEGRATION = 'payment_isEnableAirpayForIntegration',
  PAYMENT_RTGS_IS_ENABLE_UNIPAY_FOR_INTEGRATION = 'payment_isEnableUnipayForIntegration',
  PAYMENT_IS_ENABLED_RAZORPAY_FOR_INTEGRATION = 'payment_isEnableRazorpayForIntegration',

  OFFER_MAX_WEIGHT_FOR_FOC = 'offer_maxWeightforFOC',
  OFFER_MAX_VALUE_FOR_FOC = 'offer_maxValueforFOC',
  OFFER_BIN_TO_BIN_TRANSFER_ALLOWED_FOR_FOC_ITEMS = 'offer_bintobintransferallowedforFOCitems',
  OFFER_IS_TEP_SALEABLE_ITEMS_ALLOWED_FOR_FOC = 'offer_isTEPsaleableitemsallowedforFOC',
  OFFER_IS_TEP_ALLOWED_FOR_FOC_ITEMS = 'offer_isTEPallowedforFOCitems',
  OFFER_IS_FOC_ITEMS_SALEABLE = 'offer_isFOCitemssaleable',
  OFFER_IS_EMPLOYEE_DISCOUNT = 'offer_isEmployeeDiscount',

  GLOBAL_LOCATION_CODE = 'global_locationCode',
  GLOBAL_DESCRIPTION = 'global_description',
  GLOBAL_FAX = 'global_fax',
  GLOBAL_LOCATION_TYPE_CODE = 'global_locationTypeCode',
  GLOBAL_TOWN_ID = 'global_townId',
  GLOBAL_STATE_ID = 'global_stateId',
  GLOBAL_REGION_CODE = 'global_regionCode',
  GLOBAL_OWNER_TYPE_CODE = 'global_ownerTypeCode',
  GLOBAL_FACTORY_CODE_VALUE = 'global_factoryCodeValue',
  GLOBAL_LOCATION_FORMAT = 'global_locationFormat',
  GLOBAL_BRAND_CODE = 'global_brandCode',
  GLOBAL_IS_ACTIVE = 'global_isActive',
  GLOBAL_CFA_CODE_VALUE = 'global_cfaCodeValue',
  GLOBAL_STOCK_CURRENCY = 'global_stockCurrency',
  GLOBAL_MASTER_CURRENCY = 'global_masterCurrency',
  GLOBAL_PAYMENT_CURRENCY = 'global_paymentCurrencies',
  GLOBAL_MARKET_CODE = 'global_marketCode',
  GLOBAL_SUB_REGION_CODE = 'global_subRegionCode',
  GLOBAL_SUB_BRAND_CODE = 'global_subBrandCode',

  TEP_HOLD_TIME = 'tep_tepHoldTime',

  IS_ENCIRCLE_PAYMENT_ALLOWED = 'isEncirclePaymentAllowed',
  IS_PAN_CARD_VERIFY_INTEGRATION = 'isPanCardVerifyIntegration',

  SERVICE_IS_SERVICE_MANDATORY = 'service_isServiceMandatory',
}

export enum SubBrandTypeEnum {
  TANISHQ = 'TANISHQ',
  MIA = 'MIA',
  ZOYA = 'ZOYA'
}
