export interface LovMasterType {
  value: string;
  name: string;
}

export interface LovMasterTypeMain {
  value: string;
  name: string;
}

export interface LovMaster {
  lovType: string;
  lovName: string;
  description: string;
  isActive: boolean;
}

export enum LovMasterEnum {
  new = 'new',
  edit = 'edit',
  REASONTYPE = 'REASONTYPE',
  PRODUCTTYPE = 'PRODUCTTYPE',
  INDENTTYPE = 'INDENTTYPE',
  SUPPLYCHAIN = 'SUPPLYCHAIN',
  PRICINGGROUPTYPE = 'PRICINGGROUPTYPE',
  PRICINGTYPE = 'PRICINGTYPE',
  FINDING = 'FINDING',
  LOCATIONTYPE = 'LOCATIONTYPE',
  OWNERTYPE = 'OWNERTYPE',
  LOCATIONFORMAT = 'LOCATIONFORMAT',
  MATERIALPRICETYPE = 'MATERIALPRICETYPE',
  DEFECTTYPE = 'DEFECTTYPE',
  DEFECTCODE = 'DEFECTCODE',
  MATERIALTYPE = 'MATERIALTYPE',
  GEPITEMTYPE = 'GEPITEMTYPE',
  PLAINSTUDDEDTYPE = 'PLAINSTUDDEDTYPE',
  WEIGHT_EDIT_REASON_TYPE = 'WEIGHT_EDIT_REASON_TYPE',
  PRICETYPE = 'PRICETYPE',
  TAXSYSTEM = 'TAXSYSTEM',
  DATEFORMAT = 'DATEFORMAT',
  TIMEFORMAT = 'TIMEFORMAT',
  TAXTRANSACTIONTYPE = 'TAXTRANSACTIONTYPE',
  PRINT_DOC_TYPE = 'PRINT_DOC_TYPE',
  TEPPARTIALCNCANCELLATION = 'TEPPARTIALCNCANCELLATION',
  TRANSACTION_TYPE = 'TRANSACTION_TYPE',
  PAYMENT_GROUP = 'PAYMENT_GROUP',
  CUSTOMER_TYPE = 'CUSTOMER_TYPE',
  OCCASION_TYPE = 'OCCASION_TYPE',
  OTHER_CHARGES_REASONS = 'OTHER_CHARGES_REASONS',
  SALUTATION = 'SALUTATION',
  GIFT_CARD_TYPE = 'GIFT_CARD_TYPE',
  ID_PROOF = 'ID_PROOF',
  GRN_REASON_TYPE = 'GRN_REASON_TYPE',
  TATA_COMPANY = 'TATA_COMPANY',
  REFUND_PAYMENT_MODE = 'REFUND_PAYMENT_MODE',
  INVOICE_TYPE = 'INVOICE_TYPE',
  DISCOUNT_TYPE = 'DISCOUNT_TYPE',
  RANGE_TYPE = 'RANGE_TYPE',
  CLUBBING_DISCOUNT_TYPE = 'CLUBBING_DISCOUNT_TYPE',
  APPROVAL_ROLES = 'APPROVAL_ROLES',
  ROLE_TYPE = 'ROLE_TYPE',
  USER_TYPE = 'USER_TYPE',
  STOCK_ISSUE_REPORT_HEADER = 'STOCK_ISSUE_REPORT_HEADER',
  RIVAAH_CARD='RIVAAH_CARD',
  REASON_FOR_CANCELLATION ='REASON_FOR_CANCELLATION',
  HALLMARK_KARAT='HALLMARK_KARAT',
  REASON_FOR_CHANGING_DISCOUNT='REASON_FOR_CHANGING_DISCOUNT',
  REASON_FOR_NOT_GIVING_DISCOUNT='REASON_FOR_NOT_GIVING_DISCOUNT',
  FULL_VALUE_TEP_REASON ='FULL_VALUE_TEP_REASON',
  RELATIONSHIP_TYPE='RELATIONSHIP_TYPE'
}

export enum LovMasterEndpointServiceEnum {
  PRODUCT = 'product',
  CONFIG = 'config',
  PAYMENT = 'payment',
  LOCATION = 'location',
  INVENTORY = 'inventory',
  REPORT = 'report'
}

// Action interfaces
export interface LoadLovListingPayload {
  pageIndex: number;
  pageSize: number;
}

export interface LoadLovListingSuccessPayload {
  LovListing: LovMaster[];
  totalElements: number;
}
