export enum printTypesEnum {
  CM_PRINTS = 'CM',
  CN_CANCELLATION = 'CREDIT_NOTE_CANCELLATION',
  AB_PRINTS = 'AB',
  ACCEPT_ADVANCE_PRINTS = 'ACCEPT_ADVANCE',
  GC_PRINTS = 'GC',
  GEP_PRINTS = 'GEP',
  GEP_CANCEL_PRINTS = 'GEP_CANCEL',
  TEP_CANCEL_PRINTS = 'TEP_CANCEL',
  GRN_PRINTS = 'GRN_PRINTS',
  GRN = 'GRN',
  TEP_PRINTS = 'TEP',
  TEP_REFUND = 'TEP_REFUND',
  CHEQUE_DEPOSIT_PRINT = 'DEPOSIT',
  CASH_DEPOSIT_PRINT = 'DEPOSIT',
  FOC = 'FOC',
  LOSS = 'LOSS',
  EXH = 'EXH',
  LOAN = 'LOAN',
  ADJ = 'ADJ',
  PSV = 'PSV',
  CONV = 'CONV',
  FAC_BTQ = 'FAC_BTQ',
  BTQ_FAC = 'BTQ_FAC',
  BTQ_BTQ = 'BTQ_BTQ',
  MER_BTQ = 'MER_BTQ',
  TEP_PLAIN = 'MER_BTQ',
  TEP_STUDDED = 'TEP_STUDDED',
  GEP = 'GEP',
  COIN = 'COIN',
  BTQ_CFA = 'BTQ_CFA',
  MERGE_GRF = 'MERGE_GRF',
  GRF = 'GRF',
  TEP_ANNEXURE = 'TEP_ANNEXURE',
  CM_ANNEXURE = 'CM_ANNEXURE',
  COA = 'COA',
  BILL_CANCELLATION = 'BILL_CANCELLATION',
  CREDIT_NOTE = 'CREDIT_NOTE',
  GEP_DIGITAL_SIGNATURE = 'GEP_DIGITAL_SIGNATURE',
  TEP_DIGITAL_SIGNATURE = 'TEP_DIGITAL_SIGNATURE',
}

export enum otherIssuePrintTypesEnum {
  FOC = 'FOC',
  LOSS = 'LOSS',
  EXH = 'EXH',
  LOAN = 'LOAN',
  ADJ = 'ADJ',
  PSV = 'PSV',
  CONV = 'CONV'
}

export enum stockReceicePrintTypesEnum {
  FAC_BTQ = 'FAC_BTQ',
  BTQ_FAC = 'BTQ_FAC',
  BTQ_BTQ = 'BTQ_BTQ',
  MER_BTQ = 'MER_BTQ',
  TEP_PLAIN = 'MER_BTQ',
  TEP_STUDDED = 'TEP_STUDDED',
  GEP = 'GEP',
  FOC = 'FOC',
  COIN = 'COIN'
}

export enum invoiceReturnPrintTypesEnum {
  BTQ_CFA = 'BTQ_CFA',
  TEP_PLAIN = 'TEP_PLAIN',
  TEP_STUDDED = 'TEP_STUDDED',
  GEP = 'GEP',
  COIN = 'COIN'
}

export enum printTransactionTypesEnum {
  STOCK_ISSUE = 'STOCK_ISSUE',
  STOCK_TRANSFER = 'STOCK_TRANSFER',
  OTHER_ISSUE = 'OTHER_ISSUE',
  RETURN_INVOICE = 'RETURN_INVOICE',
  SALES = 'SALES',
  OTHER_RECEIVE = 'OTHER-RECEIVES'
}

export enum printFileTypeEnum {
  INVOICE_PRINT = 'INVOICE_PRINT',
  CASH_PRINT = 'CASH_PRINT',
  CHEQUE_PRINT = 'CHEQUE_PRINT'
}

export enum printDocTypeEnum {
  CUSTOMER_PRINT = 'CUSTOMER_PRINT',
  GURANTEE_CARD = 'GUARANTEE_CARD',
  CREDIT_NOTE = 'CREDIT_NOTE',
  OTHERS = 'OTHERS',
  STOCK_PRINT = 'STOCK_PRINT'
}

export enum printMsgEnum {
  PRINT_SUCCESS = 'PRINT_SUCCESS'
}
