/*  Copyright 2019. Titan Company Limited
*  All rights reserved.
*/
package com.titan.poss.core.domain.constant;

/**
 * @author Mindtree Ltd.
 * @version 1.0
 */
public enum FileGroupEnum {

	STN, INVOICE, FIR, MER, CARD_DETAILS, PAYMENT_HOSTNAME_MAPPING, PAYER_BANK, AIRPAY_CONFIG, ORACLE, NETCARROTS,
	GV_STATUS_UPDATE, GV_VALIDITY_EXTEND, GEP_CONFIG_EXCLUDE_MAPPING, TAX_CONFIG, PRODUCT_PRICE_MAPPING,
	GHS_BANK_DEPOSIT, QCGC_CONFIG, RETURN_INVOICE, ITEM_GROUP_LEVEL_DISCOUNT, BEST_DEAL_DISCOUNT,
	DISCOUNT_EXCLUDE_ITEM_MAPPING, TEP_AP, PRICE_LOGIC_TEST, RAZORPAY_CONFIG, TEP_TRANSACTION, STUDDED_SPLIT, STN_IBT,EMPLOYEE_LOAN_CONFIG,COMPLEXITY_PRICE_GROUP_DETAILS,SERVICE_POSS_BANK_DEPOSIT;


}
