/*  
 * Copyright 2019. Titan Company Limited
 * All rights reserved.
 */

package com.titan.poss.core.domain.constant;

/**
 * Customer type enum.
 * 
 * @author Mindtree Ltd.
 * @version 1.0
 */

public enum FileMasterJobNameEnum {

	// @formatter:off

	NC_TRANSACTION_DATA_JOB("TRANSACTION_DATA"), NC_STORE_DATA_JOB("STORE_DATA"), NC_MEMBER_DATA_JOB("MEMBER_DATA"),
	NC_NO_OF_RECORDS_DATA_JOB("NO_OF_RECORDS"), ITEM_MASTER("ITEM_MASTER"), STONE_MASTER("STONE_MASTER"),
	PRICE_MASTER("PRICE_MASTER"), AIRPAY_CONFIG("AIRPAY_CONFIG"), MATERIAL_MASTER("MATERIAL_MASTER"),
	ITEM_MATERIAL_MAPPING("ITEM_MATERIAL_MAPPING"), ITEM_STONE_MAPPING("ITEM_STONE_MAPPING"),
	GIFT_VOUCHER_INDENT("GIFT_VOUCHER_INDENT"), GIFT_VOUCHER_STATUS("GIFT_VOUCHER_STATUS"),
	GIFT_VOUCHER_STATUS_UPDATE("GIFT_VOUCHER_STATUS_UPDATE"),
	GIFT_VOUCHER_EXTEND_VALIDITY("GIFT_VOUCHER_EXTEND_VALIDITY"), CARD_DETAILS("CARD_DETAILS"),
	PAYER_BANK("PAYER_BANK"), PAYMENT_HOSTNAME_MAPPING("PAYMENT_HOSTNAME_MAPPING"),
	GEP_CONFIG_EXCLUDE_MAPPING("GEP_CONFIG_EXCLUDE_MAPPING"), TAX_CONFIG("TAX_CONFIG"),
	PRODUCT_PRICE_MAPPING("PRODUCT_PRICE_MAPPING"), STN("STN"), INVOICE("INVOICE"), FIR_MER("firMerJob"),
	GV_REDEMPTION_JOB("GV_REDEMPTION"), BOUTIQUE_REVENUE_JOB("BOUTIQUE_REVENUE"),DEBIT_NOTE_JOB("DEBIT_NOTE"),DEBIT_NOTE_L3_JOB("DEBIT_NOTE_L3"),BOUTIQUE_SALES_JOB("BOUTIQUE_SALES")
	, QCGC_CONFIG("QCGC_CONFIG"), RETURN_INVOICE_JOB("RETURN_INVOICE"), ITEM_GROUP_LEVEL_DISCOUNT("ITEM_GROUP_LEVEL_DISCOUNT"), DISCOUNT_EXCLUDE_ITEM_MAPPING("DISCOUNT_EXCLUDE_ITEM_MAPPING"),TEP_AP_JOB("TEP_AP")
	, PRICING_LOGIC_TEST_JOB("PRICE_LOGIC_TEST"), GENERAL_LEDGER_JOB("GENERAL_LEDGER"), RAZORPAY_CONFIG("RAZORPAY_CONFIG"), STOCK_INTERFACE_JOB("STOCK_INTERFACE"), TEP_TRANSACTION_JOB("TEP_TRANSACTION"),
    STUDDED_SPLIT_JOB("STUDDED_SPLIT"), IBT_STN_JOB("IBT_STN"),EMPLOYEE_LOAN_CONFIG("EMLOYEE_LOAN"), COMPLEXITY_PRICE_GROUP_DETAILS("COMPLEXITY_PRICE_GROUP_DETAILS");

	// @formatter:on

	private String value;

	public String getValue() {
		return this.value;

	}

	private FileMasterJobNameEnum(String value) {
		this.value = value;
	}
}
