/*  
 * Copyright 2019. Titan Company Limited
 * All rights reserved.
 */

package com.titan.poss.core.domain.constant;

/**
 * 
 * @author Mindtree Ltd.
 * @version 1.0
 */

public enum GhsTransactionEnum {

	GET_CREDITNOTE, CUSTOMER_CHECK, CUSTOMER_SAVE, TRANSFER_CREDITNOTE, UPDATE_CREDITNOTE, GET_DISCOUNT_VOUCHER,
	REDEEM_DISCOUNT_VOUCHER, BOD, EOD, GET_ACCOUNT_DETAILS, REDEEM_GHS_ACCOUNT, CASH_COLLECTED_GHS, UPDATE_CN_PASSBOOOK,
	GET_REVENUE_EOD, GET_TODAY_REVENUE, REVERSE_REDEMPTION, UPDATE_THRESHOLD_AMOUNT, DELETE_PARTIAL_ACCOUNT,
	UPDATE_HOLD_STATUS_MATURITY,CHECK_CN_STATUS,CHECK_BOD_STATUS,UPDATE_GR,CHECK_EOD_STATUS

}
