/*  
 * Copyright 2019. Titan Company Limited
 * All rights reserved.
 */
package com.titan.poss.core.domain.constant;

/**
 * @author Mindtree Ltd.
 * @version 1.0
 */
public enum RuleTypeEnum {

	WEIGHT_TOLERANCE, IBT_CONFIGURATIONS, INVOICE_CONFIGURATIONS, CONVERSIONS, HISTORY_TIME_CONFIGURATION,
	CASH_CONFIGURATION, GRF_CONFIGURATION, GRN_TOLERANCE_CONFIG, ORDER_AB_FROZEN_TOLERANCE,
	ORDER_AB_RESIDUAL_TOLERANCE_CONFIG, CN_PRIORITY_CONFIG, TEP, GRN, GHS, GEP, CN_IBT, BILL_CANCELLATION, ADV,
	ORDER_AB_PAYMENT_CONFIG, GRN_INTER_OWNER_TYPE, BEST_GOLD_RATE, BGR_TOLERANCE_CONFIG, GRN_APPROVAL_ACCESS_REGULAR,
	GRN_APPROVAL_ACCESS_MFG_DEFECT, ORDER_AB_BGR_CONFIG, ORDER_AB_NON_FROZEN_TOLERANCE,
	WORKFLOW_REQEXPIRE_GLOBAL_CONFIG, FTEP_APPROVAL_ACCESS_REGULAR, RIVAAH_CARD_ELIGIBILITY, DIGI_GOLD_TANISHQ,
	DIGI_GOLD_NON_TANISHQ, TCS_CREDIT_NOTE, AMENDMENT_CONFIGURATION, EVOUCHER, ORDER_CO_FROZEN_TOLERANCE,
	ORDER_CO_NON_FROZEN_TOLERANCE,ORDER_CO_RESIDUAL_TOLERANCE_CONFIG,ORDER_CO_PAYMENT_CONFIG,ORDER_CO_BGR_CONFIG,
	BGR_CO_TOLERANCE_CONFIG;

}
