import { LocationSettingDetails } from '@poss-web/shared/models';

export class LocationSettingsAdpator {
  static loadLocationSettings(data: any): LocationSettingDetails {
    let locationSettingsResponse: LocationSettingDetails;

    if (data) {
      locationSettingsResponse = {
        factory_baseCurrency: data.factoryDetails
          ? data.factoryDetails.baseCurrency
            ? data.factoryDetails.baseCurrency
            : ''
          : '',
        factory_brandCode: data.factoryDetails
          ? data.factoryDetails.brandCode
            ? data.factoryDetails.brandCode
            : ''
          : '',
        factory_cfaCodeValue: data.factoryDetails
          ? data.factoryDetails.cfaCodeValue
            ? data.factoryDetails.cfaCodeValue
            : ''
          : '',
        factory_countryCode: data.factoryDetails
          ? data.factoryDetails.countryCode
            ? data.factoryDetails.countryCode
            : ''
          : '',
        factory_description: data.factoryDetails
          ? data.factoryDetails.description
            ? data.factoryDetails.description
            : ''
          : '',
        factory_factoryCodeValue: data.factoryDetails
          ? data.factoryDetails.factoryCodeValue
            ? data.factoryDetails.factoryCodeValue
            : ''
          : '',
        factory_fax: data.factoryDetails
          ? data.factoryDetails.fax
            ? data.factoryDetails.fax
            : ''
          : '',
        factory_isActive: data.factoryDetails
          ? data.factoryDetails.isActive
            ? data.factoryDetails.isActive
            : false
          : false,
        factory_locationCode: data.factoryDetails
          ? data.factoryDetails.locationCode
            ? data.factoryDetails.locationCode
            : ''
          : '',
        factory_locationFormat: data.factoryDetails
          ? data.factoryDetails.locationFormat
            ? data.factoryDetails.locationFormat
            : ''
          : '',
        factory_locationTypeCode: data.factoryDetails
          ? data.factoryDetails.locationTypeCode
            ? data.factoryDetails.locationTypeCode
            : ''
          : '',
        factory_marketCode: data.factoryDetails
          ? data.factoryDetails.marketCode
            ? data.factoryDetails.marketCode
            : ''
          : '',
        factory_masterCurrency: data.factoryDetails
          ? data.factoryDetails.masterCurrency
            ? data.factoryDetails.masterCurrency
            : ''
          : '',
        factory_ownerTypeCode: data.factoryDetails
          ? data.factoryDetails.ownerTypeCode
            ? data.factoryDetails.ownerTypeCode
            : ''
          : '',
        factory_paymentCurrencies: data.factoryDetails
          ? data.factoryDetails.paymentCurrencies
            ? data.factoryDetails.paymentCurrencies
            : ''
          : '',
        factory_regionCode: data.factoryDetails
          ? data.factoryDetails.regionCode
            ? data.factoryDetails.regionCode
            : ''
          : '',
        factory_remarks: data.factoryDetails
          ? data.factoryDetails.remarks
            ? data.factoryDetails.remarks
            : null
          : null,
        factory_stateId: data.factoryDetails
          ? data.factoryDetails.stateId
            ? data.factoryDetails.stateId
            : ''
          : '',
        factory_stateName: data.factoryDetails
          ? data.factoryDetails.stateName
            ? data.factoryDetails.stateName
            : ''
          : '',
        factory_stockCurrency: data.factoryDetails
          ? data.factoryDetails.stockCurrency
            ? data.factoryDetails.stockCurrency
            : ''
          : '',
        factory_subBrandCode: data.factoryDetails
          ? data.factoryDetails.subBrandCode
            ? data.factoryDetails.subBrandCode
            : ''
          : '',
        factory_subRegionCode: data.factoryDetails
          ? data.factoryDetails.subRegionCode
            ? data.factoryDetails.subRegionCode
            : ''
          : '',
        factory_townId: data.factoryDetails
          ? data.factoryDetails.townId
            ? data.factoryDetails.townId
            : ''
          : '',
        factory_townName: data.factoryDetails
          ? data.factoryDetails.townName
            ? data.factoryDetails.townName
            : ''
          : '',

        cfa_baseCurrency: data.cfaDetails
          ? data.cfaDetails.baseCurrency
            ? data.cfaDetails.baseCurrency
            : ''
          : '',
        cfa_brandCode: data.cfaDetails
          ? data.cfaDetails.brandCode
            ? data.cfaDetails.brandCode
            : ''
          : '',
        cfa_cfaCodeValue: data.cfaDetails
          ? data.cfaDetails.cfaCodeValue
            ? data.cfaDetails.cfaCodeValue
            : null
          : null,
        cfa_countryCode: data.cfaDetails
          ? data.cfaDetails.countryCode
            ? data.cfaDetails.countryCode
            : ''
          : '',
        cfa_description: data.cfaDetails
          ? data.cfaDetails.description
            ? data.cfaDetails.description
            : ''
          : '',
        cfa_factoryCodeValue: data.cfaDetails
          ? data.cfaDetails.factoryCodeValue
            ? data.cfaDetails.factoryCodeValue
            : null
          : null,
        cfa_fax: data.cfaDetails
          ? data.cfaDetails.fax
            ? data.cfaDetails.fax
            : ''
          : '',
        cfa_isActive: data.cfaDetails
          ? data.cfaDetails.isActive
            ? data.cfaDetails.isActive
            : false
          : false,
        cfa_locationCode: data.cfaDetails
          ? data.cfaDetails.locationCode
            ? data.cfaDetails.locationCode
            : ''
          : '',
        cfa_locationFormat: data.cfaDetails
          ? data.cfaDetails.locationFormat
            ? data.cfaDetails.locationFormat
            : ''
          : '',
        cfa_locationTypeCode: data.cfaDetails
          ? data.cfaDetails.locationTypeCode
            ? data.cfaDetails.locationTypeCode
            : ''
          : '',
        cfa_marketCode: data.cfaDetails
          ? data.cfaDetails.marketCode
            ? data.cfaDetails.marketCode
            : ''
          : '',
        cfa_masterCurrency: data.cfaDetails
          ? data.cfaDetails.masterCurrency
            ? data.cfaDetails.masterCurrency
            : ''
          : '',
        cfa_ownerTypeCode: data.cfaDetails
          ? data.cfaDetails.ownerTypeCode
            ? data.cfaDetails.ownerTypeCode
            : ''
          : '',
        cfa_paymentCurrencies: data.cfaDetails
          ? data.cfaDetails.paymentCurrencies
            ? data.cfaDetails.paymentCurrencies
            : ''
          : '',
        cfa_regionCode: data.cfaDetails
          ? data.cfaDetails.regionCode
            ? data.cfaDetails.regionCode
            : ''
          : '',
        cfa_remarks: data.cfaDetails
          ? data.cfaDetails.remarks
            ? data.cfaDetails.remarks
            : ''
          : '',
        cfa_stateId: data.cfaDetails
          ? data.cfaDetails.stateId
            ? data.cfaDetails.stateId
            : ''
          : '',
        cfa_stateName: data.cfaDetails
          ? data.cfaDetails.stateName
            ? data.cfaDetails.stateName
            : ''
          : '',
        cfa_stockCurrency: data.cfaDetails
          ? data.cfaDetails.stockCurrency
            ? data.cfaDetails.stockCurrency
            : ''
          : '',
        cfa_subBrandCode: data.cfaDetails
          ? data.cfaDetails.subBrandCode
            ? data.cfaDetails.subBrandCode
            : ''
          : '',
        cfa_subRegionCode: data.cfaDetails
          ? data.cfaDetails.subRegionCode
            ? data.cfaDetails.subRegionCode
            : ''
          : '',
        cfa_townId: data.cfaDetails
          ? data.cfaDetails.townId
            ? data.cfaDetails.townId
            : ''
          : '',
        cfa_townName: data.cfaDetails
          ? data.cfaDetails.townName
            ? data.cfaDetails.townName
            : ''
          : '',

        country_countryCode: data.country
          ? data.country.countryCode
            ? data.country.countryCode
            : ''
          : '',
        country_currencyCode: data.country
          ? data.country.currencyCode
            ? data.country.currencyCode
            : ''
          : '',
        country_dateFormat: data.country
          ? data.country.dateFormat
            ? data.country.dateFormat
            : ''
          : '',
        country_description: data.country
          ? data.country.description
            ? data.country.description
            : ''
          : '',
        country_fiscalYear: data.country
          ? data.country.fiscalYear
            ? data.country.fiscalYear
            : null
          : null,
        country_fiscalYearEnd: data.country
          ? data.country.fiscalYearEnd
            ? data.country.fiscalYearEnd
            : ''
          : '',
        country_fiscalYearStart: data.country
          ? data.country.fiscalYearStart
            ? data.country.fiscalYearStart
            : ''
          : '',
        country_isActive: data.country
          ? data.country.isActive
            ? data.country.isActive
            : false
          : false,
        country_isdCode: data.country
          ? data.country.isdCode
            ? data.country.isdCode
            : ''
          : '',
        country_lastModifiedDate: data.country
          ? data.country.lastModifiedDate
            ? data.country.lastModifiedDate
            : ''
          : '',
        country_locale: data.country
          ? data.country.locale
            ? data.country.locale
            : ''
          : '',
        country_phoneLength: data.country
          ? data.country.phoneLength
            ? data.country.phoneLength
            : null
          : null,
        country_timeFormat: data.country
          ? data.country.timeFormat
            ? data.country.timeFormat
            : ''
          : '',
        country_weightUnit: data.country
          ? data.country.weightUnit
            ? data.country.weightUnit
            : ''
          : '',
        country_stoneWeightUnit: data.country
          ? data.country.stoneWeightUnit
            ? data.country.stoneWeightUnit
            : ''
          : '',

        baseCurrency_currencyCode: data.baseCurrency
          ? data.baseCurrency.currencyCode
            ? data.baseCurrency.currencyCode
            : ''
          : '',
        baseCurrency_currencySymbol: data.baseCurrency
          ? data.baseCurrency.currencySymbol
            ? data.baseCurrency.currencySymbol
            : ''
          : '',
        baseCurrency_description: data.baseCurrency
          ? data.baseCurrency.description
            ? data.baseCurrency.description
            : ''
          : '',
        baseCurrency_unicode: data.baseCurrency
          ? data.baseCurrency.unicode
            ? data.baseCurrency.unicode
            : ''
          : '',
        baseCurrency_isActive: data.baseCurrency
          ? data.baseCurrency.isActive
            ? data.baseCurrency.isActive
            : false
          : false,
        baseCurrency_lastModifiedDate: data.baseCurrency
          ? data.baseCurrency.lastModifiedDate
            ? data.baseCurrency.lastModifiedDate
            : null
          : null,

        store_companyName: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.companyName
              ? data.storeDetails.data.companyName
              : ''
            : ''
          : '',
        store_regdOffice: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.regdOffice
              ? data.storeDetails.data.regdOffice
              : ''
            : ''
          : '',
        store_cinNumber: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.cinNumber
              ? data.storeDetails.data.cinNumber
              : ''
            : ''
          : '',
        store_corporateAddress: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.corporateAddress
              ? data.storeDetails.data.corporateAddress
              : ''
            : ''
          : '',
        store_isWalkInsDetailsMandatory: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.isWalkInsDetailsMandatory
              ? data.storeDetails.data.isWalkInsDetailsMandatory
              : false
            : false
          : false,
        store_numberOfDaysToDisplay: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.numberOfDaysToDisplay
              ? data.storeDetails.data.numberOfDaysToDisplay
              : null
            : null
          : null,
        store_noOfDays: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.noOfDays
              ? data.storeDetails.data.noOfDays
              : null
            : null
          : null,
        store_addressLines: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.addressLines
              ? data.storeDetails.data.addressLines
              : null
            : null
          : null,
        store_phoneNumber1: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.phoneNumber1
              ? data.storeDetails.data.phoneNumber1
              : ''
            : ''
          : '',
        store_phoneNumber2: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.phoneNumber2
              ? data.storeDetails.data.phoneNumber2
              : ''
            : ''
          : '',
        store_contactNumber: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.contactNumber
              ? data.storeDetails.data.contactNumber
              : ''
            : ''
          : '',
        store_pincode: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.pincode
              ? data.storeDetails.data.pincode
              : ''
            : ''
          : '',
        store_boutiqueEmailId: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.boutiqueEmailId
              ? data.storeDetails.data.boutiqueEmailId
              : ''
            : ''
          : '',
        store_maxRateRetryAttempt: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.maxRateRetryAttempt
              ? data.storeDetails.data.maxRateRetryAttempt
              : null
            : null
          : null,
        store_isDial: data.storeDetails
          ? data.storeDetails.data
            ? data.storeDetails.data.isDial
              ? data.storeDetails.data.isDial
              : false
            : false
          : false,

        print_printWastagePercent: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printWastagePercent
              ? data.printDetails.data.printWastagePercent
              : false
            : false
          : false,
        print_printWastageComponent: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printWastageComponent
              ? data.printDetails.data.printWastageComponent
              : false
            : false
          : false,
        print_printWastageCharge: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printWastageCharge
              ? data.printDetails.data.printWastageCharge
              : false
            : false
          : false,
        print_printStoneValue: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printStoneValue
              ? data.printDetails.data.printStoneValue
              : false
            : false
          : false,
        print_printGoldValue: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printGoldValue
              ? data.printDetails.data.printGoldValue
              : false
            : false
          : false,
        print_printPrice: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printPrice
              ? data.printDetails.data.printPrice
              : false
            : false
          : false,
        print_freeTextForGrams: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.freeTextForGrams
              ? data.printDetails.data.freeTextForGrams
              : ''
            : ''
          : '',
        print_mcOrWastageExpense: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.mcOrWastageExpense
              ? data.printDetails.data.mcOrWastageExpense
              : ''
            : ''
          : '',
        print_isMCAndWastage: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.isMCAndWastage
              ? data.printDetails.data.isMCAndWastage
              : false
            : false
          : false,
        print_isDisplayWastagePercent: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.isDisplayWastagePercent
              ? data.printDetails.data.isDisplayWastagePercent
              : false
            : false
          : false,
        print_isVariablePrice: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.isVariablePrice
              ? data.printDetails.data.isVariablePrice
              : false
            : false
          : false,
        print_printMakingCharges: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printMakingCharges
              ? data.printDetails.data.printMakingCharges
              : false
            : false
          : false,
        print_printCustomerNumberinReport: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printCustomerNumberinReport
              ? data.printDetails.data.printCustomerNumberinReport
              : false
            : false
          : false,
        print_printCashMemo: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printCashMemo
              ? data.printDetails.data.printCashMemo
              : false
            : false
          : false,
        print_printGuaranteeCard: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printGuaranteeCard
              ? data.printDetails.data.printGuaranteeCard
              : false
            : false
          : false,
        print_printOtherStoneWtinGuaranteeCard: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printOtherStoneWtinGuaranteeCard
              ? data.printDetails.data.printOtherStoneWtinGuaranteeCard
              : false
            : false
          : false,
        print_printOtherStoneWeightinAnnexure: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printOtherStoneWeightinAnnexure
              ? data.printDetails.data.printOtherStoneWeightinAnnexure
              : false
            : false
          : false,
        print_noOfInvoicecopiesforRegularOrQuickCM: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.noOfInvoicecopiesforRegularOrQuickCM
              ? data.printDetails.data.noOfInvoicecopiesforRegularOrQuickCM
              : ''
            : ''
          : '',
        print_invoiceType: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.invoiceType
              ? data.printDetails.data.invoiceType
              : ''
            : ''
          : '',
        print_printImage: data.printDetails
          ? data.printDetails.data
            ? data.printDetails.data.printImage
              ? data.printDetails.data.printImage
              : false
            : false
          : false,

        cn_suspendingCNs: data.cnDetails
          ? data.cnDetails.data
            ? data.cnDetails.data.suspendingCNs
              ? data.cnDetails.data.suspendingCNs
              : ''
            : ''
          : '',
        cn_transferredCNs: data.cnDetails
          ? data.cnDetails.data
            ? data.cnDetails.data.transferredCNs
              ? data.cnDetails.data.transferredCNs
              : ''
            : ''
          : '',
        cn_activatedCNs: data.cnDetails
          ? data.cnDetails.data
            ? data.cnDetails.data.activatedCNs
              ? data.cnDetails.data.activatedCNs
              : ''
            : ''
          : '',
        cn_maxNoOfCN: data.cnDetails
          ? data.cnDetails.data
            ? data.cnDetails.data.maxNoOfCN
              ? data.cnDetails.data.maxNoOfCN
              : ''
            : ''
          : '',
        cn_otpForMinCN: data.cnDetails
          ? data.cnDetails.data
            ? data.cnDetails.data.otpForMinCN
              ? data.cnDetails.data.otpForMinCN
              : ''
            : ''
          : '',
        cn_maxNoOfTimesCNinEGHS: data.cnDetails
          ? data.cnDetails.data
            ? data.cnDetails.data.maxNoOfTimesCNinEGHS
              ? data.cnDetails.data.maxNoOfTimesCNinEGHS
              : ''
            : ''
          : '',
        cn_isEmployeeLoanCNCancel: data.cnDetails
          ? data.cnDetails.data
            ? data.cnDetails.data.isEmployeeLoanCNCancel
              ? data.cnDetails.data.isEmployeeLoanCNCancel
              : false
            : false
          : false,
        cn_isEmployeeLoanCNTransfer: data.cnDetails
          ? data.cnDetails.data
            ? data.cnDetails.data.isEmployeeLoanCNTransfer
              ? data.cnDetails.data.isEmployeeLoanCNTransfer
              : false
            : false
          : false,
        cn_isUploadMandatoryforThirdPartyCNWithoutOTP: data.cnDetails
          ? data.cnDetails.data
            ? data.cnDetails.data.isUploadMandatoryforThirdPartyCNWithoutOTP
              ? data.cnDetails.data.isUploadMandatoryforThirdPartyCNWithoutOTP
              : false
            : false
          : false,

        tax_isGST: data.taxDetails
          ? data.taxDetails.data
            ? data.taxDetails.data.isGST
              ? data.taxDetails.data.isGST
              : false
            : false
          : false,
        tax_gstRegisterationNo: data.taxDetails
          ? data.taxDetails.data
            ? data.taxDetails.data.gstRegisterationNo
              ? data.taxDetails.data.gstRegisterationNo
              : ''
            : ''
          : '',
        tax_gstValidFrom: data.taxDetails
          ? data.taxDetails.data
            ? data.taxDetails.data.gstValidFrom
              ? data.taxDetails.data.gstValidFrom
              : ''
            : ''
          : '',
        tax_gstPrintValidFrom: data.taxDetails
          ? data.taxDetails.data
            ? data.taxDetails.data.gstPrintValidFrom
              ? data.taxDetails.data.gstPrintValidFrom
              : ''
            : ''
          : '',

        cm_noOfHoursForOpenTaskDeletionCM: data.cmDetails
          ? data.cmDetails.data
            ? data.cmDetails.data.noOfHoursForOpenTaskDeletionCM
              ? data.cmDetails.data.noOfHoursForOpenTaskDeletionCM
              : ''
            : ''
          : '',
        cm_cmHoldTimeInMinutes: data.cmDetails
          ? data.cmDetails.data
            ? data.cmDetails.data.cmHoldTimeInMinutes
              ? data.cmDetails.data.cmHoldTimeInMinutes
              : ''
            : ''
          : '',
        cm_isBillCancelApprovalRequired: data.cmDetails
          ? data.cmDetails.data
            ? data.cmDetails.data.isBillCancelApprovalRequired
              ? data.cmDetails.data.isBillCancelApprovalRequired
              : false
            : false
          : false,
        cm_isMobileAndEmail: data.cmDetails
          ? data.cmDetails.data
            ? data.cmDetails.data.isMobileAndEmail
              ? data.cmDetails.data.isMobileAndEmail
              : false
            : false
          : false,
        cm_isMobileAndEmailMandatoryForCorrection: data.cmDetails
          ? data.cmDetails.data
            ? data.cmDetails.data.isMobileAndEmailMandatoryForCorrection
              ? data.cmDetails.data.isMobileAndEmailMandatoryForCorrection
              : false
            : false
          : false,
        cm_isEditWeightAllowed: data.cmDetails
          ? data.cmDetails.data
            ? data.cmDetails.data.isEditWeightAllowed
              ? data.cmDetails.data.isEditWeightAllowed
              : false
            : false
          : false,
        cm_isTitle: data.cmDetails
          ? data.cmDetails.data
            ? data.cmDetails.data.isTitle
              ? data.cmDetails.data.isTitle
              : false
            : false
          : false,
        cm_maxNoOfHoursForBillCancel: data.cmDetails
          ? data.cmDetails.data
            ? data.cmDetails.data.maxNoOfHoursForBillCancel
              ? data.cmDetails.data.maxNoOfHoursForBillCancel
              : ''
            : ''
          : '',

        grn_noOfDaysGRNAllowed: data.grnDetails
          ? data.grnDetails.data
            ? data.grnDetails.data.noOfDaysGRNAllowed
              ? data.grnDetails.data.noOfDaysGRNAllowed
              : ''
            : ''
          : '',
        grn_maximumNoOfDaysForApprovedGRN: data.grnDetails
          ? data.grnDetails.data
            ? data.grnDetails.data.maximumNoOfDaysForApprovedGRN
              ? data.grnDetails.data.maximumNoOfDaysForApprovedGRN
              : ''
            : ''
          : '',
        grn_noOfDaysToProtectGoldRateForGRN: data.grnDetails
          ? data.grnDetails.data
            ? data.grnDetails.data.noOfDaysToProtectGoldRateForGRN
              ? data.grnDetails.data.noOfDaysToProtectGoldRateForGRN
              : ''
            : ''
          : '',
        grn_minUtilizationPercentForGRN: data.grnDetails
          ? data.grnDetails.data
            ? data.grnDetails.data.minUtilizationPercentForGRN
              ? data.grnDetails.data.minUtilizationPercentForGRN
              : ''
            : ''
          : '',
        grn_isInterBoutiqueGRNAllowed: data.grnDetails
          ? data.grnDetails.data
            ? data.grnDetails.data.isInterBoutiqueGRNAllowed
              ? data.grnDetails.data.isInterBoutiqueGRNAllowed
              : false
            : false
          : false,
        grn_isGRNAllowedInCM: data.grnDetails
          ? data.grnDetails.data
            ? data.grnDetails.data.isGrnAllowedInCm
              ? data.grnDetails.data.isGrnAllowedInCm
              : false
            : false
          : false,
        grn_isGrnAllowedInAdvanceBooking: data.grnDetails
          ? data.grnDetails.data
            ? data.grnDetails.data.isGrnAllowedInAdvanceBooking
              ? data.grnDetails.data.isGrnAllowedInAdvanceBooking
              : false
            : false
          : false,
        grf_minimumUtilization: data.grfDetails
          ? data.grfDetails.data
            ? data.grfDetails.data.minimumUtilization
              ? data.grfDetails.data.minimumUtilization
              : ''
            : ''
          : '',
        grf_isGRFAllowed: data.grfDetails
          ? data.grfDetails.data
            ? data.grfDetails.data.isGRFAllowed
              ? data.grfDetails.data.isGRFAllowed
              : false
            : false
          : false,
        grf_isGRFAllowedInCM: data.grfDetails
          ? data.grfDetails.data
            ? data.grfDetails.data.isGRFAllowedInCM
              ? data.grfDetails.data.isGRFAllowedInCM
              : false
            : false
          : false,
        grf_isGRFAllowedInAdvanceBooking: data.grfDetails
          ? data.grfDetails.data
            ? data.grfDetails.data.isGRFAllowedInAdvanceBooking
              ? data.grfDetails.data.isGRFAllowedInAdvanceBooking
              : false
            : false
          : false,
        grf_isGRFAllowedInCustomerOrder: data.grfDetails
          ? data.grfDetails.data
            ? data.grfDetails.data.isGRFAllowedInCustomerOrder
              ? data.grfDetails.data.isGRFAllowedInCustomerOrder
              : false
            : false
          : false,
        grf_isMergeCNAllowed: data.grfDetails
          ? data.grfDetails.data
            ? data.grfDetails.data.isMergeCNAllowed
              ? data.grfDetails.data.isMergeCNAllowed
              : false
            : false
          : false,
        grf_currentOwner: data.grfDetails
          ? data.grfDetails.data
            ? data.grfDetails.data.currentOwner
              ? data.grfDetails.data.currentOwner
              : false
            : false
          : false,
        grf_thirdPerson: data.grfDetails
          ? data.grfDetails.data
            ? data.grfDetails.data.thirdPerson
              ? data.grfDetails.data.thirdPerson
              : false
            : false
          : false,

        gep_karatAcceptedForGEP: data.gepDetails
          ? data.gepDetails.data
            ? data.gepDetails.data.karatAcceptedForGEP
              ? data.gepDetails.data.karatAcceptedForGEP
              : ''
            : ''
          : '',
        gep_isPreMeltingDetailsMandatory: data.gepDetails
          ? data.gepDetails.data
            ? data.gepDetails.data.isPreMeltingDetailsMandatory
              ? data.gepDetails.data.isPreMeltingDetailsMandatory
              : false
            : false
          : false,
        gep_gepHoldTime: data.gepDetails
          ? data.gepDetails.data
            ? data.gepDetails.data.gepHoldTime
              ? data.gepDetails.data.gepHoldTime
              : ''
            : ''
          : '',
        gep_enableGEPSale: data.gepDetails
          ? data.gepDetails.data
            ? data.gepDetails.data.enableGEPSale
              ? data.gepDetails.data.enableGEPSale
              : false
            : false
          : false,
        gep_gepPureGoldPurity: data.gepDetails
          ? data.gepDetails.data
            ? data.gepDetails.data.gepPureGoldPurity
              ? data.gepDetails.data.gepPureGoldPurity
              : ''
            : ''
          : '',
        gep_gepPurePlatinumPurity: data.gepDetails
          ? data.gepDetails.data
            ? data.gepDetails.data.gepPurePlatinumPurity
              ? data.gepDetails.data.gepPurePlatinumPurity
              : ''
            : ''
          : '',
        gep_gepPureSilverPurity: data.gepDetails
          ? data.gepDetails.data
            ? data.gepDetails.data.gepPureSilverPurity
              ? data.gepDetails.data.gepPureSilverPurity
              : ''
            : ''
          : '',
        gep_gepStandardDeductionGold: data.gepDetails
          ? data.gepDetails.data
            ? data.gepDetails.data.gepStandardDeductionGold
              ? data.gepDetails.data.gepStandardDeductionGold
              : ''
            : ''
          : '',
        gep_gepStandardDeductionPlatinum: data.gepDetails
          ? data.gepDetails.data
            ? data.gepDetails.data.gepStandardDeductionPlatinum
              ? data.gepDetails.data.gepStandardDeductionPlatinum
              : ''
            : ''
          : '',
        gep_gepStandardDeductionSilver: data.gepDetails
          ? data.gepDetails.data
            ? data.gepDetails.data.gepStandardDeductionSilver
              ? data.gepDetails.data.gepStandardDeductionSilver
              : ''
            : ''
          : '',
        gep_noOfDaysGepCancel: data.gepDetails
          ? data.gepDetails.data
            ? data.gepDetails.data.noOfDaysGepCancel
              ? data.gepDetails.data.noOfDaysGepCancel
              : ''
            : ''
          : '',

        gc_maximumAmount: data.gcDetails
          ? data.gcDetails.data
            ? data.gcDetails.data.maximumAmount
              ? data.gcDetails.data.maximumAmount
              : ''
            : ''
          : '',
        gc_minimumAmount: data.gcDetails
          ? data.gcDetails.data
            ? data.gcDetails.data.minimumAmount
              ? data.gcDetails.data.minimumAmount
              : ''
            : ''
          : '',
        gc_multiplesValue: data.gcDetails
          ? data.gcDetails.data
            ? data.gcDetails.data.multiplesValue
              ? data.gcDetails.data.multiplesValue
              : ''
            : ''
          : '',
        gc_isCardCancellationAllowed: data.gcDetails
          ? data.gcDetails.data
            ? data.gcDetails.data.isCardCancellationAllowed
              ? data.gcDetails.data.isCardCancellationAllowed
              : false
            : false
          : false,
        gc_isCardInwardingAllowed: data.gcDetails
          ? data.gcDetails.data
            ? data.gcDetails.data.isCardInwardingAllowed
              ? data.gcDetails.data.isCardInwardingAllowed
              : false
            : false
          : false,
        gc_isCardActivationAllowed: data.gcDetails
          ? data.gcDetails.data
            ? data.gcDetails.data.isCardActivationAllowed
              ? data.gcDetails.data.isCardActivationAllowed
              : false
            : false
          : false,

        ab_requestApprovalForNonFrozenOrderCancel: data.abDetails
          ? data.abDetails.data
            ? data.abDetails.data.requestApprovalForNonFrozenOrderCancel
              ? data.abDetails.data.requestApprovalForNonFrozenOrderCancel
              : false
            : false
          : false,
        ab_noOfHoursForOpenTaskDeletion: data.abDetails
          ? data.abDetails.data
            ? data.abDetails.data.noOfHoursForOpenTaskDeletion
              ? data.abDetails.data.noOfHoursForOpenTaskDeletion
              : ''
            : ''
          : '',
        ab_cancellationAllowedforAdvanceBooking: data.abDetails
          ? data.abDetails.data
            ? data.abDetails.data.cancellationAllowedforAdvanceBooking
              ? data.abDetails.data.cancellationAllowedforAdvanceBooking
              : false
            : false
          : false,
        ab_activateAllowedforAdvanceBooking: data.abDetails
          ? data.abDetails.data
            ? data.abDetails.data.activateAllowedforAdvanceBooking
              ? data.abDetails.data.activateAllowedforAdvanceBooking
              : false
            : false
          : false,
        ab_validityDaysforAutoClosureInAdvanceBooking: data.abDetails
          ? data.abDetails.data
            ? data.abDetails.data.validityDaysforAutoClosureInAdvanceBooking
              ? data.abDetails.data.validityDaysforAutoClosureInAdvanceBooking
              : ''
            : ''
          : '',
        ab_validityDaysforActivateInAdvanceBooking: data.abDetails
          ? data.abDetails.data
            ? data.abDetails.data.validityDaysforActivateInAdvanceBooking
              ? data.abDetails.data.validityDaysforActivateInAdvanceBooking
              : ''
            : ''
          : '',
        ab_validityDaysforReleaseInvInAdvancebooking: data.abDetails
          ? data.abDetails.data
            ? data.abDetails.data.validityDaysforReleaseInvInAdvancebooking
              ? data.abDetails.data.validityDaysforReleaseInvInAdvancebooking
              : ''
            : ''
          : '',
        ab_minPercentToBePaidForFrozenOrder: data.abDetails
          ? data.abDetails.data
            ? data.abDetails.data.minPercentToBePaidForFrozenOrder
              ? data.abDetails.data.minPercentToBePaidForFrozenOrder
              : ''
            : ''
          : '',
        ab_minPercentToBePaidForNonFrozenOrder: data.abDetails
          ? data.abDetails.data
            ? data.abDetails.data.minPercentToBePaidForNonFrozenOrder
              ? data.abDetails.data.minPercentToBePaidForNonFrozenOrder
              : ''
            : ''
          : '',
        ab_abHoldTime: data.abDetails
          ? data.abDetails.data
            ? data.abDetails.data.abHoldTime
              ? data.abDetails.data.abHoldTime
              : ''
            : ''
          : '',

        co_cancellationAllowedforCustomerOrder: data.coDetails
          ? data.coDetails.data
            ? data.coDetails.data.cancellationAllowedforCustomerOrder
              ? data.coDetails.data.cancellationAllowedforCustomerOrder
              : false
            : false
          : false,
        co_activateAllowedforCustomerOrder: data.coDetails
          ? data.coDetails.data
            ? data.coDetails.data.activateAllowedforCustomerOrder
              ? data.coDetails.data.activateAllowedforCustomerOrder
              : false
            : false
          : false,
        co_validityDaysforAutoClosureInCustomerOrder: data.coDetails
          ? data.coDetails.data
            ? data.coDetails.data.validityDaysforAutoClosureInCustomerOrder
              ? data.coDetails.data.validityDaysforAutoClosureInCustomerOrder
              : ''
            : ''
          : '',
        co_validitydaysforReleaseInvInCustomerOrder: data.coDetails
          ? data.coDetails.data
            ? data.coDetails.data.validitydaysforReleaseInvInCustomerOrder
              ? data.coDetails.data.validitydaysforReleaseInvInCustomerOrder
              : ''
            : ''
          : '',
        co_maxNoofdaysforPOLikelyDate: data.coDetails
          ? data.coDetails.data
            ? data.coDetails.data.maxNoofdaysforPOLikelyDate
              ? data.coDetails.data.maxNoofdaysforPOLikelyDate
              : ''
            : ''
          : '',

        ghs_isEghsMandatory: data.ghsDetails
          ? data.ghsDetails.data
            ? data.ghsDetails.data.isEghsMandatory
              ? data.ghsDetails.data.isEghsMandatory
              : false
            : false
          : false,
        ghs_isConsentLetterUploadMandatory: data.ghsDetails
          ? data.ghsDetails.data
            ? data.ghsDetails.data.isConsentLetterUploadMandatory
              ? data.ghsDetails.data.isConsentLetterUploadMandatory
              : false
            : false
          : false,
        ghs_isClubbingGHSAccRestricted: data.ghsDetails
          ? data.ghsDetails.data
            ? data.ghsDetails.data.isClubbingGHSAccRestricted
              ? data.ghsDetails.data.isClubbingGHSAccRestricted
              : false
            : false
          : false,
        ghs_grammageCNTransfer: data.ghsDetails
          ? data.ghsDetails.data
            ? data.ghsDetails.data.grammageCNTransfer
              ? data.ghsDetails.data.grammageCNTransfer
              : false
            : false
          : false,
        ghs_isOtpRequired: data.ghsDetails
          ? data.ghsDetails.data
            ? data.ghsDetails.data.isOtpRequired
              ? data.ghsDetails.data.isOtpRequired
              : false
            : false
          : false,
        ghs_noOfDaysForSuspendingGhs: data.ghsDetails
          ? data.ghsDetails.data
            ? data.ghsDetails.data.noOfDaysForSuspendingGhs
              ? data.ghsDetails.data.noOfDaysForSuspendingGhs
              : ''
            : ''
          : '',
        ghs_consolidateAttempts: data.ghsDetails
          ? data.ghsDetails.data
            ? data.ghsDetails.data.consolidateAttempts
              ? data.ghsDetails.data.consolidateAttempts
              : ''
            : ''
          : '',
        ghs_gracePeriodAfterSuspenededGhs: data.ghsDetails
          ? data.ghsDetails.data
            ? data.ghsDetails.data.gracePeriodAfterSuspenededGhs
              ? data.ghsDetails.data.gracePeriodAfterSuspenededGhs
              : ''
            : ''
          : '',
        ghs_isGHSRedemptionAllowed: data.ghsDetails
          ? data.ghsDetails.data
            ? data.ghsDetails.data.isGHSRedemptionAllowed
              ? data.ghsDetails.data.isGHSRedemptionAllowed
              : false
            : false
          : false,
        ghs_isUploadMandatoryforGHSWithoutOTP: data.ghsDetails
          ? data.ghsDetails.data
            ? data.ghsDetails.data.isUploadMandatoryforGHSWithoutOTP
              ? data.ghsDetails.data.isUploadMandatoryforGHSWithoutOTP
              : false
            : false
          : false,

        inv_isIssueToFactory: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.isIssueToFactory
              ? data.inventoryDetails.data.isIssueToFactory
              : false
            : false
          : false,
        inv_isIssueToMerchandise: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.isIssueToMerchandise
              ? data.inventoryDetails.data.isIssueToMerchandise
              : false
            : false
          : false,
        inv_isIssueToOtherBoutique: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.isIssueToOtherBoutique
              ? data.inventoryDetails.data.isIssueToOtherBoutique
              : false
            : false
          : false,
        inv_isIssueToTEP: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.isIssueToTEP
              ? data.inventoryDetails.data.isIssueToTEP
              : false
            : false
          : false,
        inv_isIssueToGEP: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.isIssueToGEP
              ? data.inventoryDetails.data.isIssueToGEP
              : false
            : false
          : false,
        inv_isIssueDefective: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.isIssueDefective
              ? data.inventoryDetails.data.isIssueDefective
              : false
            : false
          : false,
        inv_isIssueOthers: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.isIssueOthers
              ? data.inventoryDetails.data.isIssueOthers
              : false
            : false
          : false,
        inv_maximumNoOfDaysForPhysicalReceiptDate: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.maximumNoOfDaysForPhysicalReceiptDate
              ? data.inventoryDetails.data.maximumNoOfDaysForPhysicalReceiptDate
              : ''
            : ''
          : '',
        inv_maximumNoOfDaysForSTNCancellation: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.maximumNoOfDaysForSTNCancellation
              ? data.inventoryDetails.data.maximumNoOfDaysForSTNCancellation
              : ''
            : ''
          : '',
        inv_isSTNcancellationAllowed: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.isSTNcancellationAllowed
              ? data.inventoryDetails.data.isSTNcancellationAllowed
              : false
            : false
          : false,
        inv_isConversionRestricted: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.isConversionRestricted
              ? data.inventoryDetails.data.isConversionRestricted
              : false
            : false
          : false,
        inv_isStuddedSplitAllowed: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.isStuddedSplitAllowed
              ? data.inventoryDetails.data.isStuddedSplitAllowed
              : false
            : false
          : false,
        inv_sparewtToleranceforStockItem: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.sparewtToleranceforStockItem
              ? data.inventoryDetails.data.sparewtToleranceforStockItem
              : ''
            : ''
          : '',
        inv_servicewtToleranceforStockItem: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.servicewtToleranceforStockItem
              ? data.inventoryDetails.data.servicewtToleranceforStockItem
              : ''
            : ''
          : '',

        inv_conversionwtToleranceforBangle: data.inventoryDetails
          ? data.inventoryDetails.data
            ? data.inventoryDetails.data.conversionwtToleranceforBangle
              ? data.inventoryDetails.data.conversionwtToleranceforBangle
              : ''
            : ''
          : '',

        banking_isBankingMandatory: data.bankingDetails
          ? data.bankingDetails.data
            ? data.bankingDetails.data.isBankingMandatory
              ? data.bankingDetails.data.isBankingMandatory
              : false
            : false
          : false,
        banking_isPasswordMandatory: data.bankingDetails
          ? data.bankingDetails.data
            ? data.bankingDetails.data.isPasswordMandatory
              ? data.bankingDetails.data.isPasswordMandatory
              : false
            : false
          : false,
        banking_enableCashDeposit: data.bankingDetails
          ? data.bankingDetails.data
            ? data.bankingDetails.data.enableCashDeposit
              ? data.bankingDetails.data.enableCashDeposit
              : false
            : false
          : false,
        banking_enableChequeDeposit: data.bankingDetails
          ? data.bankingDetails.data
            ? data.bankingDetails.data.enableChequeDeposit
              ? data.bankingDetails.data.enableChequeDeposit
              : false
            : false
          : false,
        banking_remarksForPassword: data.bankingDetails
          ? data.bankingDetails.data
            ? data.bankingDetails.data.remarksForPassword
              ? data.bankingDetails.data.remarksForPassword
              : null
            : null
          : null,
        banking_sapCode: data.bankingDetails
          ? data.bankingDetails.data
            ? data.bankingDetails.data.sapCode
              ? data.bankingDetails.data.sapCode
              : ''
            : ''
          : '',
        banking_paymentMode: data.bankingDetails
          ? data.bankingDetails.data
            ? data.bankingDetails.data.paymentMode
              ? data.bankingDetails.data.paymentMode
              : ''
            : ''
          : '',

        otp_isOTPallowedASSM: data.otpDetails
          ? data.otpDetails.data
            ? data.otpDetails.data.isOTPallowedASSM
              ? data.otpDetails.data.isOTPallowedASSM
              : false
            : false
          : false,
        otp_isOTPallowedCM: data.otpDetails
          ? data.otpDetails.data
            ? data.otpDetails.data.isOTPallowedCM
              ? data.otpDetails.data.isOTPallowedCM
              : false
            : false
          : false,
        otp_isOTPallowedAdvance: data.otpDetails
          ? data.otpDetails.data
            ? data.otpDetails.data.isOTPallowedAdvance
              ? data.otpDetails.data.isOTPallowedAdvance
              : false
            : false
          : false,
        otp_isOTPallowedAB: data.otpDetails
          ? data.otpDetails.data
            ? data.otpDetails.data.isOTPallowedAB
              ? data.otpDetails.data.isOTPallowedAB
              : false
            : false
          : false,
        otp_isOTPallowedGHS: data.otpDetails
          ? data.otpDetails.data
            ? data.otpDetails.data.isOTPallowedGHS
              ? data.otpDetails.data.isOTPallowedGHS
              : false
            : false
          : false,
        otp_isOTPallowedCO: data.otpDetails
          ? data.otpDetails.data
            ? data.otpDetails.data.isOTPallowedCO
              ? data.otpDetails.data.isOTPallowedCO
              : false
            : false
          : false,
        otp_isOTPrequiredforGHSRedemption: data.otpDetails
          ? data.otpDetails.data
            ? data.otpDetails.data.isOTPrequiredforGHSRedemption
              ? data.otpDetails.data.isOTPrequiredforGHSRedemption
              : false
            : false
          : false,
        otp_isOTPrequiredforGC: data.otpDetails
          ? data.otpDetails.data
            ? data.otpDetails.data.isOTPrequiredforGC
              ? data.otpDetails.data.isOTPrequiredforGC
              : false
            : false
          : false,
        otp_otpHelpDeskEmailId: data.otpDetails
          ? data.otpDetails.data
            ? data.otpDetails.data.otpHelpDeskEmailId
              ? data.otpDetails.data.otpHelpDeskEmailId
              : ''
            : ''
          : '',

        customer_isDownloadDocumentAllowed: data.customerDetails
          ? data.customerDetails.data
            ? data.customerDetails.data.isDownloadDocumentAllowed
              ? data.customerDetails.data.isDownloadDocumentAllowed
              : false
            : false
          : false,
        customer_isUploadDocumentAllowed: data.customerDetails
          ? data.customerDetails.data
            ? data.customerDetails.data.isUploadDocumentAllowed
              ? data.customerDetails.data.isUploadDocumentAllowed
              : false
            : false
          : false,
        customer_isDocumentDisplayForCC: data.customerDetails
          ? data.customerDetails.data
            ? data.customerDetails.data.isDocumentDisplayForCC
              ? data.customerDetails.data.isDocumentDisplayForCC
              : false
            : false
          : false,
        customer_isMobileNoForOneTimeCustomer: data.customerDetails
          ? data.customerDetails.data
            ? data.customerDetails.data.isMobileNoForOneTimeCustomer
              ? data.customerDetails.data.isMobileNoForOneTimeCustomer
              : false
            : false
          : false,
        customer_isEmailForOneTimeCustomer: data.customerDetails
          ? data.customerDetails.data
            ? data.customerDetails.data.isEmailForOneTimeCustomer
              ? data.customerDetails.data.isEmailForOneTimeCustomer
              : false
            : false
          : false,
        customer_isEmailForEncircleCustomer: data.customerDetails
          ? data.customerDetails.data
            ? data.customerDetails.data.isEmailForEncircleCustomer
              ? data.customerDetails.data.isEmailForEncircleCustomer
              : false
            : false
          : false,
        customer_isEmailForInternationalCustomer: data.customerDetails
          ? data.customerDetails.data
            ? data.customerDetails.data.isEmailForInternationalCustomer
              ? data.customerDetails.data.isEmailForInternationalCustomer
              : false
            : false
          : false,
        customer_isEmailForInstitutionalCustomer: data.customerDetails
          ? data.customerDetails.data
            ? data.customerDetails.data.isEmailForInstitutionalCustomer
              ? data.customerDetails.data.isEmailForInstitutionalCustomer
              : false
            : false
          : false,
        customer_isMobileNoForInstitutionalCustomer: data.customerDetails
          ? data.customerDetails.data
            ? data.customerDetails.data.isMobileNoForInstitutionalCustomer
              ? data.customerDetails.data.isMobileNoForInstitutionalCustomer
              : false
            : false
          : false,
        customer_isMobileNoForInternationalCustomer: data.customerDetails
          ? data.customerDetails.data
            ? data.customerDetails.data.isMobileNoForInternationalCustomer
              ? data.customerDetails.data.isMobileNoForInternationalCustomer
              : false
            : false
          : false,

        digigold_digiGoldDiscountPercent: data.digigoldDetails
          ? data.digigoldDetails.data
            ? data.digigoldDetails.data.digiGoldDiscountPercent
              ? data.digigoldDetails.data.digiGoldDiscountPercent
              : ''
            : ''
          : '',
        digigold_isCNCancelAllowedForDigiGold: data.digigoldDetails
          ? data.digigoldDetails.data
            ? data.digigoldDetails.data.isCNCancelAllowedForDigiGold
              ? data.digigoldDetails.data.isCNCancelAllowedForDigiGold
              : false
            : false
          : false,
        digigold_isCNCancelAllowedForNonDigiGold: data.digigoldDetails
          ? data.digigoldDetails.data
            ? data.digigoldDetails.data.isCNCancelAllowedForNonDigiGold
              ? data.digigoldDetails.data.isCNCancelAllowedForNonDigiGold
              : false
            : false
          : false,
        digigold_isCNPartialRedemptionAllowedForDigiGold: data.digigoldDetails
          ? data.digigoldDetails.data
            ? data.digigoldDetails.data.isCNPartialRedemptionAllowedForDigiGold
              ? data.digigoldDetails.data
                  .isCNPartialRedemptionAllowedForDigiGold
              : false
            : false
          : false,
        digigold_isCNTransferAllowedForDigiGold: data.digigoldDetails
          ? data.digigoldDetails.data
            ? data.digigoldDetails.data.isCNTransferAllowedForDigiGold
              ? data.digigoldDetails.data.isCNTransferAllowedForDigiGold
              : false
            : false
          : false,
        digigold_isCNTransferAllowedForNonDigiGold: data.digigoldDetails
          ? data.digigoldDetails.data
            ? data.digigoldDetails.data.isCNTransferAllowedForNonDigiGold
              ? data.digigoldDetails.data.isCNTransferAllowedForNonDigiGold
              : false
            : false
          : false,

        payment_chequeValidityDays: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.chequeValidityDays
              ? data.paymentDetails.data.chequeValidityDays
              : ''
            : ''
          : '',
        payment_ddValidityDays: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.ddValidityDays
              ? data.paymentDetails.data.ddValidityDays
              : ''
            : ''
          : '',
        payment_realisationDays: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.realisationDays
              ? data.paymentDetails.data.realisationDays
              : ''
            : ''
          : '',
        payment_isUlpAllowed: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.isUlpAllowed
              ? data.paymentDetails.data.isUlpAllowed
              : false
            : false
          : false,
        payment_enableCNTarnsferForGVpayment: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.enableCNTarnsferForGVpayment
              ? data.paymentDetails.data.enableCNTarnsferForGVpayment
              : false
            : false
          : false,
        payment_enableCNCancellationForGVPayment: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.enableCNCancellationForGVPayment
              ? data.paymentDetails.data.enableCNCancellationForGVPayment
              : false
            : false
          : false,
        payment_isMultipleGVAllowed: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.isMultipleGVAllowed
              ? data.paymentDetails.data.isMultipleGVAllowed
              : false
            : false
          : false,
        payment_pendingRORequestDeletion: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.pendingRORequestDeletion
              ? data.paymentDetails.data.pendingRORequestDeletion
              : ''
            : ''
          : '',
        payment_approvedRORequestDeletion: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.approvedRORequestDeletion
              ? data.paymentDetails.data.approvedRORequestDeletion
              : ''
            : ''
          : '',
        payment_enableRtgsPayment: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.rtgs
              ? data.paymentDetails.data.rtgs.enableRtgsPayment
                ? data.paymentDetails.data.rtgs.enableRtgsPayment
                : false
              : false
            : false
          : false,
        payment_isRRNumberValidation: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.rtgs
              ? data.paymentDetails.data.rtgs.isRRNumberValidation
                ? data.paymentDetails.data.rtgs.isRRNumberValidation
                : false
              : false
            : false
          : false,
        payment_maximumAmount: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.rtgs
              ? data.paymentDetails.data.rtgs.maximumAmount
                ? data.paymentDetails.data.rtgs.maximumAmount
                : null
              : null
            : null
          : null,
        payment_minimumAmount: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.rtgs
              ? data.paymentDetails.data.rtgs.minimumAmount
                ? data.paymentDetails.data.rtgs.minimumAmount
                : null
              : null
            : null
          : null,
        payment_noOfDaysForChequeOrDDAcceptance: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.rtgs
              ? data.paymentDetails.data.rtgs.noOfDaysForChequeOrDDAcceptance
                ? data.paymentDetails.data.rtgs.noOfDaysForChequeOrDDAcceptance
                : ''
              : ''
            : ''
          : '',
        payment_isEnableUnipayForIntegration: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.rtgs
              ? data.paymentDetails.data.rtgs.isEnableUnipayForIntegration
                ? data.paymentDetails.data.rtgs.isEnableUnipayForIntegration
                : false
              : false
            : false
          : false,
        payment_isROApprovedByWorkflow: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.rtgs
              ? data.paymentDetails.data.rtgs.isROApprovedByWorkflow
                ? data.paymentDetails.data.rtgs.isROApprovedByWorkflow
                : false
              : false
            : false
          : false,
        payment_isEnableAirpayForIntegration: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.rtgs
              ? data.paymentDetails.data.rtgs.isEnableAirpayForIntegration
                ? data.paymentDetails.data.rtgs.isEnableAirpayForIntegration
                : false
              : false
            : false
          : false,
        payment_isEnableRazorpayForIntegration: data.paymentDetails
          ? data.paymentDetails.data
            ? data.paymentDetails.data.isRazorPayEnabled
              ? data.paymentDetails.data.isRazorPayEnabled
              : false
            : false
          : false,
        offer_maxWeightforFOC: data.offerDetails
          ? data.offerDetails.data
            ? data.offerDetails.data.maxWeightforFOC
              ? data.offerDetails.data.maxWeightforFOC
              : ''
            : ''
          : '',
        offer_maxValueforFOC: data.offerDetails
          ? data.offerDetails.data
            ? data.offerDetails.data.maxValueforFOC
              ? data.offerDetails.data.maxValueforFOC
              : ''
            : ''
          : '',
        offer_bintobintransferallowedforFOCitems: data.offerDetails
          ? data.offerDetails.data
            ? data.offerDetails.data.bintobintransferallowedforFOCitems
              ? data.offerDetails.data.bintobintransferallowedforFOCitems
              : false
            : false
          : false,
        offer_isTEPsaleableitemsallowedforFOC: data.offerDetails
          ? data.offerDetails.data
            ? data.offerDetails.data.isTEPsaleableitemsallowedforFOC
              ? data.offerDetails.data.isTEPsaleableitemsallowedforFOC
              : false
            : false
          : false,
        offer_isTEPallowedforFOCitems: data.offerDetails
          ? data.offerDetails.data
            ? data.offerDetails.data.isTEPallowedforFOCitems
              ? data.offerDetails.data.isTEPallowedforFOCitems
              : false
            : false
          : false,
        offer_isFOCitemssaleable: data.offerDetails
          ? data.offerDetails.data
            ? data.offerDetails.data.isFOCitemssaleable
              ? data.offerDetails.data.isFOCitemssaleable
              : false
            : false
          : false,
        offer_isEmployeeDiscount: data.offerDetails
          ? data.offerDetails.data
            ? data.offerDetails.data.isEmployeeDiscount
              ? data.offerDetails.data.isEmployeeDiscount
              : false
            : false
          : false,

        global_locationCode: data.locationCode ? data.locationCode : '',
        global_description: data.description ? data.description : '',
        global_fax: data.fax ? data.fax : '',
        global_locationTypeCode: data.locationTypeCode
          ? data.locationTypeCode
          : '',
        global_townId: data.townId ? data.townId : '',
        global_stateId: data.stateId ? data.stateId : '',
        global_regionCode: data.regionCode ? data.regionCode : '',
        global_ownerTypeCode: data.ownerTypeCode ? data.ownerTypeCode : '',
        global_factoryCodeValue: data.factoryCodeValue
          ? data.factoryCodeValue
          : '',
        global_locationFormat: data.locationFormat ? data.locationFormat : '',
        global_brandCode: data.brandCode ? data.brandCode : null,
        global_isActive: data.isActive ? data.isActive : false,
        global_cfaCodeValue: data.cfaCodeValue ? data.cfaCodeValue : '',
        global_stockCurrency: data.stockCurrency ? data.stockCurrency : '',
        global_masterCurrency: data.masterCurrency ? data.masterCurrency : '',
        global_paymentCurrencies: data.paymentCurrencies
          ? data.paymentCurrencies
          : '',
        global_marketCode: data.marketCode ? data.marketCode : '',
        global_subRegionCode: data.subRegionCode ? data.subRegionCode : '',
        global_subBrandCode: data.subBrandCode ? data.subBrandCode : '',

        tep_tepHoldTime: data.tepDetails
          ? data.tepDetails.data
            ? data.tepDetails.data.tepHoldTime
              ? data.tepDetails.data.tepHoldTime
              : ''
            : ''
          : '',

        isEncirclePaymentAllowed: true,
        isPanCardVerifyIntegration: data?.storeDetails?.data
          ?.isPanCardVerifyIntegrationEnabled
          ? data?.storeDetails?.data?.isPanCardVerifyIntegrationEnabled
          : false,
        service_isServiceMandatory: data.serviceDetails
          ? data.serviceDetails.data
            ? data.serviceDetails.data.isServiceMandatory
              ? data.serviceDetails.data.isServiceMandatory
              : false
            : false
          : false,
      };
    } else {
      locationSettingsResponse = {
        factory_locationCode: '',
        factory_brandCode: '',
        factory_townId: '',
        factory_townName: '',
        factory_stateId: '',
        factory_stateName: '',
        factory_regionCode: '',
        factory_locationTypeCode: '',
        factory_locationFormat: '',
        factory_isActive: null,
        factory_description: '',
        factory_marketCode: '',
        factory_countryCode: '',
        factory_ownerTypeCode: '',
        factory_factoryCodeValue: '',
        factory_fax: '',
        factory_cfaCodeValue: '',
        factory_subRegionCode: '',
        factory_subBrandCode: '',
        factory_remarks: null,
        factory_baseCurrency: '',
        factory_stockCurrency: '',
        factory_masterCurrency: '',
        factory_paymentCurrencies: '',

        cfa_locationCode: '',
        cfa_brandCode: '',
        cfa_townId: '',
        cfa_townName: '',
        cfa_stateId: '',
        cfa_stateName: '',
        cfa_regionCode: '',
        cfa_locationTypeCode: '',
        cfa_locationFormat: '',
        cfa_isActive: null,
        cfa_description: '',
        cfa_marketCode: '',
        cfa_countryCode: '',
        cfa_ownerTypeCode: '',
        cfa_factoryCodeValue: null,
        cfa_fax: '',
        cfa_cfaCodeValue: null,
        cfa_subRegionCode: '',
        cfa_subBrandCode: '',
        cfa_remarks: '',
        cfa_baseCurrency: '',
        cfa_stockCurrency: '',
        cfa_masterCurrency: '',
        cfa_paymentCurrencies: '',

        country_countryCode: '',
        country_description: '',
        country_isActive: null,
        country_currencyCode: '',
        country_dateFormat: '',
        country_locale: '',
        country_phoneLength: null,
        country_fiscalYear: null,
        country_timeFormat: '',
        country_isdCode: '',
        country_fiscalYearEnd: '',
        country_fiscalYearStart: '',
        country_lastModifiedDate: null,
        country_weightUnit: '',
        country_stoneWeightUnit: '',

        baseCurrency_currencyCode: '',
        baseCurrency_currencySymbol: '',
        baseCurrency_description: '',
        baseCurrency_unicode: '',
        baseCurrency_isActive: null,
        baseCurrency_lastModifiedDate: null,

        store_companyName: '',
        store_addressLines: null,
        store_phoneNumber1: '',
        store_phoneNumber2: '',
        store_contactNumber: '',
        store_corporateAddress: '',
        store_cinNumber: '',
        store_isWalkInsDetailsMandatory: null,
        store_pincode: '',
        store_boutiqueEmailId: '',
        store_noOfDays: null,
        store_numberOfDaysToDisplay: null,
        store_regdOffice: '',
        store_maxRateRetryAttempt: null,
        store_isDial: null,

        print_freeTextForGrams: '',
        print_noOfInvoicecopiesforRegularOrQuickCM: '',
        print_invoiceType: '',
        print_mcOrWastageExpense: '',
        print_printWastageComponent: null,
        print_printWastagePercent: null,
        print_printWastageCharge: null,
        print_printStoneValue: null,
        print_printGoldValue: null,
        print_printPrice: null,
        print_isMCAndWastage: null,
        print_isDisplayWastagePercent: null,
        print_isVariablePrice: null,
        print_printMakingCharges: null,
        print_printCustomerNumberinReport: null,
        print_printCashMemo: null,
        print_printGuaranteeCard: null,
        print_printOtherStoneWtinGuaranteeCard: null,
        print_printOtherStoneWeightinAnnexure: null,
        print_printImage: null,

        cn_suspendingCNs: '',
        cn_transferredCNs: '',
        cn_activatedCNs: '',
        cn_maxNoOfCN: '',
        cn_otpForMinCN: '',
        cn_maxNoOfTimesCNinEGHS: '',
        cn_isEmployeeLoanCNCancel: null,
        cn_isEmployeeLoanCNTransfer: null,
        cn_isUploadMandatoryforThirdPartyCNWithoutOTP: null,

        tax_isGST: null,
        tax_gstRegisterationNo: '',
        tax_gstValidFrom: '',
        tax_gstPrintValidFrom: '',

        cm_isBillCancelApprovalRequired: null,
        cm_maxNoOfHoursForBillCancel: '',
        cm_isTitle: null,
        cm_isMobileAndEmailMandatoryForCorrection: null,
        cm_isEditWeightAllowed: null,
        cm_isMobileAndEmail: null,
        cm_cmHoldTimeInMinutes: '',
        cm_noOfHoursForOpenTaskDeletionCM: '',

        grn_noOfDaysGRNAllowed: '',
        grn_maximumNoOfDaysForApprovedGRN: '',
        grn_noOfDaysToProtectGoldRateForGRN: '',
        grn_minUtilizationPercentForGRN: '',
        grn_isInterBoutiqueGRNAllowed: null,
        grn_isGRNAllowedInCM: null,
        grn_isGrnAllowedInAdvanceBooking: null,

        grf_minimumUtilization: '',
        grf_isGRFAllowed: null,
        grf_isGRFAllowedInCM: null,
        grf_isGRFAllowedInAdvanceBooking: null,
        grf_isGRFAllowedInCustomerOrder: null,
        grf_isMergeCNAllowed: null,
        grf_currentOwner: null,
        grf_thirdPerson: null,

        gep_enableGEPSale: null,
        gep_gepPureGoldPurity: '',
        gep_gepPurePlatinumPurity: '',
        gep_gepPureSilverPurity: '',
        gep_gepStandardDeductionGold: '',
        gep_gepStandardDeductionPlatinum: '',
        gep_gepStandardDeductionSilver: '',
        gep_noOfDaysGepCancel: '',
        gep_karatAcceptedForGEP: '',
        gep_isPreMeltingDetailsMandatory: null,
        gep_gepHoldTime: '',

        gc_maximumAmount: '',
        gc_minimumAmount: '',
        gc_multiplesValue: '',
        gc_isCardCancellationAllowed: null,
        gc_isCardInwardingAllowed: null,
        gc_isCardActivationAllowed: null,

        ab_cancellationAllowedforAdvanceBooking: null,
        ab_activateAllowedforAdvanceBooking: null,
        ab_requestApprovalForNonFrozenOrderCancel: null,
        ab_validityDaysforAutoClosureInAdvanceBooking: '',
        ab_validityDaysforActivateInAdvanceBooking: '',
        ab_validityDaysforReleaseInvInAdvancebooking: '',
        ab_minPercentToBePaidForFrozenOrder: '',
        ab_minPercentToBePaidForNonFrozenOrder: '',
        ab_abHoldTime: '',
        ab_noOfHoursForOpenTaskDeletion: '',

        co_cancellationAllowedforCustomerOrder: null,
        co_activateAllowedforCustomerOrder: null,
        co_validityDaysforAutoClosureInCustomerOrder: '',
        co_validitydaysforReleaseInvInCustomerOrder: '',
        co_maxNoofdaysforPOLikelyDate: '',

        ghs_grammageCNTransfer: null,
        ghs_isConsentLetterUploadMandatory: null,
        ghs_isClubbingGHSAccRestricted: null,
        ghs_isEghsMandatory: null,
        ghs_isOtpRequired: null,
        ghs_noOfDaysForSuspendingGhs: '',
        ghs_consolidateAttempts: '',
        ghs_gracePeriodAfterSuspenededGhs: '',
        ghs_isGHSRedemptionAllowed: null,
        ghs_isUploadMandatoryforGHSWithoutOTP: null,

        inv_isIssueToFactory: null,
        inv_isIssueToMerchandise: null,
        inv_isIssueToOtherBoutique: null,
        inv_isIssueToTEP: null,
        inv_isIssueToGEP: null,
        inv_isIssueDefective: null,
        inv_isIssueOthers: null,
        inv_maximumNoOfDaysForPhysicalReceiptDate: '',
        inv_maximumNoOfDaysForSTNCancellation: '',
        inv_isConversionRestricted: null,
        inv_isSTNcancellationAllowed: null,
        inv_isStuddedSplitAllowed: null,
        inv_sparewtToleranceforStockItem: '',
        inv_servicewtToleranceforStockItem: '',
        inv_conversionwtToleranceforBangle: '',

        banking_isBankingMandatory: null,
        banking_isPasswordMandatory: null,
        banking_enableCashDeposit: null,
        banking_enableChequeDeposit: null,
        banking_remarksForPassword: null,
        banking_sapCode: '',
        banking_paymentMode: '',

        otp_isOTPallowedASSM: null,
        otp_isOTPallowedCM: null,
        otp_isOTPallowedAdvance: null,
        otp_isOTPallowedAB: null,
        otp_isOTPallowedGHS: null,
        otp_isOTPallowedCO: null,
        otp_isOTPrequiredforGC: null,
        otp_isOTPrequiredforGHSRedemption: null,
        otp_otpHelpDeskEmailId: '',

        customer_isUploadDocumentAllowed: null,
        customer_isDownloadDocumentAllowed: null,
        customer_isDocumentDisplayForCC: null,
        customer_isEmailForEncircleCustomer: null,
        customer_isMobileNoForOneTimeCustomer: null,
        customer_isEmailForOneTimeCustomer: null,
        customer_isMobileNoForInstitutionalCustomer: null,
        customer_isEmailForInstitutionalCustomer: null,
        customer_isMobileNoForInternationalCustomer: null,
        customer_isEmailForInternationalCustomer: null,

        digigold_digiGoldDiscountPercent: '',
        digigold_isCNCancelAllowedForDigiGold: null,
        digigold_isCNCancelAllowedForNonDigiGold: null,
        digigold_isCNPartialRedemptionAllowedForDigiGold: null,
        digigold_isCNTransferAllowedForDigiGold: null,
        digigold_isCNTransferAllowedForNonDigiGold: null,

        payment_chequeValidityDays: '',
        payment_ddValidityDays: '',
        payment_realisationDays: '',
        payment_isUlpAllowed: null,
        payment_enableCNCancellationForGVPayment: null,
        payment_enableCNTarnsferForGVpayment: null,
        payment_isMultipleGVAllowed: null,
        payment_approvedRORequestDeletion: '',
        payment_pendingRORequestDeletion: '',
        payment_enableRtgsPayment: null,
        payment_isRRNumberValidation: null,
        payment_maximumAmount: '',
        payment_minimumAmount: '',
        payment_noOfDaysForChequeOrDDAcceptance: '',
        payment_isROApprovedByWorkflow: null,
        payment_isEnableAirpayForIntegration: null,
        payment_isEnableUnipayForIntegration: null,
        payment_isEnableRazorpayForIntegration: null,

        offer_maxWeightforFOC: '',
        offer_maxValueforFOC: '',
        offer_bintobintransferallowedforFOCitems: null,
        offer_isTEPsaleableitemsallowedforFOC: null,
        offer_isTEPallowedforFOCitems: null,
        offer_isFOCitemssaleable: null,
        offer_isEmployeeDiscount: null,

        global_locationCode: '',
        global_description: '',
        global_fax: null,
        global_locationTypeCode: '',
        global_townId: '',
        global_stateId: '',
        global_regionCode: '',
        global_ownerTypeCode: '',
        global_factoryCodeValue: '',
        global_locationFormat: '',
        global_brandCode: null,
        global_isActive: null,
        global_cfaCodeValue: '',
        global_stockCurrency: '',
        global_masterCurrency: '',
        global_paymentCurrencies: '',
        global_marketCode: '',
        global_subRegionCode: '',
        global_subBrandCode: '',

        tep_tepHoldTime: '',

        isEncirclePaymentAllowed: null,
        isPanCardVerifyIntegration: false,

        service_isServiceMandatory: null,
      };
    }

    return locationSettingsResponse;
  }
}
