// Generated by https://quicktype.io

export interface LocationMasterDetails {
    description: string;
    fax: string;
    locationTypeCode: string;
    townId: string;
    stateId: string;
    countryCode: string;
    regionCode: string;
    ownerTypeCode: string;
    factoryCodeValue: string;
    cfaCodeValue: null;
    locationFormat: string;
    brandCode: string;
    isActive: boolean;
    marketCode: string;
    subRegionCode: string;
    subBrandCode: string;
    remarks: string;
    baseCurrency: string;
    stockCurrency: string;
    masterCurrency: string;
    paymentCurrencies: string;
    storeDetails: StoreDetails;
    printDetails: PrintDetails;
    cnDetails: CNDetails;
    taxDetails: TaxDetails;
    cmDetails: CMDetails;
    grnDetails: GrnDetails;
    grfDetails: GrfDetails;
    gepDetails: GepDetails;
    gcDetails: GcDetails;
    abDetails: AbDetails;
    coDetails: CoDetails;
    ghsDetails: GhsDetails;
    inventoryDetails: InventoryDetails;
    bankingDetails: BankingDetails;
    otpDetails: OtpDetails;
    customerDetails: CustomerDetails;
    paymentDetails: PaymentDetails;
    offerDetails: OfferDetails;
    locationCode: string;
}

export interface AbDetails {
    type: string;
    data: AbDetailsData;
}

export interface AbDetailsData {
    cancellationAllowedforAdvanceBooking: string;
    activateAllowedforAdvanceBooking: string;
    validityDaysforAutoClosureInAdvanceBooking: number;
    validityDaysforActivateInAdvanceBooking: number;
    validityDaysforReleaseInvInAdvancebooking: number;
}

export interface BankingDetails {
    type: string;
    data: BankingDetailsData;
}

export interface BankingDetailsData {
    isBankingMandatory: boolean;
    isPasswordMandatory: boolean;
    enableCashDeposit: boolean;
    enableChequeDeposit: boolean;
    remarksForPassword: string;
    sapCode: string;
    paymentMode: string;
}

export interface CMDetails {
    type: string;
    data: CMDetailsData;
}

export interface CMDetailsData {
    isBillCancelApprovalRequired: boolean;
    isMobileAndEmail: boolean;
    isEditWeightAllowed: boolean;
    title: string;
    maxNoOfHours: number;
}

export interface CNDetails {
    type: string;
    data: CNDetailsData;
}

export interface CNDetailsData {
    transferredCNs: number;
    activatedCNs: number;
    maxNoOfCN: number;
    otpForMinCN: number;
    maxNoOfTimesCNinEGHS: string;
    isEmployeeLoanCNCancel: boolean;
    isEmployeeLoanCNTransfer: boolean;
}

export interface CoDetails {
    type: string;
    data: CoDetailsData;
}

export interface CoDetailsData {
    cancellationAllowedforCustomerOrder: boolean;
    activateAllowedforCustomerOrder: boolean;
    validityDaysforAutoClosureInCustomerOrder: number;
    validitydaysforReleaseInvInCustomerOrder: number;
    maxNoofdaysforPOLikelyDate: number;
}

export interface CustomerDetails {
    type: string;
    data: CustomerDetailsData;
}

export interface CustomerDetailsData {
    isDownloadDocumentAllowed: boolean;
    isUploadDocumentAllowed: boolean;
    isDocumentDisplayForCC: boolean;
}

export interface GcDetails {
    type: string;
    data: GcDetailsData;
}

export interface GcDetailsData {
    maximumAmount: number;
    minimumAmount: number;
    multiplesValue: number;
    isCardCancellationAllowed: boolean;
    // isCardInwardingAllowed: boolean;
    isCardActivationAllowed: boolean;
}

export interface GepDetails {
    type: string;
    data: GepDetailsData;
}

export interface GepDetailsData {
    enableGEPSale: boolean;
    gepPureGoldPurity: string;
    gepPurePlatinumPurity: string;
    gepPureSilverPurity: string;
    gepStandardDeductionGold: string;
    gepStandardDeductionPlatinum: string;
    gepStandardDeductionSilver: string;
    noOfDaysGepCancel: number;
}

export interface GhsDetails {
    type: string;
    data: GhsDetailsData;
}

export interface GhsDetailsData {
    isEghsMandatory: boolean;
    isConsentLetterUploadMandatory: boolean;
    isClubbingGHSMandatory: boolean;
    grammageCNTransfer: boolean;
    isOtpRequired: boolean;
    noOfDaysForSuspendingGhs: number;
    consolidateAttempts: number;
    gracePeriodAfterSuspenededGhs: number;
}

export interface GrfDetails {
    type: string;
    data: GrfDetailsData;
}

export interface GrfDetailsData {
    minimumUtilization: string;
    isGRFAllowed: boolean;
    isInterBoutiqueGRNAllowed: boolean;
    isGRFAllowedInCM: boolean;
    isGRFAllowedInAdavnceBooking: boolean;
    isGRFAllowedInCustomerOrder: boolean;
    isMergeCNAllowed: boolean;
    currentOwner: boolean;
    thirdPerson: boolean;
}

export interface GrnDetails {
    type: string;
    data: GrnDetailsData;
}

export interface GrnDetailsData {
    noOfDaysAllowedAfterOfferPeriod: number;
    noOfDaysGRNAllowed: number;
    maximumNoOfDaysForApprovedGRN: number;
    noOfDaysToProtectGoldRateForGRN: number;
    isInterBoutiqueGRNAllowed: boolean;
}

export interface InventoryDetails {
    type: string;
    data: InventoryDetailsData;
}

export interface InventoryDetailsData {
    isIssueToFactory: boolean;
    isIssueToMerchandise: boolean;
    isIssueToOtherBoutique: boolean;
    isIssueToTEP: boolean;
    isIssueToGEP: boolean;
    isIssueDefective: boolean;
    isIssueOthers: boolean;
    maximumNoOfDaysForPhysicalReceiptDate: number;
    maximumNoOfDaysForSTNCancellation: number;
    isSTNcancellationAllowed: boolean;
    isConversionRestricted: boolean;
    isStuddedSplitAllowed: boolean;
    sparewtToleranceforStockItem: number;
    servicewtToleranceforStockItem: number;
}

export interface OfferDetails {
    type: string;
    data: OfferDetailsData;
}

export interface OfferDetailsData {
    maxWeightforFOC: number;
    maxValueforFOC: number;
    bintobintransferallowedforFOCitems: boolean;
    isTEPsaleableitemsallowedforFOC: boolean;
    isTEPallowedforFOCitems: boolean;
    isFOCitemssaleable: boolean;
    isEmployeeDiscount: boolean;
}

export interface OtpDetails {
    type: string;
    data: { [key: string]: boolean };
}

export interface PaymentDetails {
    type: string;
    data: PaymentDetailsData;
}

export interface PaymentDetailsData {
    checkValidityDays: number;
    ddValidityDays: number;
    realisationDays: number;
    isUlpAllowed: boolean;
    enableCNTarnsferForGVpayment: boolean;
    enableCNCancellationForGVPayment: boolean;
    isMultipleGVAllowed: boolean;
    roRequestDeletion: number;
    activeROPayment: number;
    rtgs: Rtgs;
}

export interface Rtgs {
    enableRtgsPayment: boolean;
    isRRNumberValidation: boolean;
    maximumAmount: number;
    minimumAmount: number;
    ddDate: string;
    isEnableUnipayForIntegration: boolean;
    isROApprovedByWorkflow: boolean;
    isEnableAirpayForIntegration: boolean;
}

export interface PrintDetails {
    type: string;
    data: PrintDetailsData;
}

export interface PrintDetailsData {
    mcOrWastageExpense: string;
    freeTextForGrams: string;
    printWastagePercent: boolean;
    printWastageComponent: boolean;
    printWastageCharge: boolean;
    printStoneValue: boolean;
    printGoldValue: boolean;
    isMCAndWastage: boolean;
    isDisplayWastagePercent: boolean;
    isVariablePrice: boolean;
    printMakingCharges: boolean;
    printCustomerNumberinReport: boolean;
    printCashMemo: boolean;
    printGuaranteeCard: boolean;
    printOtherStoneWtinGuaranteeCard: boolean;
    printOtherStoneWeightinAnnexure: boolean;
    noOfInvoicecopiesforRegularOrQuickCM: number;
    invoiceType: string;
    printImage: boolean;
}

export interface StoreDetails {
    type: string;
    data: StoreDetailsData;
}

export interface StoreDetailsData {
    isCMNumber: boolean;
    corporateAddress: string;
    isWalkInsDetailsMandatory: boolean;
    numberOfDaysToDisplay: number;
    noOfDays: number;
    addressLines: Array<null | string>;
    companyName: string;
    companyLocationName: string;
    phoneNumber1: string;
    phoneNumber2: string;
    contactNumber: string;
    pincode: number;
}

export interface TaxDetails {
    type: string;
    data: TaxDetailsData;
}

export interface TaxDetailsData {
    isGST: boolean;
    gstRegisterationNo: string;
    gstValidFrom: string;
    gstPrintValidFrom: string;
}
