export enum CNSearchEnum {
  CN_ACTIVITY = 'cn-activity',
  CN_DETAILS = 'cn-details',
  SENT_REQUESTS = 'sent-requests',
  ACTIVATE_CN = 'activate-cn',
  CANCEL_CN = 'cancel-cn',
  REMOVE_GOLD_RATE = 'remove-gold-rate',
  APPROVED = 'APPROVED',
  PENDING = 'PENDING',
  EGHS_TRANSFER = 'e-GHSTransfer',
  TRANSFER = 'TRANSFER',
  CN_EXISTING = 'CN_EXISTING',
  CN_INWARDING = 'CN_INWARDING',
  CN_OUTWARDING = 'CN_OUTWARDING',
  OPEN = 'OPEN',
  SUSPENDED = 'SUSPENDED'
}
export enum CNStatusEnum {
  APPROVED = 'APPROVED',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  OPEN = 'OPEN',
  ALL = 'ALL',
  TRANSFER_GHS = 'TRANSFER_GHS'
}
export enum CreditNoteAPITypes {
  CREDIT_NOTE_GOLD_RATE_REMOVE = 'CREDIT_NOTE_GOLD_RATE_REMOVE',
  CREDIT_NOTE_ACTIVATE = 'CREDIT_NOTE_ACTIVATE',
  CREDIT_NOTE_CANCELLATION = 'CREDIT_NOTE_CANCELLATION',
  CREDIT_NOTE_TRANSFER = 'CREDIT_NOTE_TRANSFER',
  CN_REFUND_PAYMENT_DETAILS = 'CN_REFUND_PAYMENT_DETAILS'
}
export enum CreditNoteStatusColorsEnum {
  REDEEMED = 'pw-success-color',
  TRANSFER_GHS = 'pw-success-color'
}

export enum CreditNoteType {
  ADV = 'ADV',
  GRN = 'GRN'
}
