//you should simply assert that you get the right state given the provided inputs.

import * as actions from './reports.actions';

import {
  ReportGroupLov,
  LoadAutoReportPayload,
  LoadAutoReportResponse,
  SaveAutoReportPayload,
  AutoReportList,
  PaymentCodeList,
  ReportName,
  ReportRoleSetting,
  ReportField,
  CheckBoxSelectedOption,
  ReportReponse,
  BrandSummary,
  Lov,
  RegionSummary,
  CountrySummary,
  StateSummary,
  TownSummary,
  LocationSummaryList,
  ProductGroup,
  ProductCategory,
  BinGroup,
  BinCode
} from '@poss-web/shared/models';
import { CustomErrorAdaptor } from '@poss-web/shared/util-adaptors';
import { ReportsReducer } from './reports.reducer';

import { ReportsState } from './reports.state';

describe('ReportsReducer reducer Testing Suite', () => {
  const initialState: ReportsState = {
    reportGroups: [],
    reportNames: [],
    reportRoles: [],
    reportFields: [],
    reportSettings: [],
    error: null,
    reports: [],
    brands: [],
    regions: [],
    levels: [],
    countries: [],
    states: [],
    towns: [],
    locations: [],
    productGroups: [],
    productCategories: [],
    isLoading: false,
    binGroups: [],
    binCodes: [],
    generateReportResponse: null,
    totalReports: 0,
    saveReportResponse: null,
    isLoadingReports: false,
    paymentType: [],
    roles: [],
    autoReportList: [],
    searchParameterResponse: null,
    saveSearchResponse: null,
    templateId: null,
    templateName: null,
    cnStatus: null,
    cnType: [],
    karatage: [],
    complexityCode: [],
    rso: [],
    transferTypes: null,
    applicableReportNames: null,
    subBrands: []
  };
  describe('Testing LoadReportGroups ', () => {
    beforeEach(() => {});
    it('Load LoadReportGroups should set the isLoading to true', () => {
      const action = new actions.LoadReportGroups();

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });

    it('LoadReportGroupsSuccess should return report groups', () => {
      const payload: ReportGroupLov[] = [
        {
          code: 'INVENTORY_REPORT',
          value: 'Inventory Report'
        }
      ];

      const action = new actions.LoadReportGroupsSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(false);
      expect(result.reportGroups.length).toBe(1);
    });
    it('LoadReportGroupsFailure should return error', () => {
      const action = new actions.LoadReportGroupsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadAutoReportList Functionality ', () => {
    beforeEach(() => {});
    it('LoadAutoReportList ', () => {
      const payload: LoadAutoReportPayload = {
        pageIndex: 0,
        pageSize: 10
      };
      const action = new actions.LoadAutoReportList(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });
    it('LoadAutoReportListSuccess should return the report auto list', () => {
      const payload: LoadAutoReportResponse = {
        autoReportList: [
          {
            reportDescription: 'stock receive detail',
            reportId: '1',
            cronExpression: '* * * * * *',
            frequency: 'DAILY',
            isAutoGenerated: true,
            id: '1'
          }
        ],
        totalElements: 1
      };
      const action = new actions.LoadAutoReportListSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(false);
      expect(result.autoReportList.length).toBe(1);
    });
    it('LoadAutoReportListFailures should return error', () => {
      const action = new actions.LoadAutoReportListFailures(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing SaveAutoReportSettings ', () => {
    beforeEach(() => {});
    it('SaveAutoReportSettings ', () => {
      const payload: SaveAutoReportPayload = {
        addScheduler: [
          {
            reportId: '1',
            cronExpression: '* * * * * *',
            frequency: 'DAILY'
          }
        ],
        removeScheduler: [],
        updateScheduler: []
      };
      const action = new actions.SaveAutoReportSettings(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });
    it('SaveAutoReportSettingsSuccess should update the isSaved property to true', () => {
      const payload: AutoReportList = {
        reportDescription: 'stock receive detail',
        reportId: '1',
        cronExpression: '* * * * * *',
        frequency: 'DAILY',
        isAutoGenerated: true,
        id: '1'
      };
      const action = new actions.SaveAutoReportSettingsSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.saveReportResponse.isSaved).toBe(true);
      expect(result.isLoading).toBe(false);
    });
    it('SaveAutoReportSettingsFailure should return error', () => {
      const action = new actions.SaveAutoReportSettingsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadRoles ', () => {
    beforeEach(() => {});
    it('LoadRoles ', () => {
      const action = new actions.LoadRoles();

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });
    it('LoadRolesSuccess should update role property ', () => {
      const payload = [
        {
          roleCode: 'Commercial',
          roleName: 'commercial'
        }
      ];
      const action = new actions.LoadRolesSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.roles.length).toBe(1);
      expect(result.isLoading).toBe(false);
    });
    it('LoadRolesFailure should return error', () => {
      const action = new actions.LoadRolesFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadPaymentType ', () => {
    beforeEach(() => {});
    it('LoadPaymentType ', () => {
      const action = new actions.LoadPaymentType();

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });
    it('LoadPaymentTypeSuccess should update paymentType property ', () => {
      const payload: PaymentCodeList[] = [
        {
          paymentCode: 'cash'
        }
      ];
      const action = new actions.LoadPaymentTypeSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.paymentType.length).toBe(1);
      expect(result.isLoading).toBe(false);
    });
    it('LoadPaymentTypeFailure should return error', () => {
      const action = new actions.LoadPaymentTypeFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadReportNames ', () => {
    beforeEach(() => {});
    it('LoadReportNames ', () => {
      const payload = 'INVENTORY_GROUP';
      const action = new actions.LoadReportNames(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });
    it('LoadReportNamesSuccess should update reportNames property ', () => {
      const payload: ReportName[] = [
        {
          reportDes: 'stock receive details',
          reportGroup: 'Inventory Group',
          reportType: 'DETIAL',
          maxNoOfDays: 90,
          name: 'STOCK RECEIVE DETAIL',
          id: '1'
        }
      ];

      const action = new actions.LoadReportNamesSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.reportNames.length).toBe(1);
      expect(result.isLoading).toBe(false);
    });
    it('LoadReportNamesFailure should return error', () => {
      const action = new actions.LoadReportNamesFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadReportRoles ', () => {
    beforeEach(() => {});
    it('LoadReportRoles ', () => {
      const payload = {
        roleCode: 'commercial'
      };
      const action = new actions.LoadReportRoles(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });
    it('LoadReportRolesSuccess should update reportRoles property ', () => {
      const payload: ReportRoleSetting[] = [
        {
          id: '1',
          reportId: '2',
          reportName: 'Stock receive detail',
          fromAccessTime: '10:20',
          toAccessTime: '10:30'
        }
      ];

      const action = new actions.LoadReportRolesSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.reportRoles.length).toBe(1);
      expect(result.isLoading).toBe(false);
    });
    it('LoadReportRolesFailure should return error', () => {
      const action = new actions.LoadReportRolesFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadReportFields ', () => {
    beforeEach(() => {});
    it('LoadReportFields ', () => {
      const payload = '1';
      const action = new actions.LoadReportFields(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });
    it('LoadReportFieldsSuccess should update reportFields property ', () => {
      const payload: ReportField[] = [
        {
          reportFieldId: '1',
          fieldName: 'Location code'
        }
      ];

      const action = new actions.LoadReportFieldsSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.reportFields.length).toBe(1);
      expect(result.isLoading).toBe(false);
    });
    it('LoadReportFieldsFailure should return error', () => {
      const action = new actions.LoadReportFieldsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadReportSettings ', () => {
    beforeEach(() => {});
    it('LoadReportSettings ', () => {
      const payload = {
        roleCode: 'commercial'
      };
      const action = new actions.LoadReportSettings(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });
    it('LoadReportSettingsSuccess should update reportFields property ', () => {
      const payload: CheckBoxSelectedOption[] = [
        {
          id: '1',
          rowHeaderKey: 'Location code',
          columnHeaderKey: 'isExclude'
        }
      ];

      const action = new actions.LoadReportSettingsSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.reportSettings.length).toBe(1);
      expect(result.isLoading).toBe(false);
    });
    it('LoadReportFieldsFailure should return error', () => {
      const action = new actions.LoadReportSettingsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing SaveReportRoleSettings ', () => {
    beforeEach(() => {});
    it('SaveReportRoleSettings ', () => {
      const payload = {
        roleCode: 'commercial',
        request: {
          addAccess: [
            {
              fromAccessTime: '10:05',
              toAccessTime: '11:05',
              reportId: '1'
            }
          ],
          removeAccess: [],
          updateAccess: []
        }
      };
      const action = new actions.SaveReportRoleSettings(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });
    it('SaveReportRoleSettingsSuccess should update isSaved property ', () => {
      const action = new actions.SaveReportRoleSettingsSuccess();

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.saveReportResponse.isSaved).toBe(true);
      expect(result.isLoading).toBe(false);
    });
    it('SaveReportRoleSettingsFailure should return error', () => {
      const action = new actions.SaveReportRoleSettingsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing SaveReportSettings ', () => {
    beforeEach(() => {});
    it('SaveReportSettings ', () => {
      const payload = {
        reportId: '1',
        request: {
          addRoles: [
            {
              reportFieldId: '1',
              isExcluded: true,
              isMasked: true,
              roleCode: 'commercial'
            }
          ],
          removeRoles: []
        }
      };
      const action = new actions.SaveReportSettings(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });
    it('SaveReportSettingsSuccess should update isSaved property ', () => {
      const action = new actions.SaveReportSettingsSuccess();

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.saveReportResponse.isSaved).toBe(true);
      expect(result.isLoading).toBe(false);
    });
    it('SaveReportSettingsFailure should return error', () => {
      const action = new actions.SaveReportSettingsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing GenerateReport ', () => {
    beforeEach(() => {});
    it('GenerateReport ', () => {
      const payload = {
        reportId: '1',
        request: {
          fromDate: '12-03-2021',
          toDate: '16-03-2021',
          locationCode: ['URB'],
          ownerType: ['L1'],
          reportType: 'SUMMARY',
          countryId: '1',
          stateId: '29',
          subBrandCode: ['mia'],
          brandCode: ['mia'],
          subRegionCode: 'east',
          townId: ['1'],
          customFields: {
            data: {}
          }
        }
      };
      const action = new actions.GenerateReport(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });
    it('GenerateReportSuccess should update generateReportResponse property ', () => {
      const payload = '120';
      const action = new actions.GenerateReportSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.generateReportResponse.id).toBe(payload);
      expect(result.isLoading).toBe(false);
    });
    it('GenerateReportFailure should return error', () => {
      const action = new actions.GenerateReportFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing DownloadReport ', () => {
    beforeEach(() => {});
    it('DownloadReport ', () => {
      const payload = { reportId: '1', selectedTab: 0 };
      const action = new actions.DownloadReport(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(true);
    });
    it('DownloadReportSuccess should update isLoading property ', () => {
      const action = new actions.DownloadReportSuccess();

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toBe(false);
    });
    it('DownloadReportFailure should return error', () => {
      const action = new actions.DownloadReportFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadReports ', () => {
    beforeEach(() => {});
    it('LoadReports ', () => {
      const payload = {
        pageSize: 1,
        pageIndex: 10,
        reportDesc: 'STOCK RECEIVE',
        reportGroup: 'INVENTORY ',
        reportStatus: 'completed',
        referenceNumber: '102',
        fromDate: '12-03-2021',
        toDate: '15-03-2021',
        selectedTab: 1
      };
      const action = new actions.LoadReports(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoadingReports).toBe(true);
    });
    it('LoadReportsSuccess should update reports property ', () => {
      const payload: ReportReponse = {
        reports: [
          {
            reportType: 'SUMMARY',
            reportDes: 'STOCK RECEIVE',
            reportMasterId: '1',
            status: 'completed',
            id: '1'
          }
        ],
        totalReports: 1
      };
      const action = new actions.LoadReportsSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoadingReports).toBe(false);

      expect(result.totalReports).toBe(1);

      expect(result.reports.length).toBe(1);
    });
    it('LoadReportsFailure should return error', () => {
      const action = new actions.LoadReportsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadBrands ', () => {
    beforeEach(() => {});

    it('LoadBrandsSuccess should update brands property ', () => {
      const payload: BrandSummary[] = [
        {
          brandCode: 'Tanishq',
          description: 'Tanishq'
        }
      ];
      const action = new actions.LoadBrandsSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.brands.length).toBe(1);
    });
    it('LoadBrandsFailure should return error', () => {
      const action = new actions.LoadBrandsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadLevels ', () => {
    beforeEach(() => {});

    it('LoadLevelsSuccess should update levels property ', () => {
      const payload: Lov[] = [
        {
          code: 'L1',
          value: 'LEVEL 1',
          isActive: true
        }
      ];
      const action = new actions.LoadLevelsSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.levels.length).toBe(1);
    });
    it('LoadLevelsFailure should return error', () => {
      const action = new actions.LoadLevelsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadRegions ', () => {
    beforeEach(() => {});

    it('LoadRegionsSuccess should update regions property ', () => {
      const payload: RegionSummary[] = [
        {
          regionCode: 'EAST',
          description: 'EAST'
        }
      ];
      const action = new actions.LoadRegionsSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.regions.length).toBe(1);
    });
    it('LoadRegionsFailure should return error', () => {
      const action = new actions.LoadRegionsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadCountries ', () => {
    beforeEach(() => {});

    it('LoadCountriesSuccess should update countries property ', () => {
      const payload: CountrySummary[] = [
        {
          countryCode: 'IND',
          description: 'India',
          isdCode: '+91'
        }
      ];
      const action = new actions.LoadCountriesSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.countries.length).toBe(1);
    });
    it('LoadCountriesFailure should return error', () => {
      const action = new actions.LoadCountriesFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadStates ', () => {
    beforeEach(() => {});

    it('LoadStatesSuccess should update states property ', () => {
      const payload: StateSummary[] = [
        {
          stateId: 29,
          description: 'Karanataka'
        }
      ];
      const action = new actions.LoadStatesSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.states.length).toBe(1);
    });
    it('LoadStatesFailure should return error', () => {
      const action = new actions.LoadStatesFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadTowns ', () => {
    beforeEach(() => {});

    it('LoadTownsSuccess should update states property ', () => {
      const payload: TownSummary[] = [
        {
          townCode: 10,
          description: 'Bangalore'
        }
      ];
      const action = new actions.LoadTownsSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.towns.length).toBe(1);
    });
    it('LoadTownsFailure should return error', () => {
      const action = new actions.LoadTownsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadLocations ', () => {
    beforeEach(() => {});

    it('LoadLocationsSuccess should update locations property ', () => {
      const payload: LocationSummaryList[] = [
        {
          locationCode: 'URB',
          description: 'Bangalore'
        }
      ];
      const action = new actions.LoadLocationsSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.locations.length).toBe(1);
    });
    it('LoadLocationsFailure should return error', () => {
      const action = new actions.LoadLocationsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadProductGroups ', () => {
    beforeEach(() => {});

    it('LoadProductGroupsSuccess should update productGroups property ', () => {
      const payload: ProductGroup[] = [
        {
          productGroupCode: '76',
          description: 'GOLD COIN'
        }
      ];
      const action = new actions.LoadProductGroupsSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.productGroups.length).toBe(1);
    });
    it('LoadProductGroupsFailure should return error', () => {
      const action = new actions.LoadProductGroupsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadProductCategories ', () => {
    beforeEach(() => {});

    it('LoadProductCategoriesSuccess should update productCategories property ', () => {
      const payload: ProductCategory[] = [
        {
          productCategoryCode: '76',
          description: 'GOLD COIN',
          isActive: true
        }
      ];
      const action = new actions.LoadProductCategoriesSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.productCategories.length).toBe(1);
    });
    it('LoadProductCategoriesFailure should return error', () => {
      const action = new actions.LoadProductCategoriesFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadBinGroups ', () => {
    beforeEach(() => {});

    it('LoadBinGroupsSuccess should update binGroups property ', () => {
      const payload: BinGroup[] = [
        {
          binGroupCode: '76',
          description: 'DEFECTIVE COIN',
          isActive: true
        }
      ];
      const action = new actions.LoadBinGroupsSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.binGroups.length).toBe(1);
    });
    it('LoadBinGroupsFailure should return error', () => {
      const action = new actions.LoadBinGroupsFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });

  describe('Testing LoadBinCodes ', () => {
    beforeEach(() => {});

    it('LoadBinCodesSuccess should update binCodes property ', () => {
      const payload: BinCode[] = [
        {
          binCode: '76',
          description: 'DEFECTIVE COIN'
        }
      ];
      const action = new actions.LoadBinCodesSuccess(payload);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.binCodes.length).toBe(1);
    });
    it('LoadBinCodesFailure should return error', () => {
      const action = new actions.LoadBinCodesFailure(
        CustomErrorAdaptor.fromJson(Error('some error'))
      );

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.error.message).toEqual('some error');
    });
  });
  describe('Testing ClearReportsData Functionality ', () => {
    beforeEach(() => {});
    it('ClearReportsData', () => {
      const action = new actions.ClearReportsData();

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result).toEqual(initialState);
    });
  });

  describe('Testing LoadSearchParameter Functionality ', () => {
    beforeEach(() => {});
    it('LoadSearchParameter', () => {
      const action = new actions.LoadSearchParameter({} as any);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toEqual(true);
    });
  });

  describe('Testing LoadRsoSuccess Functionality ', () => {
    beforeEach(() => {});
    it('LoadRsoSuccess', () => {
      const action = new actions.LoadRsoSuccess({} as any);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toEqual(false);
    });
  });

  describe('Testing LoadKaratageSuccess Functionality ', () => {
    beforeEach(() => {});
    it('LoadRsoSuccess', () => {
      const action = new actions.LoadKaratageSuccess({} as any);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toEqual(false);
    });
  });

  describe('Testing LoadComplexitySuccess Functionality ', () => {
    beforeEach(() => {});
    it('LoadRsoSuccess', () => {
      const action = new actions.LoadComplexitySuccess({} as any);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toEqual(false);
    });
  });

  describe('Testing LoadCnStatusSuccess Functionality ', () => {
    beforeEach(() => {});
    it('LoadRsoSuccess', () => {
      const action = new actions.LoadCnStatusSuccess({} as any);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toEqual(false);
    });
  });

  describe('Testing LoadCnTypeSuccess Functionality ', () => {
    beforeEach(() => {});
    it('LoadRsoSuccess', () => {
      const action = new actions.LoadCnTypeSuccess({} as any);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toEqual(false);
    });
  });

  describe('Testing UpdateSearchParameter Functionality ', () => {
    beforeEach(() => {});
    it('LoadRsoSuccess', () => {
      const action = new actions.UpdateSearchParameter({} as any);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toEqual(true);
    });
  });

  describe('Testing SaveSearchParameter Functionality ', () => {
    beforeEach(() => {});
    it('SaveSearchParameter', () => {
      const action = new actions.SaveSearchParameter({} as any);

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toEqual(true);
    });
  });

  describe('Testing SaveIndividualSettingSuccess Functionality ', () => {
    beforeEach(() => {});
    it('SaveIndividualSettingSuccess', () => {
      const action = new actions.SaveIndividualSettingSuccess();

      const result: ReportsState = ReportsReducer(initialState, action);

      expect(result.isLoading).toEqual(false);
    });
  });
});
