import { CustomErrorAdaptor } from '@poss-web/shared/util-adaptors';
import {
  CustomErrors,
  ReportGroupLov,
  LoadAutoReportPayload,
  LoadAutoReportResponse,
  SaveAutoReportPayload,
  AutoReportList,
  PaymentCodeList,
  ReportName,
  ReportRoleSetting,
  ReportField,
  CheckBoxSelectedOption,
  ReportReponse,
  BrandSummary,
  Lov,
  RegionSummary,
  CountrySummary,
  StateSummary,
  TownSummary,
  ReportBTQCodePayload,
  LocationSummaryList,
  ProductGroup,
  ProductCategory,
  BinGroup,
  BinCode
} from '@poss-web/shared/models';

import {
  ReportsActionTypes,
  LoadReportGroups,
  LoadReportGroupsSuccess,
  LoadReportGroupsFailure,
  LoadAutoReportList,
  LoadAutoReportListSuccess,
  LoadAutoReportListFailures,
  SaveAutoReportSettings,
  SaveAutoReportSettingsSuccess,
  SaveAutoReportSettingsFailure,
  LoadRoles,
  LoadRolesSuccess,
  LoadRolesFailure,
  LoadPaymentType,
  LoadPaymentTypeSuccess,
  LoadPaymentTypeFailure,
  LoadReportNames,
  LoadReportNamesSuccess,
  LoadReportNamesFailure,
  LoadReportRoles,
  LoadReportRolesSuccess,
  LoadReportRolesFailure,
  LoadReportFields,
  LoadReportFieldsSuccess,
  LoadReportFieldsFailure,
  ClearReportsData,
  LoadReportSettings,
  LoadReportSettingsSuccess,
  LoadReportSettingsFailure,
  SaveReportRoleSettings,
  SaveReportRoleSettingsSuccess,
  SaveReportRoleSettingsFailure,
  SaveReportSettings,
  SaveReportSettingsSuccess,
  SaveReportSettingsFailure,
  GenerateReport,
  GenerateReportSuccess,
  GenerateReportFailure,
  DownloadReport,
  DownloadReportSuccess,
  DownloadReportFailure,
  LoadReports,
  LoadReportsSuccess,
  LoadReportsFailure,
  LoadBrands,
  LoadBrandsSuccess,
  LoadBrandsFailure,
  LoadLevels,
  LoadLevelsSuccess,
  LoadLevelsFailure,
  LoadRegions,
  LoadRegionsSuccess,
  LoadRegionsFailure,
  LoadCountries,
  LoadCountriesSuccess,
  LoadCountriesFailure,
  LoadStates,
  LoadStatesSuccess,
  LoadStatesFailure,
  LoadTowns,
  LoadTownsSuccess,
  LoadTownsFailure,
  LoadLocations,
  LoadLocationsSuccess,
  LoadLocationsFailure,
  LoadProductGroups,
  LoadProductGroupsSuccess,
  LoadProductGroupsFailure,
  LoadProductCategories,
  LoadProductCategoriesSuccess,
  LoadBinGroups,
  LoadBinGroupsSuccess,
  LoadBinGroupsFailure,
  LoadBinCodes,
  LoadBinCodesSuccess,
  LoadBinCodesFailure,
  LoadProductCategoriesFailure,
  LoadSubBrands,
  LoadSubBrandsSuccess,
  LoadSubBrandsFailure,
  LoadTransferTypesFailure,
  LoadTransferTypesSuccess,
  LoadTransferTypes,
  LoadSearchParameterFailure,
  LoadSearchParameterSuccess,
  SaveSearchParameterFailure,
  SaveSearchParameterSuccess,
  LoadCnType,
  LoadCnTypeFailure,
  LoadCnStatus,
  LoadCnStatusFailure,
  SaveIndividualSetting,
  SaveIndividualSettingFailure,
  LoadExcludedIndividualSetting,
  LoadExcludedIndividualSettingSuccess,
  LoadExcludedIndividualSettingFailure,
  UpdateIndividualSetting,
  UpdateIndividualSettingSuccess
} from './reports.actions';

describe('ReportsActions  Action Testing Suite', () => {
  describe('LoadReportGroups Action Test Cases', () => {
    it('should check correct type is used for  LoadReportGroups action ', () => {
      const action = new LoadReportGroups();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_GROUPS
      });
    });
    it('should check correct type is used for  LoadReportGroupsSuccess action ', () => {
      const payload: ReportGroupLov[] = [
        {
          code: 'INVENTORY_REPORT',
          value: 'Inventory Report'
        }
      ];
      const action = new LoadReportGroupsSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_GROUPS_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadReportGroupsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadReportGroupsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_GROUPS_FAILURE,
        payload
      });
    });
  });

  describe('LoadAutoReportList Action Test Cases', () => {
    it('should check correct type is used for  LoadAutoReportList action ', () => {
      const payload: LoadAutoReportPayload = {
        pageIndex: 0,
        pageSize: 10
      };
      const action = new LoadAutoReportList(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_AUTO_REPORT_LIST,
        payload
      });
    });
    it('should check correct type is used for LoadAutoReportListSuccess action ', () => {
      const payload: LoadAutoReportResponse = {
        autoReportList: [
          {
            reportDescription: 'stock receive detail',
            reportId: '1',
            cronExpression: '* * * * * *',
            frequency: 'DAILY',
            isAutoGenerated: true,
            id: '1'
          }
        ],
        totalElements: 1
      };

      const action = new LoadAutoReportListSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_AUTO_REPORT_LIST_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadAutoReportListFailures action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadAutoReportListFailures(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_AUTO_REPORT_LIST_FAILURE,
        payload
      });
    });
  });

  describe('SaveAutoReportSettings Action Test Cases', () => {
    it('should check correct type is used for  SaveAutoReportSettings action ', () => {
      const payload: SaveAutoReportPayload = {
        addScheduler: [
          {
            reportId: '1',
            cronExpression: '* * * * * *',
            frequency: 'DAILY'
          }
        ],
        removeScheduler: [],
        updateScheduler: []
      };
      const action = new SaveAutoReportSettings(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.SAVE_AUTO_REPORT_SETTINGS,
        payload
      });
    });
    it('should check correct type is used for SaveAutoReportSettingsSuccess action ', () => {
      const payload: AutoReportList = {
        reportDescription: 'stock receive detail',
        reportId: '1',
        cronExpression: '* * * * * *',
        frequency: 'DAILY',
        isAutoGenerated: true,
        id: '1'
      };

      const action = new SaveAutoReportSettingsSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.SAVE_AUTO_REPORT_SETTINGS_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  SaveAutoReportSettingsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new SaveAutoReportSettingsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.SAVE_AUTO_REPORT_SETTINGS_FAILURE,
        payload
      });
    });
  });

  describe('LoadRoles Action Test Cases', () => {
    it('should check correct type is used for  LoadRoles action ', () => {
      const action = new LoadRoles();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_ROLES
      });
    });

    it('should check correct type is used for  LoadRolesSuccess action ', () => {
      const payload = [
        {
          roleCode: 'Commercial',
          roleName: 'commercial'
        }
      ];
      const action = new LoadRolesSuccess(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_ROLES_SUCCESS,
        payload
      });
    });

    it('should check correct type is used for  LoadRolesFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadRolesFailure(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_ROLES_FAILURE,
        payload
      });
    });
  });

  describe('LoadPaymentType Action Test Cases', () => {
    it('should check correct type is used for  LoadPaymentType action ', () => {
      const action = new LoadPaymentType();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_PAYMENT_TYPES
      });
    });
    it('should check correct type is used for LoadPaymentTypeSuccess action ', () => {
      const payload: PaymentCodeList[] = [
        {
          paymentCode: 'cash'
        }
      ];
      const action = new LoadPaymentTypeSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_PAYMENT_TYPES_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadPaymentTypeFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadPaymentTypeFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_PAYMENT_TYPES_FAILURE,
        payload
      });
    });
  });

  describe('LoadReportNames Action Test Cases', () => {
    it('should check correct type is used for  LoadReportNames action ', () => {
      const payload = 'INVENTORY_GROUP';
      const action = new LoadReportNames(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_NAMES,
        payload
      });
    });
    it('should check correct type is used for LoadReportNamesSuccess action ', () => {
      const payload: ReportName[] = [
        {
          reportDes: 'stock receive details',
          reportGroup: 'Inventory Group',
          reportType: 'DETIAL',
          maxNoOfDays: 90,
          name: 'STOCK RECEIVE DETAIL',
          id: '1'
        }
      ];

      const action = new LoadReportNamesSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_NAMES_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadReportNamesFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadReportNamesFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_NAMES_FAILURE,
        payload
      });
    });
  });

  describe('LoadReportRoles Action Test Cases', () => {
    it('should check correct type is used for  LoadReportRoles action ', () => {
      const payload = {
        roleCode: 'commercial'
      };
      const action = new LoadReportRoles(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_ROLES,
        payload
      });
    });
    it('should check correct type is used for LoadReportRolesSuccess action ', () => {
      const payload: ReportRoleSetting[] = [
        {
          id: '1',
          reportId: '2',
          reportName: 'Stock receive detail',
          fromAccessTime: '10:20',
          toAccessTime: '10:30'
        }
      ];

      const action = new LoadReportRolesSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_ROLES_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadReportRolesFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadReportRolesFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_ROLES_FAILURE,
        payload
      });
    });
  });

  describe('LoadReportFields Action Test Cases', () => {
    it('should check correct type is used for  LoadReportFields action ', () => {
      const payload = '1';
      const action = new LoadReportFields(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_FIELDS,
        payload
      });
    });
    it('should check correct type is used for LoadReportFieldsSuccess action ', () => {
      const payload: ReportField[] = [
        {
          reportFieldId: '1',
          fieldName: 'Location code'
        }
      ];

      const action = new LoadReportFieldsSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_FIELDS_SUCCESS,

        payload
      });
    });
    it('should check correct type is used for  LoadReportFieldsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadReportFieldsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_FIELDS_FAILURE,
        payload
      });
    });
  });

  describe('LoadReportSettings Action Test Cases', () => {
    it('should check correct type is used for  LoadReportSettings action ', () => {
      const payload = {
        roleCode: 'commercial'
      };
      const action = new LoadReportSettings(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_SETTINGS,
        payload
      });
    });
    it('should check correct type is used for LoadReportSettingsSuccess action ', () => {
      const payload: CheckBoxSelectedOption[] = [
        {
          id: '1',
          rowHeaderKey: 'Location code',
          columnHeaderKey: 'isExclude'
        }
      ];

      const action = new LoadReportSettingsSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_SETTINGS_SUCCESS,

        payload
      });
    });
    it('should check correct type is used for  LoadReportSettingsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadReportSettingsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORT_SETTINGS_FAILURE,
        payload
      });
    });
  });

  describe('SaveReportRoleSettings Action Test Cases', () => {
    it('should check correct type is used for  SaveReportRoleSettings action ', () => {
      const payload = {
        roleCode: 'commercial',
        request: {
          addAccess: [
            {
              fromAccessTime: '10:05',
              toAccessTime: '11:05',
              reportId: '1'
            }
          ],
          removeAccess: [],
          updateAccess: []
        }
      };
      const action = new SaveReportRoleSettings(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.SAVE_REPORT_ROLE_SETTINGS,
        payload
      });
    });
    it('should check correct type is used for SaveReportRoleSettingsSuccess action ', () => {
      const action = new SaveReportRoleSettingsSuccess();

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.SAVE_REPORT_ROLE_SETTINGS_SUCCESS
      });
    });
    it('should check correct type is used for  SaveReportRoleSettingsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new SaveReportRoleSettingsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.SAVE_REPORT_ROLE_SETTINGS_FAILURE,
        payload
      });
    });
  });

  describe('SaveReportSettings Action Test Cases', () => {
    it('should check correct type is used for  SaveReportSettings action ', () => {
      const payload = {
        reportId: '1',
        request: {
          addRoles: [
            {
              reportFieldId: '1',
              isExcluded: true,
              isMasked: true,
              roleCode: 'commercial'
            }
          ],
          removeRoles: []
        }
      };
      const action = new SaveReportSettings(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.SAVE_REPORT_SETTINGS,
        payload
      });
    });
    it('should check correct type is used for SaveReportSettingsSuccess action ', () => {
      const action = new SaveReportSettingsSuccess();

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.SAVE_REPORT_SETTINGS_SUCCESS
      });
    });
    it('should check correct type is used for  SaveReportSettingsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new SaveReportSettingsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.SAVE_REPORT_SETTINGS_FAILURE,
        payload
      });
    });
  });

  describe('GenerateReport Action Test Cases', () => {
    it('should check correct type is used for  GenerateReport action ', () => {
      const payload = {
        reportId: '1',
        request: {
          fromDate: '12-03-2021',
          toDate: '16-03-2021',
          locationCode: ['URB'],
          ownerType: ['L1'],
          reportType: 'SUMMARY',
          countryId: '1',
          stateId: '29',
          subBrandCode: ['mia'],
          brandCode: ['mia'],
          subRegionCode: 'east',
          townId: ['1'],
          customFields: {
            data: {}
          }
        }
      };
      const action = new GenerateReport(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.GENERATE_REPORT,
        payload
      });
    });
    it('should check correct type is used for GenerateReportSuccess action ', () => {
      const payload = '120';
      const action = new GenerateReportSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.GENERATE_REPORT_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  GenerateReportFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new GenerateReportFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.GENERATE_REPORT_FAILURE,
        payload
      });
    });
  });

  describe('DownloadReport Action Test Cases', () => {
    it('should check correct type is used for  DownloadReport action ', () => {
      const payload = { reportId: '1', selectedTab: 0 };
      const action = new DownloadReport(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.DOWNLOAD_REPORT,
        payload
      });
    });
    it('should check correct type is used for DownloadReportSuccess action ', () => {
      const action = new DownloadReportSuccess();

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.DOWNLOAD_REPORT_SUCCESS
      });
    });
    it('should check correct type is used for  GenerateReportFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new DownloadReportFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.DOWNLOAD_REPORT_FAILURE,
        payload
      });
    });
  });

  describe('LoadReports Action Test Cases', () => {
    it('should check correct type is used for  LoadReports action ', () => {
      const payload = {
        pageSize: 1,
        pageIndex: 10,
        reportDesc: 'STOCK RECEIVE',
        reportGroup: 'INVENTORY ',
        reportStatus: 'completed',
        referenceNumber: '102',
        fromDate: '12-03-2021',
        toDate: '15-03-2021',
        selectedTab: 1
      };
      const action = new LoadReports(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORTS,
        payload
      });
    });
    it('should check correct type is used for LoadReportsSuccess action ', () => {
      const payload: ReportReponse = {
        reports: [
          {
            reportType: 'SUMMARY',
            reportDes: 'STOCK RECEIVE',
            reportMasterId: '1',
            status: 'completed',
            id: '1'
          }
        ],
        totalReports: 1
      };
      const action = new LoadReportsSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORTS_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadReportsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadReportsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REPORTS_FAILURE,
        payload
      });
    });
  });

  describe('LoadBrands Action Test Cases', () => {
    it('should check correct type is used for  LoadBrands action ', () => {
      const action = new LoadBrands();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_BRANDS
      });
    });
    it('should check correct type is used for LoadBrandsSuccess action ', () => {
      const payload: BrandSummary[] = [
        {
          brandCode: 'Tanishq',
          description: 'Tanishq'
        }
      ];
      const action = new LoadBrandsSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_BRANDS_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadBrandsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadBrandsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_BRANDS_FAILURE,
        payload
      });
    });
  });

  describe('LoadLevels Action Test Cases', () => {
    it('should check correct type is used for  LoadLevels action ', () => {
      const action = new LoadLevels();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_LEVELS
      });
    });
    it('should check correct type is used for LoadLevelsSuccess action ', () => {
      const payload: Lov[] = [
        {
          code: 'L1',
          value: 'LEVEL 1',
          isActive: true
        }
      ];
      const action = new LoadLevelsSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_LEVELS_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadLevelsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadLevelsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_LEVELS_FAILURE,
        payload
      });
    });
  });

  describe('LoadRegions Action Test Cases', () => {
    it('should check correct type is used for  LoadRegions action ', () => {
      const action = new LoadRegions();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REGIONS
      });
    });
    it('should check correct type is used for LoadRegionsSuccess action ', () => {
      const payload: RegionSummary[] = [
        {
          regionCode: 'EAST',
          description: 'EAST'
        }
      ];
      const action = new LoadRegionsSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REGIONS_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadRegionsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadRegionsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_REGIONS_FAILURE,
        payload
      });
    });
  });

  describe('LoadCountries Action Test Cases', () => {
    it('should check correct type is used for  LoadCountries action ', () => {
      const action = new LoadCountries();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_COUNTRIES
      });
    });
    it('should check correct type is used for LoadCountriesSuccess action ', () => {
      const payload: CountrySummary[] = [
        {
          countryCode: 'IND',
          description: 'India',
          isdCode: '+91'
        }
      ];
      const action = new LoadCountriesSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_COUNTRIES_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadCountriesFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadCountriesFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_COUNTRIES_FAILURE,
        payload
      });
    });
  });

  describe('LoadStates Action Test Cases', () => {
    it('should check correct type is used for  LoadStates action ', () => {
      const payload = 'IND';
      const action = new LoadStates(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_STATES,
        payload
      });
    });
    it('should check correct type is used for LoadStatesSuccess action ', () => {
      const payload: StateSummary[] = [
        {
          stateId: 29,
          description: 'Karanataka'
        }
      ];
      const action = new LoadStatesSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_STATES_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadStatesFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadStatesFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_STATES_FAILURE,
        payload
      });
    });
  });

  describe('LoadTowns Action Test Cases', () => {
    it('should check correct type is used for  LoadTowns action ', () => {
      const payload = '29';
      const action = new LoadTowns(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_TOWNS,
        payload
      });
    });
    it('should check correct type is used for LoadTownsSuccess action ', () => {
      const payload: TownSummary[] = [
        {
          townCode: 10,
          description: 'Bangalore'
        }
      ];
      const action = new LoadTownsSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_TOWNS_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadTownsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadTownsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_TOWNS_FAILURE,
        payload
      });
    });
  });

  describe('LoadLocations Action Test Cases', () => {
    it('should check correct type is used for  LoadLocations action ', () => {
      const payload: ReportBTQCodePayload = {
        brands: ['TANISHQ'],
        regions: [],
        levels: [],
        towns: [],
        states: [],
        countries: []
      };
      const action = new LoadLocations(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_LOCAITONS,
        payload
      });
    });
    it('should check correct type is used for LoadLocationsSuccess action ', () => {
      const payload: LocationSummaryList[] = [
        {
          locationCode: 'URB',
          description: 'Bangalore'
        }
      ];
      const action = new LoadLocationsSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_LOCAITONS_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadLocationsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadLocationsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_LOCAITONS_FAILURE,
        payload
      });
    });
  });

  describe('LoadProductGroups Action Test Cases', () => {
    it('should check correct type is used for  LoadProductGroups action ', () => {
      const action = new LoadProductGroups();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_PRODUCT_GROUPS
      });
    });
    it('should check correct type is used for LoadProductGroupsSuccess action ', () => {
      const payload: ProductGroup[] = [
        {
          productGroupCode: '76',
          description: 'GOLD COIN'
        }
      ];
      const action = new LoadProductGroupsSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_PRODUCT_GROUPS_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadProductGroupsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadProductGroupsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_PRODUCT_GROUPS_FAILURE,
        payload
      });
    });
  });

  describe('LoadProductCategories Action Test Cases', () => {
    it('should check correct type is used for  LoadProductCategories action ', () => {
      const action = new LoadProductCategories();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_PRODUCT_CATEGORIES
      });
    });
    it('should check correct type is used for LoadProductCategoriesSuccess action ', () => {
      const payload: ProductCategory[] = [
        {
          productCategoryCode: '76',
          description: 'GOLD COIN',
          isActive: true
        }
      ];
      const action = new LoadProductCategoriesSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_PRODUCT_CATEGORIES_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadProductCategoriesFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadProductCategoriesFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_PRODUCT_CATEGORIES_FAILURE,
        payload
      });
    });
  });

  describe('LoadBinGroups Action Test Cases', () => {
    it('should check correct type is used for  LoadBinGroups action ', () => {
      const action = new LoadBinGroups();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_BIN_GROUPS
      });
    });
    it('should check correct type is used for LoadBinGroupsSuccess action ', () => {
      const payload: BinGroup[] = [
        {
          binGroupCode: '76',
          description: 'DEFECTIVE COIN',
          isActive: true
        }
      ];
      const action = new LoadBinGroupsSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_BIN_GROUPS_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadBinGroupsFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadBinGroupsFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_BIN_GROUPS_FAILURE,
        payload
      });
    });
  });

  describe('LoadBinCodes Action Test Cases', () => {
    it('should check correct type is used for  LoadBinCodes action ', () => {
      const payload = 'DEFECTIVE';
      const action = new LoadBinCodes(payload);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_BIN_CODES,
        payload
      });
    });
    it('should check correct type is used for LoadBinCodesSuccess action ', () => {
      const payload: BinCode[] = [
        {
          binCode: '76',
          description: 'DEFECTIVE COIN'
        }
      ];
      const action = new LoadBinCodesSuccess(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_BIN_CODES_SUCCESS,
        payload
      });
    });
    it('should check correct type is used for  LoadBinCodesFailure action ', () => {
      const payload: CustomErrors = CustomErrorAdaptor.fromJson(
        Error('Some Error')
      );
      const action = new LoadBinCodesFailure(payload);

      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_BIN_CODES_FAILURE,
        payload
      });
    });
  });

  describe('ClearReportsData Action Test Cases', () => {
    it('should check correct type is used for  ClearReportsData action ', () => {
      const action = new ClearReportsData();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.CLEAR_REPORTS_DATA
      });
    });
  });

  describe('LoadSubBrands Action Test Cases', () => {
    it('should check correct type is used for  LoadSubBrands action ', () => {
      const action = new LoadSubBrands('abc');
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_SUB_BRANDS,
        payload: 'abc'
      });
    });
  });

  describe('LoadSubBrandsSuccess Action Test Cases', () => {
    it('should check correct type is used for  LoadSubBrandsSuccess action ', () => {
      const action = new LoadSubBrandsSuccess({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_SUB_BRANDS_SUCCESS,
        payload: {} as any
      });
    });
  });

  describe('LoadSubBrandsFailure Action Test Cases', () => {
    it('should check correct type is used for  LoadSubBrandsFailure action ', () => {
      const action = new LoadSubBrandsFailure({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_SUB_BRANDS_FAILURE,
        payload: {} as any
      });
    });
  });

  describe('LoadTransferTypesFailure Action Test Cases', () => {
    it('should check correct type is used for  LoadTransferTypesFailure action ', () => {
      const action = new LoadTransferTypesFailure({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_TRANSFER_TYPES_FAILURE,
        payload: {} as any
      });
    });
  });

  describe('LoadTransferTypesSuccess Action Test Cases', () => {
    it('should check correct type is used for  LoadTransferTypesSuccess action ', () => {
      const action = new LoadTransferTypesSuccess({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_TRANSFER_TYPES_SUCCESS,
        payload: {} as any
      });
    });
  });

  describe('LoadTransferTypes Action Test Cases', () => {
    it('should check correct type is used for  LoadTransferTypes action ', () => {
      const action = new LoadTransferTypes();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_TRANSFER_TYPES,
      });
    });
  });

  describe('LoadSearchParameterFailure Action Test Cases', () => {
    it('should check correct type is used for  LoadSearchParameterFailure action ', () => {
      const action = new LoadSearchParameterFailure({} as any);
      expect({ ...action }).toEqual({
        payload: {} as any,
        type: ReportsActionTypes.LOAD_SEARCH_PARAMETERS_FAILURE,
      });
    });
  });

  describe('LoadSearchParameterSuccess Action Test Cases', () => {
    it('should check correct type is used for  LoadSearchParameterSuccess action ', () => {
      const action = new LoadSearchParameterSuccess({} as any);
      expect({ ...action }).toEqual({
        payload: {} as any,
        type: ReportsActionTypes.LOAD_SEARCH_PARAMETERS_SUCCESS,
      });
    });
  });

  describe('SaveSearchParameterFailure Action Test Cases', () => {
    it('should check correct type is used for  SaveSearchParameterFailure action ', () => {
      const action = new SaveSearchParameterFailure({} as any);
      expect({ ...action }).toEqual({
        payload: {} as any,
        type: ReportsActionTypes.SAVE_SEARCH_PARAMETERS_FAILURE,
      });
    });
  });


  describe('SaveSearchParameterSuccess Action Test Cases', () => {
    it('should check correct type is used for  SaveSearchParameterSuccess action ', () => {
      const action = new SaveSearchParameterSuccess({} as any);
      expect({ ...action }).toEqual({
        payload: {} as any,
        type: ReportsActionTypes.SAVE_SEARCH_PARAMETERS_SUCCESS,
      });
    });
  });

  describe('LoadCnType Action Test Cases', () => {
    it('should check correct type is used for  LoadCnType action ', () => {
      const action = new LoadCnType();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_CN_TYPES,
      });
    });
  });

  describe('LoadCnTypeFailure Action Test Cases', () => {
    it('should check correct type is used for  LoadCnTypeFailure action ', () => {
      const action = new LoadCnTypeFailure({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_CN_TYPES_FAILURE,
        payload: {} as any
      });
    });
  });

  describe('LoadCnStatus Action Test Cases', () => {
    it('should check correct type is used for  LoadCnStatus action ', () => {
      const action = new LoadCnStatus();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_CN_STATUS
      });
    });
  });

  describe('LoadCnTypeFailure Action Test Cases', () => {
    it('should check correct type is used for  LoadCnTypeFailure action ', () => {
      const action = new LoadCnTypeFailure({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_CN_TYPES_FAILURE,
        payload: {} as any
      });
    });
  });

  describe('LoadCnStatusFailure Action Test Cases', () => {
    it('should check correct type is used for  LoadCnStatusFailure action ', () => {
      const action = new LoadCnStatusFailure({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_CN_STATUS_FAILURE,
        payload: {} as any
      });
    });
  });

  describe('SaveIndividualSetting Action Test Cases', () => {
    it('should check correct type is used for  SaveIndividualSetting action ', () => {
      const action = new SaveIndividualSetting({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.SAVE_INDIVIDUAL_SETTINGS,
        payload: {} as any
      });
    });
  });

  describe('SaveIndividualSettingFailure Action Test Cases', () => {
    it('should check correct type is used for  SaveIndividualSettingFailure action ', () => {
      const action = new SaveIndividualSettingFailure({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.SAVE_INDIVIDUAL_SETTINGS_FAILURE,
        payload: {} as any
      });
    });
  });

  describe('LoadExcludedIndividualSetting Action Test Cases', () => {
    it('should check correct type is used for  LoadExcludedIndividualSetting action ', () => {
      const action = new LoadExcludedIndividualSetting({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_EXCLUDED_INDIVIDUAL_SETTINGS,
        payload: {} as any
      });
    });
  });

  describe('LoadExcludedIndividualSettingSuccess Action Test Cases', () => {
    it('should check correct type is used for  LoadExcludedIndividualSettingSuccess action ', () => {
      const action = new LoadExcludedIndividualSettingSuccess({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_EXCLUDED_INDIVIDUAL_SETTINGS_SUCCESS,
        payload: {} as any
      });
    });
  });

  describe('LoadExcludedIndividualSettingFailure Action Test Cases', () => {
    it('should check correct type is used for  LoadExcludedIndividualSettingFailure action ', () => {
      const action = new LoadExcludedIndividualSettingFailure({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.LOAD_EXCLUDED_INDIVIDUAL_SETTINGS_FAILURE,
        payload: {} as any
      });
    });
  });

  describe('UpdateIndividualSetting Action Test Cases', () => {
    it('should check correct type is used for  UpdateIndividualSetting action ', () => {
      const action = new UpdateIndividualSetting({} as any);
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.UPDATE_INDIVIDUAL_SETTINGS,
        payload: {} as any
      });
    });
  });

  describe('UpdateIndividualSettingSuccess Action Test Cases', () => {
    it('should check correct type is used for  UpdateIndividualSettingSuccess action ', () => {
      const action = new UpdateIndividualSettingSuccess();
      expect({ ...action }).toEqual({
        type: ReportsActionTypes.UPDATE_INDIVIDUAL_SETTINGS_SUCCESS,
      });
    });
  });
});
