call nx g @nrwl/angular:lib data-access-inventory-home  --directory=eposs/inventory-home  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-inventory-home  --directory=eposs/inventory-home  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-stock-receive  --directory=eposs/Stock-Receive  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-stock-receive-item-list  --directory=eposs/Stock-Receive  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-stock-receive-details  --directory=eposs/Stock-Receive  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-stock-receive-list  --directory=eposs/Stock-Receive  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-bin-bin-transfer  --directory=eposs/Bin-Bin-Transfer  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-bin-bin-transfer-item-list  --directory=eposs/Bin-Bin-Transfer  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-bin-bin-transfer-details  --directory=eposs/Bin-Bin-Transfer  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-bin-bin-transfer-list  --directory=eposs/Bin-Bin-Transfer  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-ibt  --directory=eposs/ibt  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-ibt-item-list  --directory=eposs/ibt  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-ibt-details  --directory=eposs/ibt  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-ibt-list  --directory=eposs/ibt  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-ibt-create-request  --directory=eposs/ibt  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-conversion  --directory=eposs/conversion  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-conversion-item  --directory=eposs/conversion  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-conversion-details  --directory=eposs/conversion  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-conversion  --directory=eposs/conversion  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-other-receipt  --directory=eposs/other-receipt  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-other-receipt-adjustment-item-list  --directory=eposs/other-receipt  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-other-receipt-item-list  --directory=eposs/other-receipt  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-other-receipt-psv-item-list  --directory=eposs/other-receipt  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-other-receipt-details  --directory=eposs/other-receipt  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-other-receipt-issue-list  --directory=eposs/other-receipt-Issue  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-other-issue  --directory=eposs/other-issue  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-other-issue-adjustment-item-list  --directory=eposs/other-issue  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-other-issue-exhibition-create-item-list  --directory=eposs/other-issue  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-other-issue-exhibition-item-list  --directory=eposs/other-issue  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-other-issue-foc-item-list  --directory=eposs/other-issue  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-other-issue-psv-item-list  --directory=eposs/other-issue  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-other-issue-adj-details  --directory=eposs/other-issue  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-other-issue-exh-create-request  --directory=eposs/other-issue  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-other-issue-foc-details  --directory=eposs/other-issue  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-other-issue-psv-details  --directory=eposs/other-issue  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-bin-request  --directory=eposs/new-bin-request  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-bin-request-bin-list  --directory=eposs/new-bin-request  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-bin-request  --directory=eposs/new-bin-request  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-stock-issue  --directory=eposs/stock-issue  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-stock-issue-item-list  --directory=eposs/stock-issue  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-stock-issue-details  --directory=eposs/stock-issue  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-stock-issue-list  --directory=eposs/stock-issue  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-stock-issue-tep-gep  --directory=eposs/stock-issue-tep-gep  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-stock-issue-tep-gep-item-list  --directory=eposs/stock-issue-tep-gep  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-stock-issue-tep-gep-details  --directory=eposs/stock-issue-tep-gep  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-stock-return  --directory=eposs/stock-return  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-stock-return-item-list  --directory=eposs/stock-return  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-stock-return-details  --directory=eposs/stock-return  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-data-upload  --directory=eposs/data-upload  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-data-upload  --directory=eposs/data-upload  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-Master-Home  --directory=eposs/master-home  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-master-menu  --directory=eposs/master-home  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-master-sub-menu  --directory=eposs/master-home  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-brand  --directory=eposs/brand  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-brand-list  --directory=eposs/brand  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-brand-detail  --directory=eposs/brand  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-brand-listing  --directory=eposs/brand  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-brand-detail  --directory=eposs/brand  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/brand  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-location-setup  --directory=eposs/location-setup  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-location-listing  --directory=eposs/location-setup  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-location-detail  --directory=eposs/location-setup  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-location-detail  --directory=eposs/location-setup  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-location-listing  --directory=eposs/location-setup  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/location-setup  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-sub-brand  --directory=eposs/sub-brand  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-sub-brand-list  --directory=eposs/sub-brand  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-sub-brand-detail  --directory=eposs/sub-brand  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-sub-brand  --directory=eposs/sub-brand  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/sub-brand  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-bin  --directory=eposs/bin  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-bin-listing  --directory=eposs/bin  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-bin-popup  --directory=eposs/bin  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/bin  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-bin-group  --directory=eposs/bin-group  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-bin-group-list  --directory=eposs/bin-group  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-bin-group-detail  --directory=eposs/bin-group  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-bin-group  --directory=eposs/bin-group  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/bin-group  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-courier  --directory=eposs/courier  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-courier-list  --directory=eposs/courier  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-courier-detail  --directory=eposs/courier  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-courier-listing  --directory=eposs/courier  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-courier-detail  --directory=eposs/courier  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/courier  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-weight-tolerance  --directory=eposs/weight-tolerance  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-weight-tolerance-list  --directory=eposs/weight-tolerance  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-weight-tolerance-detail  --directory=eposs/weight-tolerance  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-weight-tolerance-edit  --directory=eposs/weight-tolerance  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-weight-tolerance-listing  --directory=eposs/weight-tolerance  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/weight-tolerance  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-lov  --directory=eposs/list-of-values  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-lov-list  --directory=eposs/list-of-values  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-lov-detail  --directory=eposs/list-of-values  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-lov-listing  --directory=eposs/list-of-values  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/list-of-values  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-corporate-town  --directory=eposs/corporate-town  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-corporate-town-list  --directory=eposs/corporate-town  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-corporate-town-detail  --directory=eposs/corporate-town  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-corporate-town-listing  --directory=eposs/corporate-town  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/corporate-town  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-cfa-product  --directory=eposs/cfa-product  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-cfa-product-list  --directory=eposs/cfa-product  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-cfa-product-detail  --directory=eposs/cfa-product  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-cfa-product-listing  --directory=eposs/cfa-product  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-cfa-product-detail  --directory=eposs/cfa-product  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/cfa-product  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-item-master  --directory=eposs/item-master  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-item-list  --directory=eposs/item-master  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-item-detail  --directory=eposs/item-master  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-item-listing  --directory=eposs/item-master  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-item-detail  --directory=eposs/item-master  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/item-master  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-product-category  --directory=eposs/product-category  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-product-category-list  --directory=eposs/product-category  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-product-category-detail  --directory=eposs/product-category  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-product-category-listing  --directory=eposs/product-category  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/product-category  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-stone-type  --directory=eposs/stone-type  --unit-test-runner=karma --tags="scope:eposs,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-stone-type-detail  --directory=eposs/stone-type  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-stone-type-list  --directory=eposs/stone-type  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-stone-type-listing  --directory=eposs/stone-type  --unit-test-runner=karma --tags="scope:eposs,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-master-form-modals  --directory=eposs/stone-type  --unit-test-runner=karma --tags="scope:eposs,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-uam-home  --directory=shared/uam-home  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-activate-user  --directory=shared/activate-user  --unit-test-runner=karma --tags="scope:shared,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-activate-user-form  --directory=shared/activate-user  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-activate-user  --directory=shared/activate-user  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-forgot-password  --directory=shared/forgot-password  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-forgot-password  --directory=shared/forgot-password  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-user  --directory=shared/user-mgmt  --unit-test-runner=karma --tags="scope:shared,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-user-list  --directory=shared/user-mgmt  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-user-detail  --directory=shared/user-mgmt  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-user-listing  --directory=shared/user-mgmt  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-user-detail  --directory=shared/user-mgmt  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib util-user-mgmt  --directory=shared/user-mgmt  --unit-test-runner=karma --tags="scope:shared,type:util" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-role-mgmt-shell  --directory=shared/role-mgmt-shell  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-role-config  --directory=shared/role-config  --unit-test-runner=karma --tags="scope:shared,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-role-config-list  --directory=shared/role-config  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-request-list  --directory=shared/role-config  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-request-detail  --directory=shared/role-config  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-role-config-listing  --directory=shared/role-config  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-request-listing  --directory=shared/role-config  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-request-detail  --directory=shared/role-config  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-role-mgmt  --directory=shared/role-mgmt  --unit-test-runner=karma --tags="scope:shared,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-role-list  --directory=shared/role-mgmt  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-role-detail  --directory=shared/role-mgmt  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-role-create-form  --directory=shared/role-mgmt  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-role-edit-form  --directory=shared/role-mgmt  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-create-role  --directory=shared/role-mgmt  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-role-listing  --directory=shared/role-mgmt  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-login-shell  --directory=shared/login  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-login-form  --directory=shared/login  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib data-access-access-control-mgmt  --directory=shared/access-control-mgmt  --unit-test-runner=karma --tags="scope:shared,type:data-access" --style="scss" --dry-run
call nx g @nrwl/angular:lib ui-access-control-list  --directory=shared/access-control-mgmt  --unit-test-runner=karma --tags="scope:shared,type:ui" --style="scss" --dry-run
call nx g @nrwl/angular:lib feature-access-control  --directory=shared/access-control-mgmt  --unit-test-runner=karma --tags="scope:shared,type:feature" --style="scss" --dry-run
call  nx g @nrwl/angular:lib ui-bin-bin-transfer-popup  --directory=eposs/Bin-Bin-Transfer  --unit-test-runner=karma --tags="scope:eposs,type:ui" --style="scss" --dry-run
