call ng lint  eposs-ab-tolerance-config-data-access-ab-tolerance-config
call ng lint  eposs-grn-approval-config-data-access-grn-approval-config
call ng lint  eposs-grf-tolerance-config-ui-grf-tolerance-config-detail
call ng lint  eposs-gep-purity-config-feature-gep-purity-config-details
call ng lint  eposs-conversion-config-feature-conversion-config-details
call ng lint  eposs-tep-product-group-feature-tep-product-group-listing
call ng lint  eposs-grn-request-approvals-feature-grn-request-approvals
call ng lint  eposs-inventory-global-config-ui-inv-global-config-detail
call ng lint  eposs-other-receipt-ui-other-receipt-adjustment-item-list
call ng lint  eposs-tep-exception-config-ui-tep-exception-config-detail
call ng lint  eposs-gl-location-payment-data-access-gl-location-payment
call ng lint  eposs-order-payment-config-ui-order-payment-config-detail
call ng lint  eposs-cash-payment-config-data-access-cash-payment-config
call ng lint  eposs-cashback-offer-config-ui-cashback-offer-config-list
call ng lint  eposs-stock-receive-feature-stock-receive-history-details
call ng lint  eposs-clubbing-discount-config-ui-clubbing-discount-popup
call ng lint  eposs-tep-product-group-feature-tep-product-group-detail
call ng lint  eposs-grn-approval-config-ui-grn-approval-config-listing
call ng lint  eposs-ab-tolerance-config-ui-ab-tolerance-config-details
call ng lint  eposs-other-issue-feature-other-issue-exh-create-request
call ng lint  eposs-request-approvals-feature-request-approval-listing
call ng lint  eposs-gl-location-payment-ui-gl-location-payment-listing
call ng lint  eposs-discount-config-ui-discount-value-percentage-popup
call ng lint  eposs-ab-tolerance-config-ui-ab-tolerance-config-listing
call ng lint  eposs-ab-manual-requests-data-access-ab-manual-requests
call ng lint  eposs-cash-payment-config-ui-cash-payment-config-detail
call ng lint  eposs-discount-config-ui-discount-product-group-mapping
call ng lint  eposs-gl-boutique-location-ui-gl-boutique-location-view
call ng lint  eposs-discount-config-ui-discount-exchange-offer-config
call ng lint  eposs-grn-tolerance-config-ui-grn-tolerance-config-view
call ng lint  eposs-grf-tolerance-config-ui-grf-tolerance-config-list
call ng lint  eposs-tep-stone-config-feature-tep-stone-config-listing
call ng lint  eposs-tep-exception-config-ui-tep-exception-config-list
call ng lint  eposs-bgr-tolerance-config-ui-bgr-tolerance-config-view
call ng lint  eposs-grf-tolerance-config-ui-grf-tolerance-config-view
call ng lint  eposs-discount-config-ui-discount-exchange-offer-pg-map
call ng lint  eposs-bin-bin-transfer-feature-bin-bin-transfer-details
call ng lint  eposs-weight-tolerance-feature-weight-tolerance-listing
call ng lint  eposs-airpay-host-config-data-access-airpay-host-config
call ng lint  eposs-request-approvals-ui-ibt-cancel-request-item-list
call ng lint  eposs-cn-priority-config-data-access-cn-priority-config
call ng lint  eposs-state-tax-config-feature-state-tax-config-listing
call ng lint  eposs-grn-tolerance-config-ui-grn-tolerance-config-list
call ng lint  eposs-grn-approval-config-ui-grn-approval-config-detail
call ng lint  eposs-gv-redemption-config-feature-gv-redemption-config
call ng lint  eposs-order-payment-config-ui-order-payment-config-view
call ng lint  eposs-cut-piece-config-feature-cut-piece-config-details
call ng lint  eposs-ftep-approval-config-ui-ftep-approval-config-view
call ng lint  eposs-foc-blocking-location-level-feature-foc-bll-list
call ng lint  eposs-payer-bank-config-ui-payer-bank-config-item-list
call ng lint  eposs-conversion-config-feature-conversion-config-list
call ng lint  eposs-foc-blocking-customer-level-feature-foc-bcl-list
call ng lint  eposs-request-approvals-ui-request-approvals-item-list
call ng lint  eposs-gep-purity-config-ui-gep-purity-config-item-list
call ng lint  eposs-cn-priority-config-ui-cn-priority-config-listing
call ng lint  eposs-payer-bank-config-feature-payer-bank-config-list
call ng lint  eposs-gv-redemption-config-ui-gv-redemption-mob-config
call ng lint  eposs-conversion-config-ui-conversion-config-item-list
call ng lint  eposs-gep-purity-config-feature-gep-purity-config-list
call ng lint  eposs-tep-stone-config-feature-tep-stone-config-detail
call ng lint  eposs-request-approvals-ui-bin-request-approvals-popup
call ng lint  eposs-weight-tolerance-feature-weight-tolerance-detail
call ng lint  eposs-gl-location-payment-ui-gl-location-payment-popup
call ng lint  eposs-state-tax-config-feature-state-tax-config-detail
call ng lint  eposs-tep-approval-ui-full-value-tep-request-list-grid
call ng lint  eposs-conversion-config-data-access-conversion-config
call ng lint  eposs-discount-config-ui-discount-config-request-list
call ng lint  eposs-other-receipt-feature-other-receipt-adj-details
call ng lint  eposs-payer-bank-config-data-access-payer-bank-config
call ng lint  eposs-max-flat-tep-config-feature-max-flat-tep-config
call ng lint  eposs-foc-blocking-location-level-data-access-foc-bll
call ng lint  eposs-tep-product-group-data-access-tep-product-group
call ng lint  eposs-other-receipt-feature-other-receipt-psv-details
call ng lint  eposs-gep-purity-config-data-access-gep-purity-config
call ng lint  eposs-cn-validation-feature-cn-validation-view-detail
call ng lint  eposs-request-approvals-data-access-request-approvals
call ng lint  eposs-other-issue-ui-other-issue-exhibition-item-list
call ng lint  eposs-foc-blocking-customer-level-data-access-foc-bcl
call ng lint  eposs-cn-priority-config-ui-cn-priority-config-detail
call ng lint  eposs-stock-issue-feature-stock-issue-history-details
call ng lint  eposs-ab-tolerance-config-ui-ab-tolerance-config-view
call ng lint  eposs-other-issue-ui-other-issue-adjustment-item-list
call ng lint  eposs-discount-config-feature-discount-config-request
call ng lint  eposs-payer-bank-config-ui-payer-bank-config-details
call ng lint  eposs-conversion-config-ui-conversion-config-details
call ng lint  eposs-grn-request-approvals-ui-grn-request-approvals
call ng lint  eposs-gep-purity-config-ui-gep-purity-config-details
call ng lint  eposs-discount-config-ui-discount-lot-bin-age-config
call ng lint  eposs-bin-bin-transfer-ui-bin-bin-transfer-item-list
call ng lint  eposs-bin-bin-transfer-feature-bin-bin-transfer-list
call ng lint  eposs-stock-return-feature-stock-return-history-list
call ng lint  eposs-discount-config-ui-discount-empowerment-config
call ng lint  eposs-discount-config-ui-discount-max-allowed-value
call ng lint  eposs-state-tax-config-data-access-state-tax-config
call ng lint  eposs-tep-stone-config-data-access-tep-stone-config
call ng lint  eposs-weight-tolerance-data-access-weight-tolerance
call ng lint  eposs-cut-piece-config-data-access-cut-piece-config
call ng lint  eposs-airpay-host-config-feature-airpay-host-config
call ng lint  eposs-configuration-home-feature-configuration-home
call ng lint  eposs-conversion-feature-conversion-history-details
call ng lint  eposs-bin-bin-transfer-data-access-bin-bin-transfer
call ng lint  eposs-gv-status-update-data-access-gv-status-update
call ng lint  eposs-ab-manual-requests-ab-manual-requests-feature
call ng lint  eposs-tep-product-group-ui-tep-product-group-detail
call ng lint  eposs-tep-approval-feature-full-value-tep-approval
call ng lint  eposs-cut-piece-config-ui-cut-piece-config-details
call ng lint  eposs-other-receipt-ui-other-receipt-psv-item-list
call ng lint  eposs-weight-tolerance-ui-weight-tolerance-listing
call ng lint  eposs-discount-config-feature-discount-config-list
call ng lint  eposs-gv-redemption-config-ui-gv-redemption-config
call ng lint  eposs-gep-purity-config-ui-gep-purity-config-popup
call ng lint  eposs-discount-config-ui-discount-applicable-theme
call ng lint  eposs-discount-config-ui-discount-location-mapping
call ng lint  eposs-other-receipt-feature-other-receipt-details
call ng lint  eposs-stock-receive-feature-stock-receive-details
call ng lint  eposs-foc-blocking-customer-level-ui-foc-bcl-list
call ng lint  eposs-state-tax-config-ui-state-tax-config-detail
call ng lint  eposs-other-issue-feature-other-issue-exh-details
call ng lint  eposs-cn-validation-feature-cn-validation-listing
call ng lint  eposs-discount-config-data-access-discount-config
call ng lint  eposs-tep-product-group-ui-tep-product-group-list
call ng lint  eposs-weight-tolerance-ui-weight-tolerance-detail
call ng lint  eposs-password-config-data-access-password-config
call ng lint  eposs-other-issue-feature-other-issue-psv-details
call ng lint  eposs-foc-blocking-location-level-ui-foc-bll-list
call ng lint  eposs-unipay-config-feature-unipay-access-mapping
call ng lint  eposs-discount-config-ui-discount-refer-best-deal
call ng lint  eposs-ab-manual-requests-ab-manual-requests-shell
call ng lint  eposs-other-issue-feature-other-issue-foc-details
call ng lint  eposs-tep-stone-config-ui-tep-stone-config-detail
call ng lint  eposs-other-issue-feature-other-issue-adj-details
call ng lint  eposs-shared-ab-requests-data-access-ab-requests
call ng lint  eposs-cn-validation-feature-cn-validation-detail
call ng lint  eposs-stock-return-ui-stock-return-history-popup
call ng lint  eposs-discount-config-ui-discount-exclude-config
call ng lint  eposs-bin-bin-transfer-ui-bin-bin-transfer-popup
call ng lint  eposs-max-flat-tep-config-ui-max-flat-tep-config
call ng lint  eposs-request-approvals-ui-bin-request-item-list
call ng lint  eposs-tep-stone-config-ui-tep-stone-config-view
call ng lint  eposs-state-tax-config-ui-state-tax-config-list
call ng lint  eposs-stock-return-feature-stock-return-details
call ng lint  eposs-tep-approval-feature-regular-tep-approval
call ng lint  eposs-discount-config-ui-discount-config-header
call ng lint  eposs-gv-status-update-feature-gv-status-update
call ng lint  eposs-inventory-home-data-access-inventory-home
call ng lint  eposs-tep-stone-config-ui-tep-stone-config-list
call ng lint  eposs-password-config-feature-generate-password
call ng lint  eposs-other-receipt-ui-other-receipt-item-list
call ng lint  eposs-discount-config-ui-emp-discount-location
call ng lint  eposs-other-issue-ui-other-issue-psv-item-list
call ng lint  eposs-other-issue-ui-other-issue-foc-item-list
call ng lint  eposs-stock-receive-ui-stock-receive-item-list
call ng lint  eposs-unipay-config-ui-unipay-config-item-list
call ng lint  eposs-airpay-host-config-ui-airpay-host-config
call ng lint  eposs-stock-receive-feature-stock-receive-list
call ng lint  eposs-ab-manual-requests-ui-ab-manual-requests
call ng lint  eposs-cn-master-feature-cn-master-view-detail
call ng lint  eposs-unipay-config-data-access-unipay-config
call ng lint  eposs-discount-config-ui-discount-config-list
call ng lint  eposs-stock-issue-feature-stock-issue-details
call ng lint  eposs-other-receipt-data-access-other-receipt
call ng lint  eposs-new-bin-request-data-access-bin-request
call ng lint  eposs-airpay-config-data-access-airpay-config
call ng lint  eposs-cn-validation-data-access-cn-validation
call ng lint  eposs-stock-receive-data-access-stock-receive
call ng lint  eposs-discount-config-feature-discount-config
call ng lint  eposs-instock-home-feature-instock-home-shell
call ng lint  eposs-discount-config-ui-discount-ab-co-popup
call ng lint  eposs-discount-config-ui-discount-slab-config
call ng lint  eposs-discount-config-ui-discount-tsss-config
call ng lint  eposs-new-bin-request-ui-bin-request-bin-list
call ng lint  eposs-conversion-ui-conversion-request-popup
call ng lint  eposs-discount-config-ui-discount-applicable
call ng lint  eposs-foc-config-feature-foc-variant-details
call ng lint  eposs-cn-validation-ui-cn-validation-listing
call ng lint  eposs-stock-return-ui-stock-return-item-list
call ng lint  eposs-shared-ab-requests-feature-ab-requests
call ng lint  eposs-ibt-config-feature-ibt-config-listing
call ng lint  eposs-bgr-config-feature-bgr-config-listing
call ng lint  eposs-inventory-home-feature-inventory-home
call ng lint  eposs-cn-approvals-data-access-cn-approvals
call ng lint  eposs-conversion-feature-conversion-details
call ng lint  eposs-cn-validation-ui-cn-validation-detail
call ng lint  eposs-stock-return-data-access-stock-return
call ng lint  eposs-tep-approval-data-access-tep-approval
call ng lint  eposs-approvals-home-feature-approvals-home
call ng lint  eposs-new-bin-request-ui-bin-details-popup
call ng lint  eposs-password-config-ui-generate-password
call ng lint  eposs-stock-issue-ui-stock-issue-item-list
call ng lint  eposs-gv-status-update-ui-gv-status-update
call ng lint  eposs-bgr-config-feature-bgr-config-detail
call ng lint  eposs-foc-config-ui-foc-item-mapping-popup
call ng lint  eposs-ibt-config-feature-ibt-config-detail
call ng lint  eposs-stock-issue-feature-stock-issue-list
call ng lint  eposs-foc-config-feature-foc-config-detail
call ng lint  eposs-stock-receive-ui-stock-receive-popup
call ng lint  eposs-new-bin-request-feature-bin-details
call ng lint  eposs-other-issue-data-access-other-issue
call ng lint  eposs-new-bin-request-feature-bin-request
call ng lint  eposs-gst-mapping-data-access-gst-mapping
call ng lint  eposs-data-upload-data-access-data-upload
call ng lint  eposs-cn-master-feature-cn-master-listing
call ng lint  eposs-stock-issue-data-access-stock-issue
call ng lint  eposs-airpay-config-feature-airpay-config
call ng lint  eposs-tep-approval-ui-stone-details-popup
call ng lint  eposs-cn-master-feature-cn-master-detail
call ng lint  eposs-foc-config-feature-foc-config-list
call ng lint  eposs-conversion-data-access-conversion
call ng lint  eposs-bgr-config-data-access-bgr-config
call ng lint  eposs-foc-config-data-access-foc-config
call ng lint  eposs-cn-approvals-feature-cn-approvals
call ng lint  eposs-approvals-feature-request-details
call ng lint  eposs-ibt-config-data-access-ibt-config
call ng lint  eposs-approvals-feature-request-listing
call ng lint  eposs-foc-config-ui-foc-variant-details
call ng lint  eposs-instock-home-feature-instock-home
call ng lint  eposs-shared-ab-requests-ui-ab-requests
call ng lint  eposs-ibt-config-ui-ibt-config-listing
call ng lint  eposs-tep-approval-feature-refund-list
call ng lint  eposs-tep-approval-ui-refund-list-grid
call ng lint  eposs-gst-mapping-ui-gst-mapping-form
call ng lint  eposs-bgr-config-ui-bgr-config-detail
call ng lint  eposs-cn-master-data-access-cn-master
call ng lint  eposs-ibt-config-ui-ibt-config-detail
call ng lint  eposs-gst-mapping-feature-gst-mapping
call ng lint  eposs-gst-mapping-ui-gst-mapping-list
call ng lint  eposs-foc-config-ui-foc-config-detail
call ng lint  eposs-data-upload-feature-data-upload
call ng lint  eposs-shared-ui-courier-details-popup
call ng lint  eposs-airpay-config-ui-airpay-config
call ng lint  eposs-ibt-feature-ibt-create-request
call ng lint  eposs-cn-master-ui-cn-master-listing
call ng lint  eposs-bgr-config-ui-bgr-config-view
call ng lint  eposs-conversion-ui-conversion-item
call ng lint  eposs-conversion-feature-conversion
call ng lint  eposs-bgr-config-ui-bgr-config-list
call ng lint  eposs-foc-config-ui-foc-config-list
call ng lint  eposs-cn-master-ui-cn-master-detail
call ng lint  eposs-tep-approval-ui-tep-approval
call ng lint  eposs-cn-approvals-ui-cn-approvals
call ng lint  eposs-shared-ui-out-of-stock-popup
call ng lint  eposs-range-feature-range-details
call ng lint  eposs-range-data-access-range
call ng lint  eposs-ibt-feature-ibt-details
call ng lint  eposs-range-ui-range-details
call ng lint  eposs-ibt-ui-ibt-item-list
call ng lint  eposs-ibt-feature-ibt-list
call ng lint  eposs-ibt-data-access-ibt
call ng lint  eposs-home-feature-home
call ng lint  eposs-ibt-ui-ibt-popup
call ng lint  eposs-e2e
call ng lint  eposs