call ng lint  poss-gift-cards-ui-gift-cards-grid
call ng lint  poss-grn-feature-grn-details-shell
call ng lint  poss-ct-advance-ui-rso-names-list
call ng lint  poss-credit-note-feature-cn-shell
call ng lint  poss-tep-feature-tep-request-view
call ng lint  poss-bod-eod-data-access-bod-eod
call ng lint  poss-gift-cards-feature-gc-shell
call ng lint  poss-cash-memo-ui-add-coin-popup
call ng lint  poss-shared-discount-ui-discount
call ng lint  poss-credit-note-data-access-cn
call ng lint  poss-shared-feature-summary-bar
call ng lint  poss-gift-cards-feature-gc-menu
call ng lint  poss-cash-memo-ui-add-foc-popup
call ng lint  poss-cash-memo-feature-cm-shell
call ng lint  poss-bc-feature-bc-detail-shell
call ng lint  poss-tep-feature-tep-view-shell
call ng lint  poss-shared-product-ui-product
call ng lint  poss-cash-memo-feature-cm-menu
call ng lint  poss-shared-toolbar-ui-toolbar
call ng lint  poss-tep-feature-cut-piece-tep
call ng lint  poss-cash-memo-ui-order-search
call ng lint  poss-grf-feature-grf-history
call ng lint  poss-tep-feature-tep-history
call ng lint  poss-tep-feature-tep-request
call ng lint  poss-bod-eod-feature-bod-eod
call ng lint  poss-gep-ui-gep-product-grid
call ng lint  poss-gep-feature-gep-on-hold
call ng lint  poss-bod-eod-ui-eod-process
call ng lint  poss-grn-feature-grn-status
call ng lint  poss-gep-feature-cancel-gep
call ng lint  poss-tep-feature-tep-search
call ng lint  poss-bod-eod-ui-bod-process
call ng lint  poss-shared-ui-product-grid
call ng lint  poss-gep-feature-manual-gep
call ng lint  poss-tep-feature-tep-cancel
call ng lint  poss-grn-feature-create-grn
call ng lint  poss-tep-feature-manual-tep
call ng lint  poss-tep-feature-create-tep
call ng lint  poss-tep-ui-refund-details
call ng lint  poss-grf-feature-merge-grf
call ng lint  poss-tep-ui-rso-names-list
call ng lint  poss-shared-feature-common
call ng lint  poss-foc-feature-foc-shell
call ng lint  poss-grf-ui-merge-grf-list
call ng lint  poss-gep-feature-gep-shell
call ng lint  poss-grf-ui-rso-names-list
call ng lint  poss-tep-feature-tep-shell
call ng lint  poss-gift-cards-ui-rso-name
call ng lint  poss-bc-feature-bc-detail
call ng lint  poss-tep-feature-tep-view
call ng lint  poss-grf-feature-grf-menu
call ng lint  poss-gep-feature-gep-menu
call ng lint  poss-grn-feature-view-grn
call ng lint  poss-tep-data-access-tep
call ng lint  poss-gep-feature-new-gep
call ng lint  poss-foc-data-access-foc
call ng lint  poss-grf-data-access-grf
call ng lint  poss-gep-data-access-gep
call ng lint  poss-grn-data-access-grn
call ng lint  poss-bc-feature-bc-shell
call ng lint  poss-grn-ui-grn-history
call ng lint  poss-bc-feature-bc-list
call ng lint  poss-tep-ui-tep-details
call ng lint  poss-grn-ui-grn-status
call ng lint  poss-home-feature-home
call ng lint  poss-foc-ui-foc-popups
call ng lint  poss-gep-ui-manual-gep
call ng lint  poss-bc-data-access-bc
call ng lint  poss-shared-util-price
call ng lint  poss-grn-ui-create-grn
call ng lint  poss-gep-ui-cancel-gep
call ng lint  poss-grf-feature-grf
call ng lint  poss-bc-ui-bc-detail
call ng lint  poss-bc-ui-bc-list
call ng lint  poss-grf-feature-grf-shell
call ng lint  poss-bc-ui-bc
call ng lint  poss-e2e
call ng lint  poss
call ng lint shared-complexity-pricegroup-map-feature-complexity-pricegroup-map-listing
call ng lint shared-transaction-type-master-feature-transaction-type-master-listing
call ng lint shared-complexity-pricegroup-map-data-access-complexity-pricegroup-map
call ng lint shared-complexity-pricegroup-map-ui-complexity-pricegroup-map-detail
call ng lint shared-boutique-bank-deposit-feature-boutique-bank-deposit-listing
call ng lint shared-transaction-type-master-data-access-transaction-type-master
call ng lint shared-market-material-price-feature-market-material-price-listing
call ng lint shared-complexity-pricegroup-map-ui-complexity-pricegroup-map-list
call ng lint shared-market-material-price-feature-market-material-price-detail
call ng lint shared-transaction-type-master-ui-transaction-type-master-detail
call ng lint shared-bank-priority-master-feature-bank-priority-master-listing
call ng lint shared-ro-request-approvals-feature-ro-request-approvals-status
call ng lint shared-market-material-price-data-access-market-material-price
call ng lint shared-boutique-bank-deposit-data-access-boutique-bank-deposit
call ng lint shared-transaction-type-master-ui-transaction-type-master-list
call ng lint shared-product-group-mapping-data-access-product-group-mapping
call ng lint shared-market-material-price-ui-market-material-price-detail
call ng lint shared-bank-priority-master-data-access-bank-priority-master
call ng lint shared-monitoring-dashboard-data-access-monitoring-dashboard
call ng lint shared-ro-request-approvals-data-access-ro-request-approvals
call ng lint shared-boutique-bank-deposit-ui-boutique-bank-deposit-items
call ng lint shared-ro-request-approvals-ui-ro-request-approvals-status
call ng lint shared-market-material-price-ui-market-material-price-list
call ng lint shared-product-group-mapping-feature-product-group-mapping
call ng lint shared-access-control-mgmt-data-access-access-control-mgmt
call ng lint shared-price-group-mapping-data-access-price-group-mapping
call ng lint shared-ro-request-approvals-feature-ro-request-approvals
call ng lint shared-product-category-feature-product-category-listing
call ng lint shared-monitoring-dashboard-feature-monitoring-dashboard
call ng lint shared-overlay-notification-feature-overlay-notification
call ng lint shared-catchment-master-feature-catchment-master-listing
call ng lint shared-order-confirmation-data-access-order-confirmation
call ng lint shared-bank-priority-master-ui-bank-priority-master-list
call ng lint shared-monitoring-dashboard-ui-manual-trigger-data-sync
call ng lint shared-upload-eghs-bank-deposit-data-access-upload-eghs
call ng lint shared-one-time-password-data-access-one-time-password
call ng lint shared-location-master-feature-location-master-listing
call ng lint shared-currency-master-feature-currency-master-listing
call ng lint shared-price-group-mapping-feature-price-group-mapping
call ng lint shared-product-category-mapping-data-access-pc-mapping
call ng lint shared-location-settings-data-access-location-settings
call ng lint shared-monitoring-dashboard-ui-scheduled-jobs-listing
call ng lint shared-location-master-feature-location-master-detail
call ng lint shared-location-mapping-data-access-location-mapping
call ng lint shared-catchment-master-data-access-catchment-master
call ng lint shared-corporate-town-feature-corporate-town-listing
call ng lint shared-product-category-data-access-product-category
call ng lint shared-country-master-feature-country-master-listing
call ng lint shared-monitoring-dashboard-ui-update-scheduler-time
call ng lint shared-manual-cm-request-feature-cm-request-details
call ng lint shared-manual-cm-request-feature-cm-request-listing
call ng lint shared-monitoring-dashboard-ui-data-sync-statistics
call ng lint shared-upload-eghs-bank-deposit-feature-upload-eghs
call ng lint shared-catchment-master-ui-catchment-master-detail
call ng lint shared-complexity-code-data-access-complexity-code
call ng lint shared-location-settings-feature-location-settings
call ng lint shared-location-master-data-access-location-master
call ng lint shared-product-category-mapping-feature-pc-mapping
call ng lint shared-product-category-ui-product-category-detail
call ng lint shared-currency-master-data-access-currency-master
call ng lint shared-components-ui-fileupload-confirmation-popup
call ng lint shared-access-control-mgmt-ui-access-control-list
call ng lint shared-price-group-mapping-ui-price-group-mapping
call ng lint shared-item-master-ui-product-search-autocomplete
call ng lint shared-access-control-mgmt-feature-access-control
call ng lint shared-manual-cm-request-feature-cm-request-shell
call ng lint shared-location-mapping-feature-location-mapping
call ng lint shared-catchment-master-ui-catchment-master-list
call ng lint shared-cpg-qcgc-map-feature-cpg-qcgc-map-listing
call ng lint shared-currency-master-ui-currency-master-detail
call ng lint shared-country-master-data-access-country-master
call ng lint shared-corporate-town-data-access-corporate-town
call ng lint shared-location-master-ui-location-master-detail
call ng lint shared-complexity-code-ui-complexity-code-detail
call ng lint shared-payment-master-data-access-payment-master
call ng lint shared-product-category-ui-product-category-list
call ng lint shared-manual-cm-request-data-access-cm-request
call ng lint shared-cpg-qcgc-map-feature-cpg-qcgc-map-detail
call ng lint shared-components-ui-paginated-selection-dialog
call ng lint shared-activate-user-data-access-activate-user
call ng lint shared-corporate-town-ui-corporate-town-detail
call ng lint shared-cfa-product-feature-cfa-product-listing
call ng lint shared-market-code-feature-market-code-listing
call ng lint shared-upload-eghs-bank-deposit-ui-upload-eghs
call ng lint shared-complexity-code-ui-complexity-code-view
call ng lint shared-location-master-ui-location-master-list
call ng lint shared-complexity-code-ui-complexity-code-list
call ng lint shared-currency-master-ui-currency-master-list
call ng lint shared-complexity-code-feature-complexity-code
call ng lint shared-country-master-ui-country-master-detail
call ng lint shared-notifications-data-access-notifications
call ng lint shared-role-mgmt-shell-feature-shell-role-mgmt
call ng lint shared-role-config-feature-role-config-listing
call ng lint shared-payment-master-ui-payment-master-detail
call ng lint shared-forgot-password-feature-forgot-password
call ng lint shared-location-master-ui-location-master-view
call ng lint shared-payee-bank-ui-payee-bank-gl-code-pop-up
call ng lint shared-role-mgmt-shell-feature-role-mgmt-menu
call ng lint shared-cfa-product-feature-cfa-product-detail
call ng lint shared-corporate-town-ui-corporate-town-view
call ng lint shared-payment-master-ui-payment-master-list
call ng lint shared-corporate-town-ui-corporate-town-list
call ng lint shared-bank-deposit-data-access-bank-deposit
call ng lint shared-payment-master-feature-payment-master
call ng lint shared-country-master-ui-country-master-list
call ng lint shared-cpg-qcgc-map-data-access-cpg-qcgc-map
call ng lint shared-metal-type-feature-metal-type-listing
call ng lint shared-tax-master-feature-tax-master-listing
call ng lint shared-payee-bank-feature-payee-bank-listing
call ng lint shared-sub-region-feature-sub-region-listing
call ng lint shared-stone-type-feature-stone-type-listing
call ng lint shared-manual-cm-request-ui-request-history
call ng lint shared-bc-requests-feature-bc-status-detail
call ng lint shared-payee-bank-feature-payee-bank-detail
call ng lint shared-file-upload-data-access-file-upload
call ng lint shared-permission-util-element-permissions
call ng lint shared-manual-cm-request-ui-cm-header-view
call ng lint shared-item-data-access-item-details-popup
call ng lint shared-market-code-data-access-market-code
call ng lint shared-price-group-data-access-price-group
call ng lint shared-item-master-data-access-item-master
call ng lint shared-cfa-product-data-access-cfa-product
call ng lint shared-activate-user-ui-activate-user-form
call ng lint shared-activate-user-feature-activate-user
call ng lint shared-tax-class-feature-tax-class-listing
call ng lint shared-notifications-feature-notifications
call ng lint shared-cpg-qcgc-map-ui-cpg-qcgc-map-detail
call ng lint shared-role-config-feature-request-listing
call ng lint shared-components-ui-selection-dialog-grid
call ng lint shared-role-config-data-access-role-config
call ng lint shared-manual-cm-request-ui-discount-view
call ng lint shared-tep-ui-tep-stone-details-list-grid
call ng lint shared-list-of-values-feature-lov-listing
call ng lint shared-forgot-password-ui-forgot-password
call ng lint shared-manual-cm-request-ui-customer-view
call ng lint shared-role-config-feature-request-detail
call ng lint shared-payer-bank-feature-payer-bank-list
call ng lint shared-payer-bank-ui-payer-bank-item-list
call ng lint shared-reports-feature-report-role-maping
call ng lint shared-tax-master-data-access-tax-master
call ng lint shared-cfa-product-ui-cfa-product-detail
call ng lint shared-metal-type-data-access-metal-type
call ng lint shared-cpg-qcgc-map-ui-cpg-qcgc-map-list
call ng lint shared-bank-deposit-feature-bank-deposit
call ng lint shared-price-group-ui-price-group-detail
call ng lint shared-sub-region-data-access-sub-region
call ng lint shared-appsetting-data-access-appsetting
call ng lint shared-payer-bank-data-access-payer-bank
call ng lint shared-permission-data-access-permission
call ng lint shared-market-code-ui-market-code-detail