call ng lint  poss-shared-discount-data-access-discount
call ng lint  poss-walk-ins-data-access-walk-ins-record
call ng lint  poss-metal-rates-data-access-metal-rates
call ng lint  poss-shared-gift-voucher-ui-gift-voucher
call ng lint  poss-cash-memo-feature-regular-cash-memo
call ng lint  poss-ct-advance-feature-ct-advance-shell
call ng lint  poss-customer-town-ui-customer-town-list
call ng lint  poss-cash-memo-feature-tolerance-details
call ng lint  poss-cash-memo-feature-cash-memo-history
call ng lint  poss-cn-transfer-data-access-cn-transfer
call ng lint  poss-cn-transfer-ui-cn-transfer-details
call ng lint  poss-shared-toolbar-data-access-toolbar
call ng lint  poss-advance-booking-ui-advance-booking
call ng lint  poss-pif-series-feature-pif-series-list
call ng lint  poss-gift-cards-feature-gift-cards-sale
call ng lint  poss-shared-product-data-access-product
call ng lint  poss-cash-memo-feature-manual-cash-memo
call ng lint  poss-ct-advance-feature-accept-advance
call ng lint  poss-cash-memo-feature-quick-cash-memo
call ng lint  poss-gift-cards-ui-cm-list-grid-pop-up
call ng lint  poss-gift-cards-data-access-gift-cards
call ng lint  poss-metal-rates-ui-update-metal-rates
call ng lint  poss-bod-eod-ui-eghs-offline-bod-popup
call ng lint  poss-bod-eod-ui-eghs-offline-eod-popup
call ng lint  poss-pif-series-data-access-pif-series
call ng lint  poss-tep-ui-refund-payment-mode-fields
call ng lint  poss-shared-discount-feature-discount
call ng lint  poss-walk-ins-feature-walk-ins-record
call ng lint  poss-gift-cards-ui-gift-cards-cm-list
call ng lint  poss-printer-config-ui-printer-config
call ng lint  poss-bod-eod-ui-users-active-sessions
call ng lint  poss-grf-ui-grf-history-item-listing
call ng lint  poss-metal-rates-feature-metal-rates
call ng lint  poss-foc-ui-pending-foc-product-grid
call ng lint  poss-cash-memo-ui-occasion-selection
call ng lint  poss-credit-note-ui-cn-details-views
call ng lint  poss-grf-feature-grf-history-detail
call ng lint  poss-foc-feature-search-pending-foc
call ng lint  poss-tep-ui-cut-piece-tep-item-grid
call ng lint  poss-pif-series-ui-pif-series-items
call ng lint  poss-tep-feature-tep-refund-request
call ng lint  poss-shared-product-feature-product
call ng lint  poss-shared-toolbar-feature-toolbar
call ng lint  poss-cash-memo-ui-cash-memo-history
call ng lint  poss-credit-note-feature-cn-details
call ng lint  poss-tep-feature-tep-request-shell
call ng lint  poss-shared-ui-manual-form-details
call ng lint  poss-foc-feature-issue-pending-foc
call ng lint  poss-sales-home-feature-sales-home
call ng lint  poss-credit-note-feature-cn-search
call ng lint eposs-request-approvals-feature-other-issues-approval-details
call ng lint eposs-cashback-offer-config-data-access-cashback-offer-config
call ng lint eposs-grn-approval-config-feature-grn-approval-config-listing
call ng lint eposs-gl-location-payment-feature-gl-location-payment-listing
call ng lint eposs-grn-request-approvals-data-access-grn-request-approvals
call ng lint eposs-payment-configuration-data-access-payment-configuration
call ng lint eposs-stock-issue-tep-gep-feature-stock-issue-tep-gep-details
call ng lint eposs-ab-cancellation-requests-ab-cancellation-requests-shell
call ng lint eposs-ab-tolerance-config-feature-ab-tolerance-config-details
call ng lint eposs-request-approvals-feature-ibt-request-approval-details
call ng lint eposs-payment-configuration-ui-payment-configuration-listing
call ng lint eposs-cash-payment-config-feature-cash-payment-config-detail
call ng lint eposs-other-issue-ui-other-issue-exhibition-create-item-list
call ng lint eposs-grn-approval-config-feature-grn-approval-config-detail
call ng lint eposs-tep-validation-config-ui-tep-validation-config-detail
call ng lint eposs-ftep-approval-config-data-access-ftep-approval-config
call ng lint eposs-gl-boutique-location-data-access-gl-boutique-location
call ng lint eposs-inventory-global-config-data-access-inv-global-config
call ng lint eposs-tep-exception-config-data-access-tep-exception-config
call ng lint eposs-order-payment-config-data-access-order-payment-config
call ng lint eposs-cashback-offer-config-ui-cashback-offer-config-detail
call ng lint eposs-grf-tolerance-config-data-access-grf-tolerance-config
call ng lint eposs-cn-priority-config-feature-cn-priority-config-listing
call ng lint eposs-residual-weight-config-ui-residual-weight-config-view
call ng lint eposs-grn-tolerance-config-data-access-grn-tolerance-config
call ng lint eposs-gv-redemption-config-data-access-gv-redemption-config
call ng lint eposs-bgr-tolerance-config-data-access-bgr-tolerance-config
call ng lint  eposs-payment-configuration-ui-payment-configuration-detail
call ng lint  eposs-order-payment-config-ui-order-payment-config-listing
call ng lint  eposs-other-receipt-issue-feature-other-receipt-issue-list
call ng lint  eposs-request-approvals-ui-ibt-request-approvals-item-list
call ng lint  eposs-bgr-tolerance-config-ui-bgr-tolerance-config-listing
call ng lint  eposs-clubbing-discount-config-ui-clubbing-discount-config
call ng lint  eposs-gl-boutique-location-ui-gl-boutique-location-listing
call ng lint  eposs-request-approvals-ui-other-issue-approvals-item-list
call ng lint  eposs-cn-priority-config-feature-cn-priority-config-detail
call ng lint  eposs-ab-manual-requests-ab-manual-requests-detail-feature
call ng lint  eposs-ftep-approval-config-ui-ftep-approval-config-listing
call ng lint  eposs-grn-interboutique-config-ui-grn-interboutique-config
call ng lint  eposs-stock-issue-tep-gep-ui-stock-issue-tep-gep-item-list
call ng lint  eposs-bgr-tolerance-config-ui-bgr-tolerance-config-details
call ng lint  eposs-discount-config-ui-discount-product-category-mapping
call ng lint  eposs-payer-bank-config-feature-payer-bank-config-details
call ng lint  eposs-max-flat-tep-config-data-access-max-flat-tep-config
call ng lint  eposs-tep-validation-config-ui-tep-validation-config-list
call ng lint  eposs-stock-issue-tep-gep-data-access-stock-issue-tep-gep
call ng lint  eposs-grn-tolerance-config-ui-grn-tolerance-config-detail
call ng lint  eposs-ftep-approval-config-ui-ftep-approval-config-detail
call ng lint  eposs-gl-boutique-location-ui-gl-boutique-location-detail
call ng lint  eposs-ab-activation-requests-ab-activation-requests-shell