export enum GiftVoucherStatusDropdownEnum {
  REDEEMABLE_CODE = 'REDEEMABLE',
  REDEEMABLE_VALUE = 'REDEEMABLE',

  INACTIVE_CODE = 'INACTIVE',
  INACTIVE_VALUE = 'INACTIVE',

  ISSUEDTORO_CODE = 'ISSUEDTORO',
  ISSUEDTORO_VALUE = 'ISSUED TO RO',

  FOR_INWARDING_CODE = 'FOR_INWARDING',
  FOR_INWARDING_VALUE = 'FOR INWARDING',

  BLOCKED_CODE = 'BLOCKED',
  BLOCKED_VALUE = 'BLOCKED',

  REDEEMED_CODE = 'REDEEMED',
  REDEEMED_VALUE = 'REDEEMED',

  CANCELLED_CODE = 'CANCELLED',
  CANCELLED_VALUE = 'CANCELLED',

  FORCECLOSED_CODE = 'FORCECLOSED',
  FORCECLOSED_VALUE = 'FORCECLOSED',

  EXPIRED_CODE = 'EXPIRED',
  EXPIRED_VALUE = 'EXPIRED',

  AUTO_CANCELLATION_CODE = 'AUTO_CANCELLATION',
  AUTO_CANCELLATION_VALUE = 'AUTO CANCELLATION'
}

export enum GiftVoucherInputField {
  SCAN_CODE = 'SCAN',
  SCAN_VALUE = 'SCAN',

  MANUAL_CODE = 'MANUAL',
  MANUAL_VALUE = 'MANUAL',

  MANY_CODE = 'MANY',
  MANY_ALUE = 'MANY'
}
