export enum CUSTOMER_TYPE_ENUM {
  REGULAR = 'REGULAR',
  INTERNATIONAL = 'INTERNATIONAL',
  INSTITUTIONAL = 'INSTITUTIONAL',
  ONE_TIME = 'ONETIME'
}

export enum SEARCH_BY_ENUM {
  MOBILE_NO = 'MOBILE_NO',
  ULP_ID = 'ULP_ID',
  PAN_NO = 'CUSTOMER_TAX_NO',
  GST_NO = 'INSTITUTIONAL_TAX_NO',
  PASSPORT_ID = 'PASSPORT_ID',
  EMAIL_ID = 'EMAIL_ID',
  CUSTOMER_NAME = 'CUSTOMER_NAME',
  CUSTOMER_ID = 'CUSTOMER_ID'
}

export enum CUSTOMER_MEMBER_TYPE {
  GOLD = 'GOLD',
  SILVER = 'SILVER',
  PLATINUM = 'PLATINUM'
}

export enum VERIFICATION_TYPE {
  PAN_CARD = 'PAN_CARD',
  FORM60_IDPROOF = 'FORM60_IDPROOF'
}
