/*  
 * Copyright 2019. Titan Company Limited
 * All rights reserved.
 */

package com.titan.poss.datasync.util;

/**
 * 
 * @author Mindtree Ltd.
 * @version 1.0
 */

public enum OperationCodesEnum {
	COUNTRY, CURRENCY, LOCATION_PRICE_GROUP_MAPPING, LOCATION, MARKET, METAL_PRICE_LOCATION_MAPPING, PINCODE, REGION,
	STATE, STATETAX, TAXCLASS, TAXCONFIGS, TOWN, ORGANIZATION, BRAND, COMPLEXITY, ITEM, LOT, MATERIAL, PRICE_GROUP,
	PRICE, PRODUCT_CATEGORY, PRODUCT_GROUP, PURITY, STONE, STONE_TYPE, COMPLEXITY_PRICEGROUP, ITEM_STONE, BINGROUP, BIN,
	BIN_LOCATION_MAPPING, MATERIAL_TYPE, ITEM_MATERIAL, CHANGEPSWD, VERIFYOTP, CORPUSER, STOREUSER, STORETEMPORARYUSER,
	ROLE, RULE, RULE_LOC_MAPPING, RULE_PGRP_MAPPING, PAYMENT_LOV, PAYER_BANK, PAYEE_BANK, PAYER_BANK_CONFIG,
	PAYEE_BANK_LOCATION, PAYMENT, PAYMENT_CATEGORY, PAYMENT_CATEGORY_PRODUCT, PAYMENT_CONFIG, PAYMENT_CONFIG_DETAILS,
	PAYMENT_CONFIG_LOCATION, CASHBACK, CASHBACK_PRODUCT, CASHBACK_CARD_DETAILS, CASHBACK_OFFER_DETAILS,
	PAYER_BANK_LOCATION, PAYER_BANK_PRIORITY_MAPPING, CATCHMENT, CUSTOMER_TOWN, ADVANCE_CONFIRM, CANCEL_CONFIRM,
	GEP_CONFIRM, TEP_CONFIRM, GRF_UPDATE, RANGE, EXCHANGE_CONFIG, INV, ORDER, BANK_DEPOSIT, PIF_SERIES_UPDATE,
	EXCHANGE_CONFIG_DETAILS, EXCHANGE_CONFIG_LOCATION, EXCHANGE_CONFIG_PRODUCT, EXCHANGE_CONFIG_THEME,
	EXCHANGE_CONFIG_ITEMS, CUSTOMER, PENDING_FOC_CM, LOT_STONE_DETAILS, LOT_MATERIAL_DETAILS, BUSINESS_DAY,
	CUSTOMER_VISIT, RULE_MARKET_MAPPING, EXCHANGE_CONFIG_STONE, PRINTER_CONFIGURATION, PAYER_CONFIG_DETAILS_UPDATE,
	STATETAXDETAILS, PAYMENT_CUSTOMER_MAPPING, DISCOUNT_PUBLISH, FOC_PUBLISH, PAYMENT_HOSTNAME_MAPPING,
	MARKET_MARKUP_MAPPING, SALES_DOC, GRN_CONFIRM, CONFIG_LOV, LOCATION_LOV, PRODUCT_LOV, RULE_RANGE_MAPPING,
	DISCOUNT_CLUB_MAPPING, ACCOUNT_DETAILS, SCHEDULAR, INVENTORY_JOB, JOB, DEPOSITE_SUMMARY, GRF_MERGE, VENDOR_CONFIGS,
	CREDIT_NOTE, CUSTOMER_DOCUMENT, CASHMEMO, ITEM_GROUP_LEVEL_DISCOUNT, MARKET_UCP_PRICE_MAPPING,
	PRODUCT_PRICE_MAPPING, MANUAL_FOC, CN_EPOSS, CN_WORKFLOW, CN_REVERSE, RIVAAH_PGRP_MAPPING, CUTPIECE_CONFIRM,
	CREDIT_NOTE_UPDATE, SALES_DISCOUNT, CASHBACK_CARD, SALES_ORDER_CONFIG,CUSTOMER_PAYMENT_DETAILS,PAYMENT_REQUEST ,CUSTOMER_TCS_DETAILS,
	DOC_NUMBER_FAIL_AUDIT,SALES_INVOICE_DOCUMENTS

}
