package com.titan.poss.sales.dto.constants;

public enum ApplicableTransactionTypes {

	ADVANCEORDERORBOOKING,CASHMEMO,GHS,ACCEPTADVANCE,GRN
	,GRF,GIFTCARD,CNCANCELLATION,TEPDECLARATION,
	GEPDECLARATION, CCAF,BILLCANCELLATION
	
}
